codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 72%
        threshold: 0%
        informational: false
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 0%
        informational: false
        if_ci_failed: error

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
