// Code generated by flutter_go_bridge_codegen. DO NOT EDIT.
// ignore_for_file: unused_element, unused_import, unnecessary_import
import "../bridge_generated.dart";
import 'dart:async';
import 'dart:typed_data';

final class Point {
  final int x;
  final int y;
  String label;

  Point({required this.x, required this.y, required this.label});

  /// Moved returns a copy of the point shifted by (dx, dy).
  Point moved({required int dx, required int dy}) {
    return FlutterGoBridge.instance.fgbInternalCall1(this, dx, dy);
  }

  @override
  String toString() => 'Point(x: $x, y: $y, label: $label)';

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Point &&
          other.runtimeType == runtimeType &&
          fgbInternalDeepEquals(x, other.x) &&
          fgbInternalDeepEquals(y, other.y) &&
          fgbInternalDeepEquals(label, other.label);

  @override
  int get hashCode {
    var result = runtimeType.hashCode;
    result = result * 31 + fgbInternalDeepHash(x);
    result = result * 31 + fgbInternalDeepHash(y);
    result = result * 31 + fgbInternalDeepHash(label);
    return result;
  }
}

/// Counter keeps its state on the Go side and crosses the bridge as a
/// GoOpaque handle.
final class Counter extends GoOpaque {
  Counter.fgbInternal({required super.fgbBridge, required super.fgbHandle});

  int add({required int delta}) {
    return fgbBridge.fgbInternalCall3(this, delta);
  }
}

String greeting({required String name}) {
  final bridge = FlutterGoBridge.instance;
  return bridge.fgbInternalCall0(name);
}

Counter? newCounter() {
  final bridge = FlutterGoBridge.instance;
  return bridge.fgbInternalCall2();
}
