// Code generated by flutter_go_bridge_codegen. DO NOT EDIT.
// ignore_for_file: unused_element, unused_import, unnecessary_import
import "../bridge_generated.dart";
import 'dart:async';
import 'dart:typed_data';

final class Point {
  final int x;
  final int y;
  String label;

  Point({required this.x, required this.y, required this.label});

  /// Moved returns a copy of the point shifted by (dx, dy).
  Point moved({required int dx, required int dy}) {
    return FlutterGoBridge.instance.fgbInternalCall1(this, dx, dy);
  }
}

/// Counter keeps its state on the Go side and crosses the bridge as a
/// GoOpaque handle.
final class Counter extends GoOpaque {
  Counter.fgbInternal({required super.fgbBridge, required super.fgbHandle});

  int add({required int delta}) {
    return fgbBridge.fgbInternalCall3(this, delta);
  }
}

String greeting({required String name}) {
  final bridge = FlutterGoBridge.instance;
  return bridge.fgbInternalCall0(name);
}

Counter? newCounter() {
  final bridge = FlutterGoBridge.instance;
  return bridge.fgbInternalCall2();
}
