// Code generated by flutter_go_bridge_codegen. DO NOT EDIT.
// ignore_for_file: unused_element, unused_import, unnecessary_import
// Static analysis selects the IO conditional import; Web compilation selects this library.
// ignore_for_file: argument_type_not_assignable
import 'dart:async';
import 'dart:convert';
import 'dart:js_interop';
import 'dart:js_interop_unsafe';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'dart:typed_data';
import "bridge_generated.dart";
import "api/lib.dart";

/// Base class for generated opaque Go handles. Web methods using opaque
/// handles currently fail before transport, so no native finalizer is needed.
abstract base class GoOpaque {
  GoOpaque({required this.fgbBridge, required this.fgbHandle});

  final FlutterGoBridge fgbBridge;
  final int fgbHandle;
}

const _fgbWasmAssetPackage = "REPLACE_ME_GO_MOD_NAME";
const _fgbWasmAssetKeyRoot = 'packages/$_fgbWasmAssetPackage/assets/wasm';
const _fgbWasmAssetUrlRoot = 'assets/$_fgbWasmAssetKeyRoot';

final class FgbWasmManifest {
  FgbWasmManifest._(this.libraryName, this.wasmAsset, this.wasmExecAsset);

  final String libraryName;
  final String wasmAsset;
  final String wasmExecAsset;

  static FgbWasmManifest parse(String raw) {
    final value = jsonDecode(raw);
    if (value is! Map) {
      throw const FormatException('fgb_wasm_manifest.json must contain an object');
    }
    if (value['target'] != 'web-wasm' || value['schema_version'] != 1) {
      throw const FormatException('unsupported Gokit Web Wasm manifest');
    }
    final libraryName = value['library_name'];
    final artifacts = value['artifacts'];
    if (libraryName is! String || artifacts is! Map) {
      throw const FormatException('Web Wasm manifest is missing library_name or artifacts');
    }
    final wasm = artifacts.keys.whereType<String>().firstWhere(
      (key) => key.endsWith('.wasm'),
      orElse: () => throw const FormatException('Web Wasm manifest has no .wasm artifact'),
    );
    if (!artifacts.containsKey('wasm_exec.js')) {
      throw const FormatException('Web Wasm manifest has no wasm_exec.js artifact');
    }
    return FgbWasmManifest._(
      libraryName,
      '$_fgbWasmAssetUrlRoot/$wasm',
      '$_fgbWasmAssetUrlRoot/wasm_exec.js',
    );
  }
}

final class FgbWasmLoader {
  static Future<void>? _ready;

  static Future<void> ensureReady({AssetBundle? bundle}) async {
    if (_ready != null) {
      return _ready!;
    }
    _ready = _ensureReady(bundle: bundle);
    return _ready!;
  }

  static Future<void> _ensureReady({AssetBundle? bundle}) async {
    WidgetsFlutterBinding.ensureInitialized();
    final assets = bundle ?? rootBundle;
    final manifest = FgbWasmManifest.parse(
      await assets.loadString('$_fgbWasmAssetKeyRoot/fgb_wasm_manifest.json'),
    );
    await _loadScript(manifest.wasmExecAsset);
    final goConstructor = globalContext.getProperty<JSFunction?>('Go'.toJS);
    if (goConstructor == null) {
      throw StateError('wasm_exec.js did not register the Go constructor');
    }
    final go = goConstructor.callAsConstructor<JSObject>();
    final fetch = globalContext.getProperty<JSFunction>('fetch'.toJS);
    final response = fetch.callAsFunction(null, manifest.wasmAsset.toJS);
    final webAssembly = globalContext.getProperty<JSObject>('WebAssembly'.toJS);
    final instantiate = webAssembly.getProperty<JSFunction>('instantiateStreaming'.toJS);
    final importObject = go.getProperty<JSObject>('importObject'.toJS);
    final result =
        await (instantiate.callAsFunction(null, response, importObject) as JSPromise<JSAny?>)
            .toDart;
    if (result == null || !result.isA<JSObject>()) {
      throw StateError('WebAssembly.instantiateStreaming returned no instance');
    }
    final instance = (result as JSObject).getProperty<JSObject>('instance'.toJS);
    final run = go.getProperty<JSFunction>('run'.toJS);
    run.callAsFunction(go, instance);
    await _waitForBridge(manifest.libraryName);
  }

  static Future<void> _loadScript(String asset) async {
    final document = globalContext.getProperty<JSObject>('document'.toJS);
    final createElement = document.getProperty<JSFunction>('createElement'.toJS);
    final script = createElement.callAsFunction(document, 'script'.toJS);
    if (script == null || !script.isA<JSObject>()) {
      throw StateError('could not create wasm_exec.js script element');
    }
    final completed = Completer<void>();
    final scriptElement = script as JSObject;
    scriptElement.setProperty('src'.toJS, asset.toJS);
    scriptElement.setProperty(
      'onload'.toJS,
      (() {
        if (!completed.isCompleted) {
          completed.complete();
        }
      }).toJS,
    );
    scriptElement.setProperty(
      'onerror'.toJS,
      (() {
        if (!completed.isCompleted) {
          completed.completeError(StateError('failed to load $asset'));
        }
      }).toJS,
    );
    final head = document.getProperty<JSObject>('head'.toJS);
    head.getProperty<JSFunction>('appendChild'.toJS).callAsFunction(head, scriptElement);
    await completed.future;
  }

  static Future<void> _waitForBridge(String libraryName) async {
    for (var attempt = 0; attempt < 200; attempt++) {
      final registry = globalContext.getProperty<JSObject?>('__flutterGoBridge'.toJS);
      if (registry?.getProperty<JSFunction?>(libraryName.toJS) != null) {
        return;
      }
      await Future<void>.delayed(const Duration(milliseconds: 10));
    }
    throw StateError('Go Wasm bridge $libraryName did not register within 2 seconds');
  }
}

final class FlutterGoBridge {
  FlutterGoBridge._();

  static FlutterGoBridge? _instance;

  static FlutterGoBridge get instance => _instance ??= FlutterGoBridge._();

  static FlutterGoBridge open({String? libraryPath}) {
    if (libraryPath != null) {
      throw UnsupportedError('libraryPath is not used by the Web Wasm transport');
    }
    return instance;
  }

  static Future<void> initialize({
    String? libraryPath,
    Future<void> Function()? webInitializer,
  }) async {
    await (webInitializer ?? _defaultWebInitializer)();
    open(libraryPath: libraryPath);
  }

  static Future<void> _defaultWebInitializer() async {
    WidgetsFlutterBinding.ensureInitialized();
    await FgbWasmLoader.ensureReady();
  }

  Object? fgbInvokeSync(String method, List<Object?> arguments) {
    const libraryName = "REPLACE_ME_GO_MOD_NAME";
    final registry = globalContext.getProperty<JSObject?>('__flutterGoBridge'.toJS);
    if (registry == null) {
      throw StateError(
        'Go Wasm runtime is not initialized; load wasm_exec.js and the .wasm artifact first',
      );
    }
    final invoke = registry.getProperty<JSFunction?>(libraryName.toJS);
    if (invoke == null) {
      throw StateError('Go Wasm bridge $libraryName is not registered');
    }
    final request = fgbInternalEncodeMethodCall(method, arguments);
    final rawResponse = invoke.callAsFunction(null, request.toJS);
    if (rawResponse == null || !rawResponse.isA<JSUint8Array>()) {
      throw StateError('Go Wasm bridge returned a non-Uint8Array response');
    }
    return fgbInternalDecodeEnvelope((rawResponse as JSUint8Array).toDart);
  }

  Future<Object?> fgbInvokeAsync(String method, List<Object?> arguments) async {
    return fgbInvokeSync(method, arguments);
  }

  void fgbAttachOpaqueFinalizer(Object object, int handle) {}

  int fgbInternalRegisterDartOpaque(Object value) {
    throw UnsupportedError('DartOpaque is not supported by the Web Wasm transport');
  }

  Object fgbInternalResolveDartOpaque(int handle, String path) {
    throw UnsupportedError('$path: DartOpaque is not supported by the Web Wasm transport');
  }

  int fgbInternalRegisterCallback(Future<Object?> Function(List<Object?> args) invoker) {
    throw UnsupportedError('Dart callbacks are not supported by the Web Wasm transport');
  }

  int fgbInternalRegisterStreamSink(StreamSink<dynamic> sink, void Function(Object? raw) add) {
    throw UnsupportedError('streams are not supported by the Web Wasm transport');
  }

  void fgbInternalStartStream<T>(StreamController<T> controller, Future<void> call) {
    throw UnsupportedError('streams are not supported by the Web Wasm transport');
  }
}

extension FgbGeneratedCalls on FlutterGoBridge {
  String fgbInternalCall0(String name) {
    final wireResult = fgbInvokeSync("Greeting", <Object?>[fgbEncode0(name, this, "name", 0)]);
    return fgbDecode0(wireResult, this, 'result');
  }

  Point fgbInternalCall1(Point receiver, int dx, int dy) {
    final wireResult = fgbInvokeSync("Point.Moved", <Object?>[
      fgbEncode1(receiver, this, "receiver", 0),
      fgbEncode2(dx, this, "dx", 0),
      fgbEncode2(dy, this, "dy", 0),
    ]);
    return fgbDecode1(wireResult, this, 'result');
  }

  Counter? fgbInternalCall2() {
    throw UnsupportedError(
      "Go method NewCounter is unavailable on Web: opaque handles and interfaces are not supported by the Web transport",
    );
  }

  int fgbInternalCall3(Counter receiver, int delta) {
    throw UnsupportedError(
      "Go method Add is unavailable on Web: opaque handles and interfaces are not supported by the Web transport",
    );
  }
}
