// Code generated by flutter_go_bridge_codegen. DO NOT EDIT.
// ignore_for_file: unused_element, unused_import, unnecessary_import
import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';
import "bridge_generated.io.dart" if (dart.library.js_interop) "bridge_generated.web.dart";
export "bridge_generated.io.dart" if (dart.library.js_interop) "bridge_generated.web.dart";
import "api/lib.dart";

final class FgbPlatformException implements Exception {
  FgbPlatformException(this.code, this.message, this.details, {this.goErrors});

  final String code;
  final String? message;
  final Object? details;

  /// The individual Go errors, when the call declares several error results.
  /// Null for a call with at most one error result - use [message] there.
  final FgbGoErrors? goErrors;

  @override
  String toString() => 'FgbPlatformException($code, $message, $details)';
}

/// The combined errors of a Go call that declares several error results: every
/// non-nil one is collected instead of only the first.
final class FgbGoErrors implements Exception {
  const FgbGoErrors(this.messages);

  final List<String> messages;

  int get length => messages.length;

  String operator [](int index) => messages[index];

  @override
  String toString() => 'FgbGoErrors(${messages.join('; ')})';
}

/// Reads the individual error messages out of an error envelope's details.
/// The standard codec sends the whole details map; the DCO path, which has no
/// map type, sends a plain list of messages.
FgbGoErrors? fgbInternalGoErrorsFrom(Object? details) {
  Object? errors = details;
  if (details is Map) {
    errors = details['errors'];
  }
  if (errors is! List) {
    return null;
  }
  return FgbGoErrors(List<String>.unmodifiable(errors.map((Object? error) => '$error')));
}

/// Internal: unwraps the list carrying a call's several results.
List<Object?> fgbAsResultList(Object? value, int count) {
  if (value is! List || value.length != count) {
    throw FormatException('expected $count results, got $value');
  }
  return value;
}

/// Base class for generated opaque Go handles. The generated source files do
/// not need to expose dart:ffi; finalizer plumbing stays in this integration
/// library.

abstract interface class GoAbsent {}

/// Structural equality for the fields of a generated value class.
///
/// Dart compares List and Map by identity, which contradicts Go value
/// semantics: two structs decoded from the same wire bytes must be equal.
bool fgbInternalDeepEquals(Object? left, Object? right) {
  if (identical(left, right)) {
    return true;
  }
  if (left == null || right == null) {
    return false;
  }
  if (left is List && right is List) {
    if (left.length != right.length) {
      return false;
    }
    for (var index = 0; index < left.length; index++) {
      if (!fgbInternalDeepEquals(left[index], right[index])) {
        return false;
      }
    }
    return true;
  }
  if (left is Map && right is Map) {
    if (left.length != right.length) {
      return false;
    }
    // A scalar key can be looked up directly, which keeps this linear. A
    // generated class key also works, because its own == and hashCode are
    // structural. Anything else falls back to pairwise matching.
    if (left.keys.every(_fgbLooksUpByValue)) {
      for (final entry in left.entries) {
        if (!right.containsKey(entry.key)) {
          return false;
        }
        if (!fgbInternalDeepEquals(entry.value, right[entry.key])) {
          return false;
        }
      }
      return true;
    }
    final unmatched = right.entries.toList();
    for (final leftEntry in left.entries) {
      final index = unmatched.indexWhere(
        (rightEntry) =>
            fgbInternalDeepEquals(leftEntry.key, rightEntry.key) &&
            fgbInternalDeepEquals(leftEntry.value, rightEntry.value),
      );
      if (index < 0) {
        return false;
      }
      unmatched.removeAt(index);
    }
    return true;
  }
  return left == right;
}

bool _fgbLooksUpByValue(Object? key) =>
    key == null || key is String || key is num || key is bool || key is Enum;

/// Hash companion to [fgbInternalDeepEquals], combining with the same factor
/// the generated hashCode uses. Map entries are combined commutatively so
/// insertion order cannot change the result.
int fgbInternalDeepHash(Object? value) {
  if (value == null) {
    return 0;
  }
  if (value is List) {
    var result = 1;
    for (final item in value) {
      result = result * 31 + fgbInternalDeepHash(item);
    }
    return result;
  }
  if (value is Map) {
    var result = 0;
    for (final entry in value.entries) {
      result ^= fgbInternalDeepHash(entry.key) * 31 + fgbInternalDeepHash(entry.value);
    }
    return result;
  }
  return value.hashCode;
}

/// Wraps a registered Dart closure so the callback dispatcher can tell it
/// apart from plain DartOpaque objects sharing the same registry.
final class FgbInternalCallbackInvoker {
  FgbInternalCallbackInvoker(this.invoke);

  final Future<Object?> Function(List<Object?> args) invoke;
}

/// A Dart sink Go pushes values into, together with the typed add closure the
/// generated encoder built for it.
final class FgbInternalStreamTarget {
  FgbInternalStreamTarget(this.sink, this.add);

  final StreamSink<dynamic> sink;
  final void Function(Object? raw) add;
}

final class _FgbWriter {
  final BytesBuilder _bytes = BytesBuilder(copy: false);

  int get length => _bytes.length;

  void byte(int value) => _bytes.addByte(value & 0xff);

  void bytes(Iterable<int> value) =>
      _bytes.add(value is List<int> ? value : value.toList(growable: false));

  void alignment(int size) {
    final padding = (size - length % size) % size;
    if (padding != 0) {
      bytes(List<int>.filled(padding, 0));
    }
  }

  void size(int value) {
    if (value < 0) {
      throw FormatException('negative message size');
    }
    if (value < 254) {
      byte(value);
    } else if (value <= 0xffff) {
      byte(254);
      final data = ByteData(2)..setUint16(0, value, Endian.host);
      bytes(data.buffer.asUint8List());
    } else {
      byte(255);
      final data = ByteData(4)..setUint32(0, value, Endian.host);
      bytes(data.buffer.asUint8List());
    }
  }

  void int32(int value) {
    final data = ByteData(4)..setInt32(0, value, Endian.host);
    bytes(data.buffer.asUint8List());
  }

  void int64(int value) {
    final data = ByteData(8)..setInt64(0, value, Endian.host);
    bytes(data.buffer.asUint8List());
  }

  void float64(double value) {
    alignment(8);
    final data = ByteData(8)..setFloat64(0, value, Endian.host);
    bytes(data.buffer.asUint8List());
  }

  Uint8List finish() => _bytes.takeBytes();
}

final class _FgbReader {
  _FgbReader(this._bytes);

  final Uint8List _bytes;
  int _offset = 0;

  bool get hasRemaining => _offset < _bytes.length;
  int get remaining => _bytes.length - _offset;

  int byte() {
    if (_offset >= _bytes.length) {
      throw const FormatException('unexpected end of message');
    }
    return _bytes[_offset++];
  }

  Uint8List bytes(int length) {
    if (length < 0 || remaining < length) {
      throw const FormatException('message is truncated');
    }
    final result = Uint8List.sublistView(_bytes, _offset, _offset + length);
    _offset += length;
    return result;
  }

  void alignment(int size) {
    final padding = (size - _offset % size) % size;
    if (remaining < padding) {
      throw const FormatException('message alignment is truncated');
    }
    _offset += padding;
  }

  int size() {
    final marker = byte();
    if (marker < 254) {
      return marker;
    }
    if (marker == 254) {
      final data = ByteData.sublistView(bytes(2));
      return data.getUint16(0, Endian.host);
    }
    final data = ByteData.sublistView(bytes(4));
    return data.getUint32(0, Endian.host);
  }

  int count(int elementSize) {
    final length = size();
    if (length < 0 || (elementSize > 0 && length > remaining ~/ elementSize)) {
      throw const FormatException('message is truncated');
    }
    return length;
  }

  int int32() => ByteData.sublistView(bytes(4)).getInt32(0, Endian.host);

  int int64() => ByteData.sublistView(bytes(8)).getInt64(0, Endian.host);

  double float64() {
    alignment(8);
    return ByteData.sublistView(bytes(8)).getFloat64(0, Endian.host);
  }

  Object? value() {
    switch (byte()) {
      case 0:
        return null;
      case 1:
        return true;
      case 2:
        return false;
      case 3:
        return int32();
      case 4:
        return int64();
      case 5:
        // Flutter's base StandardMessageCodec exposes large integers received
        // from native code as their hexadecimal String representation.
        return utf8.decode(bytes(size()));
      case 6:
        return float64();
      case 7:
        return utf8.decode(bytes(size()));
      case 8:
        return bytes(size());
      case 9:
        final result = Int32List(count(4));
        alignment(4);
        for (var index = 0; index < result.length; index++) {
          result[index] = int32();
        }
        return result;
      case 10:
        final result = Int64List(count(8));
        alignment(8);
        for (var index = 0; index < result.length; index++) {
          result[index] = int64();
        }
        return result;
      case 11:
        final result = Float64List(count(8));
        alignment(8);
        for (var index = 0; index < result.length; index++) {
          result[index] = float64();
        }
        return result;
      case 12:
        final result = <Object?>[];
        for (var index = 0, length = count(1); index < length; index++) {
          result.add(value());
        }
        return result;
      case 13:
        final result = <Object?, Object?>{};
        for (var index = 0, length = count(2); index < length; index++) {
          result[value()] = value();
        }
        return result;
      case 14:
        final result = Float32List(count(4));
        alignment(4);
        for (var index = 0; index < result.length; index++) {
          final data = ByteData.sublistView(bytes(4));
          result[index] = data.getFloat32(0, Endian.host);
        }
        return result;
      default:
        throw const FormatException('unknown StandardMessageCodec type');
    }
  }
}

final class _FgbCodec {
  const _FgbCodec();

  Uint8List encodeMethodCall(String method, Object? arguments) {
    final writer = _FgbWriter();
    _writeValue(writer, method);
    _writeValue(writer, arguments);
    return writer.finish();
  }

  Object? decodeEnvelope(Uint8List bytes) {
    final reader = _FgbReader(bytes);
    final flag = reader.byte();
    if (flag == 0) {
      final result = reader.value();
      if (reader.hasRemaining) {
        throw const FormatException('result envelope has trailing bytes');
      }
      return result;
    }
    if (flag == 1) {
      final code = reader.value();
      final message = reader.value();
      final details = reader.value();
      if (reader.hasRemaining) {
        throw const FormatException('error envelope has trailing bytes');
      }
      if (code is! String) {
        throw const FormatException('error code is not a String');
      }
      if (message != null && message is! String) {
        throw const FormatException('error message is not a String or null');
      }
      return throw FgbPlatformException(
        code,
        message as String?,
        details,
        goErrors: fgbInternalGoErrorsFrom(details),
      );
    }
    throw const FormatException('unknown method envelope flag');
  }

  void _writeValue(_FgbWriter writer, Object? value) {
    if (value == null) {
      writer.byte(0);
    } else if (value is bool) {
      writer.byte(value ? 1 : 2);
    } else if (value is double) {
      writer.byte(6);
      writer.float64(value);
      // ignore: avoid_double_and_int_checks, JS uses the double branch above
    } else if (value is int) {
      if (value >= -0x80000000 && value <= 0x7fffffff) {
        writer.byte(3);
        writer.int32(value);
      } else {
        writer.byte(4);
        writer.int64(value);
      }
    } else if (value is BigInt) {
      // The base Dart codec does not emit tag 5. Use the same hexadecimal
      // string convention understood by the generated Go decoder.
      writer.byte(7);
      final raw = utf8.encode(value.toRadixString(16));
      writer.size(raw.length);
      writer.bytes(raw);
    } else if (value is String) {
      writer.byte(7);
      final raw = utf8.encode(value);
      writer.size(raw.length);
      writer.bytes(raw);
    } else if (value is Uint8List) {
      writer.byte(8);
      writer.size(value.length);
      writer.bytes(value);
    } else if (value is Int32List) {
      writer.byte(9);
      writer.size(value.length);
      writer.alignment(4);
      for (final item in value) {
        writer.int32(item);
      }
    } else if (value is Int64List) {
      writer.byte(10);
      writer.size(value.length);
      writer.alignment(8);
      for (final item in value) {
        writer.int64(item);
      }
    } else if (value is Float64List) {
      writer.byte(11);
      writer.size(value.length);
      writer.alignment(8);
      for (final item in value) {
        writer.float64(item);
      }
    } else if (value is Float32List) {
      writer.byte(14);
      writer.size(value.length);
      writer.alignment(4);
      for (final item in value) {
        final data = ByteData(4)..setFloat32(0, item, Endian.host);
        writer.bytes(data.buffer.asUint8List());
      }
    } else if (value is List) {
      writer.byte(12);
      writer.size(value.length);
      for (final item in value) {
        _writeValue(writer, item);
      }
    } else if (value is Map) {
      writer.byte(13);
      writer.size(value.length);
      value.forEach((key, item) {
        _writeValue(writer, key);
        _writeValue(writer, item);
      });
    } else {
      throw FormatException('type ${value.runtimeType} is not supported by StandardMessageCodec');
    }
  }
}

final _fgbInternalCodec = _FgbCodec();

Uint8List fgbInternalEncodeMethodCall(String method, List<Object?> arguments) =>
    _fgbInternalCodec.encodeMethodCall(method, arguments);

Object? fgbInternalDecodeEnvelope(Uint8List bytes) => _fgbInternalCodec.decodeEnvelope(bytes);

Object? fgbInternalDecodeValue(Uint8List bytes) => _FgbReader(bytes).value();

Uint8List fgbInternalEncodeValue(Object? value) {
  final writer = _FgbWriter();
  _fgbInternalCodec._writeValue(writer, value);
  return writer.finish();
}

String fgbDecode0(Object? value, FlutterGoBridge bridge, String path) {
  if (value is! String) {
    throw FormatException('$path: expected String');
  }
  return value;
}

Object? fgbEncode0(String value, FlutterGoBridge bridge, String path, int depth) {
  if (depth > 64) {
    throw FormatException('$path: value nesting exceeds 64 levels (cyclic reference?)');
  }
  return value;
}

Point fgbDecode1(Object? value, FlutterGoBridge bridge, String path) {
  if (value is Map) {
    return Point(
      x: fgbDecode2(value["x"], bridge, '$path.x'),
      y: fgbDecode2(value["y"], bridge, '$path.y'),
      label: fgbDecode0(value["label"], bridge, '$path.label'),
    );
  }
  if (value is List) {
    if (value.length != 3) {
      throw FormatException('$path: expected 3 fields');
    }
    return Point(
      x: fgbDecode2(value[0], bridge, '$path[0]'),
      y: fgbDecode2(value[1], bridge, '$path[1]'),
      label: fgbDecode0(value[2], bridge, '$path[2]'),
    );
  }
  throw FormatException('$path: expected Map or List');
}

Object? fgbEncode1(Point value, FlutterGoBridge bridge, String path, int depth) {
  if (depth > 64) {
    throw FormatException('$path: value nesting exceeds 64 levels (cyclic reference?)');
  }
  return <Object?, Object?>{
    "x": fgbEncode2(value.x, bridge, '$path.x', depth + 1),
    "y": fgbEncode2(value.y, bridge, '$path.y', depth + 1),
    "label": fgbEncode0(value.label, bridge, '$path.label', depth + 1),
  };
}

int fgbDecode2(Object? value, FlutterGoBridge bridge, String path) {
  if (value is! int) {
    throw FormatException('$path: expected int');
  }
  return value;
}

Object? fgbEncode2(int value, FlutterGoBridge bridge, String path, int depth) {
  if (depth > 64) {
    throw FormatException('$path: value nesting exceeds 64 levels (cyclic reference?)');
  }
  return value;
}

Counter? fgbDecode3(Object? value, FlutterGoBridge bridge, String path) {
  if (value == null) {
    return null;
  }
  if (value is! int || value <= 0) {
    throw FormatException('$path: expected opaque handle');
  }
  return Counter.fgbInternal(fgbBridge: bridge, fgbHandle: value);
}

Object? fgbEncode3(Counter? value, FlutterGoBridge bridge, String path, int depth) {
  if (depth > 64) {
    throw FormatException('$path: value nesting exceeds 64 levels (cyclic reference?)');
  }
  if (value == null) {
    return null;
  }
  if (!identical(value.fgbBridge, bridge)) {
    throw StateError('opaque value belongs to a different bridge');
  }
  return value.fgbHandle;
}
