// Code generated by flutter_go_bridge_codegen. DO NOT EDIT.
// ignore_for_file: unused_element, unused_import, unnecessary_import
library flutter_go_bridge;

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'dart:io';
import 'dart:isolate';
import 'dart:typed_data';
import "lib.dart";
export "lib.dart";

final class _FgbCstBytes extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;
  @ffi.Int64()
  external int len;
}

final class _FgbCstArgs0 extends ffi.Struct {
  external ffi.Pointer<_FgbCstBytes> name;
}

final class _FgbCstArgs1 extends ffi.Struct {
  @ffi.UintPtr()
  external int receiver;
  @ffi.Int64()
  external int x;
  @ffi.Int64()
  external int y;
}

final class FgbPlatformException implements Exception {
  FgbPlatformException(this.code, this.message, this.details);

  final String code;
  final String? message;
  final Object? details;

  @override
  String toString() => 'FgbPlatformException($code, $message, $details)';
}

/// Base class for generated opaque Go handles. The generated source files do
/// not need to expose dart:ffi; finalizer plumbing stays in this integration
/// library.
abstract base class FgbOpaque implements ffi.Finalizable {
  FgbOpaque(this.fgbBridge, this.fgbHandle) {
    fgbBridge.fgbAttachOpaqueFinalizer(this, fgbHandle);
  }

  final FlutterGoBridge fgbBridge;
  final int fgbHandle;
}

final class _FgbWriter {
  final List<int> _bytes = <int>[];

  int get length => _bytes.length;

  void byte(int value) => _bytes.add(value & 0xff);

  void bytes(Iterable<int> value) => _bytes.addAll(value);

  void alignment(int size) {
    final padding = (size - length % size) % size;
    if (padding != 0) bytes(List<int>.filled(padding, 0));
  }

  void size(int value) {
    if (value < 0) throw FormatException('negative message size');
    if (value < 254) {
      byte(value);
    } else if (value <= 0xffff) {
      byte(254);
      final data = ByteData(2)..setUint16(0, value, Endian.host);
      bytes(data.buffer.asUint8List());
    } else {
      byte(255);
      final data = ByteData(4)..setUint32(0, value, Endian.host);
      bytes(data.buffer.asUint8List());
    }
  }

  void int32(int value) {
    final data = ByteData(4)..setInt32(0, value, Endian.host);
    bytes(data.buffer.asUint8List());
  }

  void int64(int value) {
    final data = ByteData(8)..setInt64(0, value, Endian.host);
    bytes(data.buffer.asUint8List());
  }

  void float64(double value) {
    alignment(8);
    final data = ByteData(8)..setFloat64(0, value, Endian.host);
    bytes(data.buffer.asUint8List());
  }

  Uint8List finish() => Uint8List.fromList(_bytes);
}

final class _FgbReader {
  _FgbReader(this._bytes);

  final Uint8List _bytes;
  int _offset = 0;

  bool get hasRemaining => _offset < _bytes.length;
  int get remaining => _bytes.length - _offset;

  int byte() {
    if (_offset >= _bytes.length) throw const FormatException('unexpected end of message');
    return _bytes[_offset++];
  }

  Uint8List bytes(int length) {
    if (length < 0 || remaining < length) throw const FormatException('message is truncated');
    final result = Uint8List.sublistView(_bytes, _offset, _offset + length);
    _offset += length;
    return result;
  }

  void alignment(int size) {
    final padding = (size - _offset % size) % size;
    if (remaining < padding) throw const FormatException('message alignment is truncated');
    _offset += padding;
  }

  int size() {
    final marker = byte();
    if (marker < 254) return marker;
    if (marker == 254) {
      final data = ByteData.sublistView(bytes(2));
      return data.getUint16(0, Endian.host);
    }
    final data = ByteData.sublistView(bytes(4));
    return data.getUint32(0, Endian.host);
  }

  int int32() => ByteData.sublistView(bytes(4)).getInt32(0, Endian.host);

  int int64() => ByteData.sublistView(bytes(8)).getInt64(0, Endian.host);

  double float64() {
    alignment(8);
    return ByteData.sublistView(bytes(8)).getFloat64(0, Endian.host);
  }

  Object? value() {
    switch (byte()) {
      case 0:
        return null;
      case 1:
        return true;
      case 2:
        return false;
      case 3:
        return int32();
      case 4:
        return int64();
      case 5:
        // Flutter's base StandardMessageCodec exposes large integers received
        // from native code as their hexadecimal String representation.
        return utf8.decode(bytes(size()));
      case 6:
        return float64();
      case 7:
        return utf8.decode(bytes(size()));
      case 8:
        return bytes(size());
      case 9:
        final result = Int32List(size());
        alignment(4);
        for (var index = 0; index < result.length; index++) result[index] = int32();
        return result;
      case 10:
        final result = Int64List(size());
        alignment(8);
        for (var index = 0; index < result.length; index++) result[index] = int64();
        return result;
      case 11:
        final result = Float64List(size());
        alignment(8);
        for (var index = 0; index < result.length; index++) result[index] = float64();
        return result;
      case 12:
        final result = <Object?>[];
        for (var index = 0, length = size(); index < length; index++) result.add(value());
        return result;
      case 13:
        final result = <Object?, Object?>{};
        for (var index = 0, length = size(); index < length; index++) {
          result[value()] = value();
        }
        return result;
      case 14:
        final result = Float32List(size());
        alignment(4);
        for (var index = 0; index < result.length; index++) {
          final data = ByteData.sublistView(bytes(4));
          result[index] = data.getFloat32(0, Endian.host);
        }
        return result;
      default:
        throw const FormatException('unknown StandardMessageCodec type');
    }
  }
}

final class _FgbCodec {
  const _FgbCodec();

  Uint8List encodeMethodCall(String method, Object? arguments) {
    final writer = _FgbWriter();
    _writeValue(writer, method);
    _writeValue(writer, arguments);
    return writer.finish();
  }

  Object? decodeEnvelope(Uint8List bytes) {
    final reader = _FgbReader(bytes);
    final flag = reader.byte();
    if (flag == 0) {
      final result = reader.value();
      if (reader.hasRemaining) throw const FormatException('result envelope has trailing bytes');
      return result;
    }
    if (flag == 1) {
      final code = reader.value();
      final message = reader.value();
      final details = reader.value();
      if (reader.hasRemaining) throw const FormatException('error envelope has trailing bytes');
      if (code is! String) throw const FormatException('error code is not a String');
      if (message != null && message is! String) {
        throw const FormatException('error message is not a String or null');
      }
      return throw FgbPlatformException(code, message as String?, details);
    }
    throw const FormatException('unknown method envelope flag');
  }

  void _writeValue(_FgbWriter writer, Object? value) {
    if (value == null) {
      writer.byte(0);
    } else if (value is bool) {
      writer.byte(value ? 1 : 2);
    } else if (value is double) {
      writer.byte(6);
      writer.float64(value);
    } else if (value is int) {
      if (value >= -0x80000000 && value <= 0x7fffffff) {
        writer.byte(3);
        writer.int32(value);
      } else {
        writer.byte(4);
        writer.int64(value);
      }
    } else if (value is BigInt) {
      // The base Dart codec does not emit tag 5. Use the same hexadecimal
      // string convention understood by the generated Go decoder.
      writer.byte(7);
      final raw = utf8.encode(value.toRadixString(16));
      writer.size(raw.length);
      writer.bytes(raw);
    } else if (value is String) {
      writer.byte(7);
      final raw = utf8.encode(value);
      writer.size(raw.length);
      writer.bytes(raw);
    } else if (value is Uint8List) {
      writer.byte(8);
      writer.size(value.length);
      writer.bytes(value);
    } else if (value is Int32List) {
      writer.byte(9);
      writer.size(value.length);
      writer.alignment(4);
      for (final item in value) writer.int32(item);
    } else if (value is Int64List) {
      writer.byte(10);
      writer.size(value.length);
      writer.alignment(8);
      for (final item in value) writer.int64(item);
    } else if (value is Float64List) {
      writer.byte(11);
      writer.size(value.length);
      writer.alignment(8);
      for (final item in value) writer.float64(item);
    } else if (value is Float32List) {
      writer.byte(14);
      writer.size(value.length);
      writer.alignment(4);
      for (final item in value) {
        final data = ByteData(4)..setFloat32(0, item, Endian.host);
        writer.bytes(data.buffer.asUint8List());
      }
    } else if (value is List) {
      writer.byte(12);
      writer.size(value.length);
      for (final item in value) _writeValue(writer, item);
    } else if (value is Map) {
      writer.byte(13);
      writer.size(value.length);
      value.forEach((key, item) {
        _writeValue(writer, key);
        _writeValue(writer, item);
      });
    } else {
      throw FormatException('type ${value.runtimeType} is not supported by StandardMessageCodec');
    }
  }
}

final class _FgbData extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Int64()
  external int len;
}

typedef _FgbInitNative = ffi.Int32 Function(ffi.Pointer<ffi.Void>);
typedef _FgbInitDart = int Function(ffi.Pointer<ffi.Void>);
typedef _FgbAllocNative = ffi.Pointer<ffi.Void> Function(ffi.Int64);
typedef _FgbAllocDart = ffi.Pointer<ffi.Void> Function(int);
typedef _FgbFreeNative = ffi.Void Function(ffi.Pointer<ffi.Void>);
typedef _FgbFreeDart = void Function(ffi.Pointer<ffi.Void>);
typedef _FgbSyncNative = _FgbData Function(ffi.Pointer<ffi.Void>, ffi.Int64);
typedef _FgbSyncDart = _FgbData Function(ffi.Pointer<ffi.Void>, int);
typedef _FgbAsyncNative = ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int64, ffi.Int64);
typedef _FgbAsyncDart = void Function(ffi.Pointer<ffi.Void>, int, int);
typedef _FgbDropNative = ffi.Void Function(ffi.Pointer<ffi.Void>);
typedef _FgbDropDart = void Function(ffi.Pointer<ffi.Void>);
typedef _FgbCstNative = ffi.Pointer<ffi.Void> Function(ffi.Int32, ffi.Pointer<ffi.Void>);
typedef _FgbCstDart = ffi.Pointer<ffi.Void> Function(int, ffi.Pointer<ffi.Void>);
typedef _FgbCstAsyncNative = ffi.Void Function(ffi.Int32, ffi.Pointer<ffi.Void>, ffi.Int64);
typedef _FgbCstAsyncDart = void Function(int, ffi.Pointer<ffi.Void>, int);
typedef _FgbDcoFreeNative = ffi.Void Function(ffi.Pointer<ffi.Void>);
typedef _FgbDcoFreeDart = void Function(ffi.Pointer<ffi.Void>);

final class _FgbBindings {
  _FgbBindings(this.library)
    : init = library.lookupFunction<_FgbInitNative, _FgbInitDart>('fgb_init'),
      alloc = library.lookupFunction<_FgbAllocNative, _FgbAllocDart>('fgb_alloc'),
      free = library.lookupFunction<_FgbFreeNative, _FgbFreeDart>('fgb_free'),
      call = library.lookupFunction<_FgbSyncNative, _FgbSyncDart>('fgb'),
      callAsync = library.lookupFunction<_FgbAsyncNative, _FgbAsyncDart>('fgb_async'),
      drop = library.lookupFunction<_FgbDropNative, _FgbDropDart>('fgb_drop'),
      cst = library.lookupFunction<_FgbCstNative, _FgbCstDart>('fgb_cst'),
      cstAsync = library.lookupFunction<_FgbCstAsyncNative, _FgbCstAsyncDart>('fgb_cst_async'),
      dcoFree = library.lookupFunction<_FgbDcoFreeNative, _FgbDcoFreeDart>('fgb_dco_free'),
      dropAddress = library.lookup<ffi.NativeFunction<_FgbDropNative>>('fgb_drop');

  final ffi.DynamicLibrary library;
  final int Function(ffi.Pointer<ffi.Void>) init;
  final ffi.Pointer<ffi.Void> Function(int) alloc;
  final void Function(ffi.Pointer<ffi.Void>) free;
  final _FgbData Function(ffi.Pointer<ffi.Void>, int) call;
  final void Function(ffi.Pointer<ffi.Void>, int, int) callAsync;
  final void Function(ffi.Pointer<ffi.Void>) drop;
  final ffi.Pointer<ffi.Void> Function(int, ffi.Pointer<ffi.Void>) cst;
  final void Function(int, ffi.Pointer<ffi.Void>, int) cstAsync;
  final void Function(ffi.Pointer<ffi.Void>) dcoFree;
  final ffi.Pointer<ffi.NativeFunction<_FgbDropNative>> dropAddress;
}

final class _FgbDcoTypedData extends ffi.Struct {
  @ffi.Uint32()
  external int type;

  @ffi.IntPtr()
  external int length;

  external ffi.Pointer<ffi.Uint8> values;
}

final class _FgbDcoArray extends ffi.Struct {
  @ffi.IntPtr()
  external int length;

  external ffi.Pointer<ffi.Pointer<_FgbDcoObject>> values;
}

typedef _FgbDcoFinalizerNative = ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>);

final class _FgbDcoExternalTypedData extends ffi.Struct {
  @ffi.Uint32()
  external int type;

  @ffi.IntPtr()
  external int length;

  external ffi.Pointer<ffi.Uint8> data;
  external ffi.Pointer<ffi.Void> peer;
  external ffi.Pointer<ffi.NativeFunction<_FgbDcoFinalizerNative>> callback;
}

final class _FgbDcoNativePointer extends ffi.Struct {
  @ffi.IntPtr()
  external int ptr;

  @ffi.IntPtr()
  external int size;

  external ffi.Pointer<ffi.NativeFunction<_FgbDcoFinalizerNative>> callback;
}

final class _FgbDcoValue extends ffi.Union {
  @ffi.Bool()
  external bool asBool;

  @ffi.Int32()
  external int asInt32;

  @ffi.Int64()
  external int asInt64;

  @ffi.Double()
  external double asDouble;

  external ffi.Pointer<ffi.Char> asString;

  external _FgbDcoArray asArray;

  external _FgbDcoTypedData asTypedData;

  external _FgbDcoExternalTypedData asExternalTypedData;

  external _FgbDcoNativePointer asNativePointer;
}

final class _FgbDcoObject extends ffi.Struct {
  @ffi.Uint32()
  external int type;

  external _FgbDcoValue value;
}

final class _FgbArena {
  _FgbArena(this.bridge);

  final FlutterGoBridge bridge;
  final List<ffi.Pointer<ffi.Void>> _allocations = <ffi.Pointer<ffi.Void>>[];

  ffi.Pointer<T> allocate<T extends ffi.NativeType>(int bytes) {
    final pointer = bridge._bindings.alloc(bytes);
    if (pointer == ffi.nullptr) throw StateError('fgb_alloc returned null');
    if (bytes > 0) pointer.cast<ffi.Uint8>().asTypedList(bytes).fillRange(0, bytes, 0);
    _allocations.add(pointer);
    return pointer.cast<T>();
  }

  ffi.Pointer<ffi.Uint8> bytes(List<int> value) {
    final pointer = allocate<ffi.Uint8>(value.isEmpty ? 1 : value.length);
    if (value.isNotEmpty) pointer.asTypedList(value.length).setAll(0, value);
    return pointer;
  }

  void close() {
    for (final pointer in _allocations.reversed) {
      bridge._bindings.free(pointer);
    }
    _allocations.clear();
  }
}

final class FlutterGoBridge {
  FlutterGoBridge._(this._bindings, this._libraryPath)
    : _handleFinalizer = ffi.NativeFinalizer(_bindings.dropAddress) {
    final status = _bindings.init(ffi.NativeApi.initializeApiDLData);
    if (status != 0) throw StateError('Dart API DL initialization failed (status $status)');
  }

  static FlutterGoBridge? _instance;

  static FlutterGoBridge get instance => _instance ??= FlutterGoBridge._open();

  static FlutterGoBridge open({String? libraryPath}) {
    final existing = _instance;
    if (existing != null) {
      if (libraryPath != null && existing._libraryPath != libraryPath) {
        throw StateError('FlutterGoBridge is already initialized with another library');
      }
      return existing;
    }
    return _instance = FlutterGoBridge._open(libraryPath: libraryPath);
  }

  static void initialize({String? libraryPath}) => open(libraryPath: libraryPath);

  static FlutterGoBridge _open({String? libraryPath}) {
    final library = libraryPath == null
        ? _openDefaultLibrary()
        : ffi.DynamicLibrary.open(libraryPath);
    return FlutterGoBridge._(_FgbBindings(library), libraryPath);
  }

  static ffi.DynamicLibrary _openDefaultLibrary() {
    if (Platform.isMacOS || Platform.isIOS) return ffi.DynamicLibrary.process();
    const libraryName = "go_lib_myapp";
    if (Platform.isWindows) return ffi.DynamicLibrary.open('$libraryName.dll');
    return ffi.DynamicLibrary.open('lib$libraryName.so');
  }

  final _FgbBindings _bindings;
  final String? _libraryPath;
  final ffi.NativeFinalizer _handleFinalizer;
  static const _FgbCodec _codec = _FgbCodec();

  /// Internal entrypoint used by generated per-source Dart API files.
  Object? fgbInvokeSync(String method, List<Object?> arguments) {
    final request = _codec.encodeMethodCall(method, arguments);
    return _codec.decodeEnvelope(_syncBytes(request));
  }

  /// Internal entrypoint used by generated per-source Dart API files.
  Future<Object?> fgbInvokeAsync(String method, List<Object?> arguments) async {
    final request = _codec.encodeMethodCall(method, arguments);
    return _codec.decodeEnvelope(await _asyncBytes(request));
  }

  Object? fgbInvokeCstSync(int method, ffi.Pointer<ffi.Void> args) {
    final pointer = _bindings.cst(method, args);
    if (pointer == ffi.nullptr) throw StateError('fgb_cst returned null');
    try {
      return _decodeDcoEnvelope(_decodeDco(pointer.cast<_FgbDcoObject>().ref));
    } finally {
      _bindings.dcoFree(pointer);
    }
  }

  Future<Object?> fgbInvokeCstAsync(int method, ffi.Pointer<ffi.Void> args) async {
    final port = ReceivePort();
    try {
      _bindings.cstAsync(method, args, port.sendPort.nativePort);
      return _decodeDcoEnvelope(await port.first);
    } finally {
      port.close();
    }
  }

  Object? _decodeDco(_FgbDcoObject object) {
    switch (object.type) {
      case 0:
        return null;
      case 1:
        return object.value.asBool;
      case 2:
        return object.value.asInt32;
      case 3:
        return object.value.asInt64;
      case 4:
        return object.value.asDouble;
      case 5:
        final pointer = object.value.asString.cast<ffi.Uint8>();
        var length = 0;
        while ((pointer + length).value != 0) length++;
        return utf8.decode(pointer.asTypedList(length));
      case 6:
        final array = object.value.asArray;
        return List<Object?>.generate(
          array.length,
          (index) => _decodeDco((array.values + index).value.ref),
          growable: false,
        );
      case 7:
        final typed = object.value.asTypedData;
        final length = typed.length;
        switch (typed.type) {
          case 2:
            return Uint8List.fromList(typed.values.asTypedList(length));
          case 6:
            return Int32List.fromList(typed.values.cast<ffi.Int32>().asTypedList(length));
          case 8:
            return Int64List.fromList(typed.values.cast<ffi.Int64>().asTypedList(length));
          case 11:
            return Float64List.fromList(typed.values.cast<ffi.Double>().asTypedList(length));
          default:
            throw FormatException('unsupported Dart_CObject typed data ${typed.type}');
        }
      default:
        throw FormatException('unsupported Dart_CObject type ${object.type}');
    }
  }

  Object? _decodeDcoEnvelope(Object? raw) {
    if (raw is! List || raw.length < 2 || raw.first is! int) {
      throw const FormatException('invalid DCO envelope');
    }
    if (raw.first == 0) return raw[1];
    if (raw.first == 1 && raw.length >= 4) {
      throw FgbPlatformException(raw[1] as String, raw[2] as String?, raw[3]);
    }
    throw const FormatException('unknown DCO envelope flag');
  }

  /// Attaches framework-owned cleanup for an opaque Go handle.
  void fgbAttachOpaqueFinalizer(ffi.Finalizable object, int handle) {
    _handleFinalizer.attach(object, ffi.Pointer<ffi.Void>.fromAddress(handle), detach: object);
  }

  Uint8List _syncBytes(Uint8List request) {
    final pointer = _bindings.alloc(request.length);
    if (pointer == ffi.nullptr) throw StateError('fgb_alloc returned null');
    try {
      pointer.cast<ffi.Uint8>().asTypedList(request.length).setAll(0, request);
      final result = _bindings.call(pointer, request.length);
      if (result.data == ffi.nullptr && result.len != 0) {
        throw StateError('fgb returned an invalid buffer');
      }
      try {
        if (result.len == 0) return Uint8List(0);
        return Uint8List.fromList(result.data.asTypedList(result.len));
      } finally {
        if (result.data != ffi.nullptr) _bindings.free(result.data.cast());
      }
    } finally {
      _bindings.free(pointer);
    }
  }

  Future<Uint8List> _asyncBytes(Uint8List request) async {
    final port = ReceivePort();
    final pointer = _bindings.alloc(request.length);
    if (pointer == ffi.nullptr) {
      port.close();
      throw StateError('fgb_alloc returned null');
    }
    try {
      try {
        pointer.cast<ffi.Uint8>().asTypedList(request.length).setAll(0, request);
        _bindings.callAsync(pointer, request.length, port.sendPort.nativePort);
      } finally {
        _bindings.free(pointer);
      }
      final message = await port.first;
      if (message is Uint8List) return message;
      if (message is List<int>) return Uint8List.fromList(message);
      throw StateError('fgb_async returned an invalid message');
    } finally {
      port.close();
    }
  }
}

String fgbDecode0(Object? value, FlutterGoBridge bridge, String path) {
  if (value is! String) throw FormatException('$path: expected String');
  return value;
}

Object? fgbEncode0(String value, FlutterGoBridge bridge, String path) {
  return value;
}

Point? fgbDecode1(Object? value, FlutterGoBridge bridge, String path) {
  if (value == null) return null;
  if (value is! int || value <= 0) throw FormatException('$path: expected opaque handle');
  return Point.fgbInternal(bridge, value);
}

Object? fgbEncode1(Point? value, FlutterGoBridge bridge, String path) {
  if (value == null) return null;
  if (!identical(value.fgbBridge, bridge))
    throw StateError('opaque value belongs to a different bridge');
  return value.fgbHandle;
}

int fgbDecode2(Object? value, FlutterGoBridge bridge, String path) {
  if (value is! int) throw FormatException('$path: expected int');
  return value;
}

Object? fgbEncode2(int value, FlutterGoBridge bridge, String path) {
  return value;
}

ffi.Pointer<_FgbCstBytes> fgbCstEncode0(String value, _FgbArena arena, String path) {
  final raw = utf8.encode(value);
  final result = arena.allocate<_FgbCstBytes>(ffi.sizeOf<_FgbCstBytes>());
  result.ref.ptr = arena.bytes(raw);
  result.ref.len = raw.length;
  return result;
}

int fgbCstEncode1(Point? value, _FgbArena arena, String path) {
  if (value == null) return 0;
  if (!identical(value.fgbBridge, arena.bridge))
    throw StateError('opaque value belongs to a different bridge');
  return value.fgbHandle;
}

int fgbCstEncode2(int value, _FgbArena arena, String path) {
  return value;
}

extension FgbGeneratedCalls on FlutterGoBridge {
  String fgbInternalCall0(String name) {
    final arena = _FgbArena(this);
    try {
      final args = arena.allocate<_FgbCstArgs0>(ffi.sizeOf<_FgbCstArgs0>());
      args.ref.name = fgbCstEncode0(name, arena, "name");
      final wireResult = fgbInvokeCstSync(0, args.cast<ffi.Void>());
      return fgbDecode0(wireResult, this, 'result');
    } finally {
      arena.close();
    }
  }

  void fgbInternalCall1(Point receiver, int x, int y) {
    final arena = _FgbArena(this);
    try {
      final args = arena.allocate<_FgbCstArgs1>(ffi.sizeOf<_FgbCstArgs1>());
      args.ref.receiver = fgbCstEncode1(receiver, arena, 'receiver');
      args.ref.x = fgbCstEncode2(x, arena, "x");
      args.ref.y = fgbCstEncode2(y, arena, "y");
      fgbInvokeCstSync(1, args.cast<ffi.Void>());
      return;
    } finally {
      arena.close();
    }
  }
}
