// Code generated by flutter_go_bridge_codegen. DO NOT EDIT.
// ignore_for_file: unused_element, unused_import, unnecessary_import
import "bridge_generated.dart";
import 'dart:typed_data';
export "bridge_generated.dart" show FlutterGoBridge, FgbPlatformException;

final class Point extends FgbOpaque {
  Point.fgbInternal(FlutterGoBridge bridge, int handle) : super(bridge, handle);

  void move(int x, int y) {
    fgbBridge.fgbInternalCall1(this, x, y);
  }
}

String greeting(String name) {
  final bridge = FlutterGoBridge.instance;
  return bridge.fgbInternalCall0(name);
}
