package parser

import (
	"go/ast"
	goparser "go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/star4277/flutter_go_bridge/internal/model"
	"golang.org/x/tools/go/packages"
)

func commentGroup(text string) *ast.CommentGroup {
	return &ast.CommentGroup{List: []*ast.Comment{{Text: text}}}
}

func TestDirectiveStringValueQuoted(t *testing.T) {
	if got := directiveStringValue(`"abc"`); got != "abc" {
		t.Fatalf("unquote: got %q", got)
	}
	if got := directiveStringValue(`plain`); got != "plain" {
		t.Fatalf("noquote: got %q", got)
	}
}

func TestConstSpecNameUnnamed(t *testing.T) {
	if got := constSpecName(&ast.ValueSpec{}); got != "<unnamed>" {
		t.Fatalf("got %q", got)
	}
}

func TestPackageDirFallback(t *testing.T) {
	if got := packageDir(&packages.Package{}, "fallback"); got != "fallback" {
		t.Fatalf("got %q", got)
	}
	if got := packageDir(&packages.Package{GoFiles: []string{"", ""}}, "fb"); got != "fb" {
		t.Fatalf("got %q", got)
	}
}

func TestShouldSkipGeneratedFileBranches(t *testing.T) {
	dir := t.TempDir()
	realFile := filepath.Join(dir, "real.go")
	if err := os.WriteFile(realFile, []byte("package p\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	missing := filepath.Join(dir, "missing.go")
	bad := filepath.Join(dir, "bad.go")
	gen := filepath.Join(dir, "gen.go")
	// Package GoFiles include missing/bad/gen so the read/parse error branches run.
	pkg := &packages.Package{GoFiles: []string{realFile, missing, bad, gen}}
	if !shouldSkipGeneratedFile(pkg, "") {
		t.Fatal("empty file should be skipped")
	}
	if shouldSkipGeneratedFile(pkg, filepath.Clean(realFile)) {
		t.Fatal("normal file should not be skipped")
	}
	if !shouldSkipGeneratedFile(pkg, filepath.Join(dir, "other.go")) {
		t.Fatal("non-package file should be skipped")
	}
	if !shouldSkipGeneratedFile(pkg, missing) {
		t.Fatal("missing (unreadable) file should be skipped")
	}
	if err := os.WriteFile(bad, []byte("this is {{{ not go at all &&&"), 0o644); err != nil {
		t.Fatal(err)
	}
	if !shouldSkipGeneratedFile(pkg, bad) {
		t.Fatal("invalid source should be skipped")
	}
	if err := os.WriteFile(gen, []byte("// Code generated by x. DO NOT EDIT.\n\npackage p\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if !shouldSkipGeneratedFile(pkg, gen) {
		t.Fatal("generated file should be skipped")
	}
}

func TestSameFilePath(t *testing.T) {
	dir := t.TempDir()
	f := filepath.Join(dir, "Foo.go")
	if !sameFilePath(f, filepath.Clean(f)) {
		t.Fatalf("same path should be equal")
	}
	if sameFilePath(f, filepath.Join(dir, "Bar.go")) {
		t.Fatalf("different paths should not be equal")
	}
}

func TestParseDirectivesExtraBranches(t *testing.T) {
	if ds, err := parseDirectives(commentGroup("//fgb:opaque")); err != nil || !ds.Opaque {
		t.Fatalf("opaque: %#v %v", ds, err)
	}
	if ds, err := parseDirectives(commentGroup("//fgb:enum")); err != nil || !ds.Enum {
		t.Fatalf("enum: %#v %v", ds, err)
	}
	if ds, err := parseDirectives(commentGroup("//fgb:ignore")); err != nil || !ds.Ignore {
		t.Fatalf("ignore: %#v %v", ds, err)
	}
	if ds, err := parseDirectives(commentGroup("//fgb:sync")); err != nil || !ds.HasMode || ds.Mode != model.CallModeSync {
		t.Fatalf("sync: %#v %v", ds, err)
	}
	if ds, err := parseDirectives(commentGroup("//fgb:rename = \"foo\"")); err != nil || ds.Rename != "foo" {
		t.Fatalf("rename: %#v %v", ds, err)
	}
	if ds, err := parseDirectives(commentGroup("//fgb:nullable = \"a,b\"")); err != nil || len(ds.Nullable) != 2 {
		t.Fatalf("nullable: %#v %v", ds, err)
	}
	if _, err := parseDirectives(commentGroup("//fgb:rename = \"\"")); err == nil {
		t.Fatal("empty rename should fail")
	}
	if _, err := parseDirectives(commentGroup("//fgb:nullable = \"a,\"")); err == nil {
		t.Fatal("empty nullable parameter should fail")
	}
	if _, err := parseDirectives(commentGroup("// fgb:async")); err == nil {
		t.Fatal("malformed spaced directive should fail")
	}
	if _, err := parseDirectives(commentGroup("//fgb:")); err == nil {
		t.Fatal("empty directive should fail")
	}
	if _, err := parseDirectives(commentGroup("//fgb:sync, async")); err == nil {
		t.Fatal("conflicting modes should fail")
	}
	if _, err := parseDirectives(commentGroup("//fgb:bogus")); err == nil {
		t.Fatal("unknown directive should fail")
	}
	if ds, err := parseDirectives(nil); err != nil || ds.Mode != model.CallModeSync {
		t.Fatalf("nil group: %#v %v", ds, err)
	}
	if ds, err := parseDirectives(commentGroup("// just prose")); err != nil || ds.HasMode {
		t.Fatalf("prose should be ignored: %#v %v", ds, err)
	}
}

func TestMergeSpecDirectivesBranches(t *testing.T) {
	if _, err := mergeSpecDirectives(commentGroup("//fgb:async"), nil); err == nil {
		t.Fatal("mode on spec should error for type decl")
	}
	if _, err := mergeSpecDirectives(nil, commentGroup("//fgb:nullable = \"a\"")); err == nil {
		t.Fatal("nullable on decl should error for type decl")
	}
	ds, err := mergeSpecDirectives(commentGroup("//fgb:rename = \"B\""), commentGroup("//fgb:ignore"))
	if err != nil {
		t.Fatal(err)
	}
	if ds.Rename != "B" || !ds.Ignore {
		t.Fatalf("merge result: %#v", ds)
	}
	ds2, err := mergeSpecDirectives(nil, commentGroup("//fgb:rename = \"C\""))
	if err != nil {
		t.Fatal(err)
	}
	if ds2.Rename != "C" {
		t.Fatalf("decl rename fallback: %#v", ds2)
	}
	if ds, err := mergeSpecDirectives(commentGroup("//fgb:enum"), commentGroup("//fgb:opaque")); err == nil || !strings.Contains(err.Error(), "enum") {
		t.Fatalf("enum and opaque should conflict, got %#v %v", ds, err)
	}
}

func TestDumpAST(t *testing.T) {
	api := &model.API{
		Package: &packages.Package{Fset: token.NewFileSet(), Syntax: []*ast.File{}},
	}
	if out := DumpAST(api); out != "" {
		t.Fatalf("expected empty, got %q", out)
	}
	fileset := token.NewFileSet()
	parsed, err := goparser.ParseFile(fileset, "x.go", "package x\n\nfunc F() int { return 1 }\n", 0)
	if err != nil {
		t.Fatal(err)
	}
	api2 := &model.API{Package: &packages.Package{Fset: fileset, Syntax: []*ast.File{parsed}}}
	if out := DumpAST(api2); out == "" {
		t.Fatal("expected non-empty dump")
	}
	genSet := token.NewFileSet()
	gen, err := goparser.ParseFile(genSet, "gen.go", "// Code generated by x. DO NOT EDIT.\n\npackage x\n", goparser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	api3 := &model.API{Package: &packages.Package{Fset: genSet, Syntax: []*ast.File{gen}}}
	if out := DumpAST(api3); out != "" {
		t.Fatalf("generated file should be skipped, got %q", out)
	}
}
