package parser

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	goparser "go/parser"
	"go/token"
	"go/types"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strconv"
	"strings"

	"github.com/star4277/flutter_go_bridge/internal/model"
	"github.com/star4277/flutter_go_bridge/internal/names"
	"golang.org/x/tools/go/packages"
)

type Options struct {
	Input    string
	BaseDir  string
	PrintAST bool
	ASTOut   io.Writer
}

func Parse(options Options) (*model.API, error) {
	if options.Input == "" {
		return nil, errors.New("empty Go input")
	}
	if options.BaseDir == "" {
		options.BaseDir = "."
	}
	if options.ASTOut == nil {
		options.ASTOut = io.Discard
	}

	dir, pattern, err := loadTarget(options.BaseDir, options.Input)
	if err != nil {
		return nil, err
	}
	cfg := &packages.Config{
		Dir: dir,
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedCompiledGoFiles |
			packages.NeedImports |
			packages.NeedDeps |
			packages.NeedModule |
			packages.NeedSyntax |
			packages.NeedTypes |
			packages.NeedTypesInfo |
			packages.NeedTypesSizes,
		Tests: false,
	}
	loaded, err := packages.Load(cfg, pattern)
	if err != nil {
		return nil, err
	}
	if packages.PrintErrors(loaded) > 0 {
		return nil, packageErrors(loaded)
	}
	if len(loaded) != 1 {
		return nil, fmt.Errorf("go_input must resolve to exactly one package, got %d", len(loaded))
	}
	pkg := loaded[0]
	if pkg.Types == nil || pkg.TypesInfo == nil {
		return nil, errors.New("Go package loader did not provide type information")
	}
	if element := internalPathElement(pkg.PkgPath); element != "" {
		return nil, fmt.Errorf("go_input resolves to %s, which is inside an %q package; internal packages are excluded from generation", pkg.PkgPath, element)
	}

	api := &model.API{
		Package:      pkg,
		InputDir:     packageDir(pkg, dir),
		Types:        map[*types.TypeName]*model.TypeDecl{},
		Constants:    map[*types.Named][]*model.Constant{},
		IgnoredTypes: map[string]bool{},
		OpaqueTypes:  map[string]bool{},
	}

	seenSourceFiles := map[string]bool{}
	for index, file := range pkg.Syntax {
		// Syntax files are not required to have the same ordering as
		// CompiledGoFiles (notably when cgo or generated files are present).
		// Resolve the filename from the official FileSet position instead of
		// relying on an index coincidence; this is what keeps Dart source
		// files mapped to the correct Go file.
		sourceFile := ""
		if position := pkg.Fset.Position(file.Pos()); position.Filename != "" {
			sourceFile = position.Filename
		} else if index < len(pkg.CompiledGoFiles) {
			// A defensive fallback for unusual loaders that omit position names.
			sourceFile = pkg.CompiledGoFiles[index]
		}
		if sourceFile != "" {
			if !filepath.IsAbs(sourceFile) {
				sourceFile = filepath.Join(dir, sourceFile)
			}
			sourceFile = filepath.Clean(sourceFile)
		}
		// packages.Load can include compiler/cache-only syntax files that are
		// not part of the original package sources. They must not become Dart
		// files (or affect source mirroring).
		if !isPackageGoFile(pkg, sourceFile) {
			continue
		}
		// cmd/cgo annotates the original Go source AST with its own
		// "Code generated by cmd/cgo" comment.  Treating that AST as a
		// generated file would silently discard the user's API whenever an
		// input file imports "C".  Only skip generated ASTs that do not map
		// back to one of the package's original Go files, or whose on-disk
		// source is itself genuinely marked as generated.
		if ast.IsGenerated(file) && shouldSkipGeneratedFile(pkg, sourceFile) {
			continue
		}
		if sourceFile != "" && !seenSourceFiles[sourceFile] {
			seenSourceFiles[sourceFile] = true
			api.SourceFiles = append(api.SourceFiles, sourceFile)
		}
		if options.PrintAST {
			_ = ast.Fprint(options.ASTOut, pkg.Fset, file, nil)
		}
		if err := collectFile(api, file, sourceFile); err != nil {
			return nil, err
		}
	}

	// A type marked fgb(ignore) drags its methods with it, wherever they were
	// declared.
	kept := api.Callables[:0]
	for _, callable := range api.Callables {
		if callable.Receiver != nil && api.IgnoredTypes[callable.Receiver.Obj().Name()] {
			continue
		}
		kept = append(kept, callable)
	}
	api.Callables = kept

	sort.SliceStable(api.Callables, func(i, j int) bool {
		return api.Callables[i].Position < api.Callables[j].Position
	})
	for _, constants := range api.Constants {
		sort.SliceStable(constants, func(i, j int) bool {
			return constants[i].Position < constants[j].Position
		})
	}
	sort.Strings(api.SourceFiles)
	return api, nil
}

func collectFile(api *model.API, file *ast.File, sourceFile string) error {
	for _, declaration := range file.Decls {
		switch declaration := declaration.(type) {
		case *ast.FuncDecl:
			object, _ := api.Package.TypesInfo.Defs[declaration.Name].(*types.Func)
			if object == nil || !object.Exported() {
				continue
			}
			signature, _ := object.Type().(*types.Signature)
			if signature == nil {
				continue
			}
			directives, err := parseDirectives(declaration.Doc)
			if err != nil {
				return fmt.Errorf("%s: %w", object.FullName(), err)
			}
			if directives.Ignore {
				continue
			}
			callable := &model.Callable{
				Func:           object,
				Signature:      signature,
				Position:       declaration.Pos(),
				SourceFile:     sourceFile,
				Docs:           cleanDocs(declaration.Doc),
				DartName:       directives.Rename,
				Mode:           directives.Mode,
				NullableParams: directives.Nullable,
			}
			if callable.DartName == "" {
				callable.DartName = names.LowerCamel(object.Name())
			}
			if recv := signature.Recv(); recv != nil {
				receiverType := recv.Type()
				if pointer, ok := receiverType.(*types.Pointer); ok {
					callable.PointerRecv = true
					receiverType = pointer.Elem()
				}
				callable.Receiver, _ = types.Unalias(receiverType).(*types.Named)
				if callable.Receiver == nil || callable.Receiver.Obj() == nil || !callable.Receiver.Obj().Exported() {
					continue
				}
			}
			api.Callables = append(api.Callables, callable)

		case *ast.GenDecl:
			switch declaration.Tok {
			case token.TYPE:
				for _, spec := range declaration.Specs {
					typeSpec, _ := spec.(*ast.TypeSpec)
					if typeSpec == nil || !typeSpec.Name.IsExported() {
						continue
					}
					object, _ := api.Package.TypesInfo.Defs[typeSpec.Name].(*types.TypeName)
					if object == nil {
						continue
					}
					directives, err := mergeSpecDirectives(typeSpec.Doc, declaration.Doc)
					if err != nil {
						return fmt.Errorf("type %s: %w", object.Name(), err)
					}
					if directives.Ignore {
						api.IgnoredTypes[object.Name()] = true
						continue
					}
					if directives.Opaque {
						api.OpaqueTypes[object.Name()] = true
					}
					named, _ := object.Type().(*types.Named)
					if named == nil {
						continue
					}
					docs := typeSpec.Doc
					if docs == nil {
						docs = declaration.Doc
					}
					dartName := directives.Rename
					if dartName == "" {
						dartName = names.UpperCamel(object.Name())
					}
					api.Types[object] = &model.TypeDecl{
						Object: object, Named: named, Position: typeSpec.Pos(), SourceFile: sourceFile, AST: typeSpec,
						Docs: cleanDocs(docs), DartName: dartName,
						Methods: interfaceMethods(typeSpec),
					}
				}
			case token.CONST:
				for _, spec := range declaration.Specs {
					valueSpec, _ := spec.(*ast.ValueSpec)
					if valueSpec == nil {
						continue
					}
					directives, err := mergeSpecDirectives(valueSpec.Doc, declaration.Doc)
					if err != nil {
						return fmt.Errorf("const %s: %w", constSpecName(valueSpec), err)
					}
					if directives.Ignore {
						continue
					}
					for _, identifier := range valueSpec.Names {
						object, _ := api.Package.TypesInfo.Defs[identifier].(*types.Const)
						if object == nil || !object.Exported() {
							continue
						}
						named, _ := types.Unalias(object.Type()).(*types.Named)
						if named == nil {
							continue
						}
						docs := valueSpec.Doc
						if docs == nil {
							docs = declaration.Doc
						}
						dartName := directives.Rename
						if dartName == "" {
							dartName = names.LowerCamel(identifier.Name)
						}
						api.Constants[named] = append(api.Constants[named], &model.Constant{
							Object: object, Position: identifier.Pos(), Docs: cleanDocs(docs), DartName: dartName,
						})
					}
				}
			}
		}
	}
	return nil
}

// interfaceMethods collects the //fgb: directives written on the methods of
// an interface declaration. Interface methods have no bodies, so their doc
// comments are the only place a directive can live.
func interfaceMethods(spec *ast.TypeSpec) map[string]*model.InterfaceMethod {
	declared, ok := spec.Type.(*ast.InterfaceType)
	if !ok || declared.Methods == nil {
		return nil
	}
	result := map[string]*model.InterfaceMethod{}
	for _, field := range declared.Methods.List {
		if len(field.Names) == 0 {
			// An embedded interface; its own declaration carries the
			// directives of the methods it contributes.
			continue
		}
		directives, err := parseDirectives(field.Doc)
		if err != nil {
			// Reported by the type-level parse; keep the default shape here.
			directives = directiveSet{Mode: model.CallModeSync}
		}
		for _, name := range field.Names {
			method := &model.InterfaceMethod{
				GoName: name.Name, DartName: directives.Rename,
				Mode: directives.Mode, Docs: cleanDocs(field.Doc), Ignore: directives.Ignore,
			}
			if method.DartName == "" {
				method.DartName = names.LowerCamel(name.Name)
			}
			result[name.Name] = method
		}
	}
	return result
}

func constSpecName(spec *ast.ValueSpec) string {
	if len(spec.Names) != 0 {
		return spec.Names[0].Name
	}
	return "<unnamed>"
}

func loadTarget(baseDir, input string) (dir, pattern string, err error) {
	absBase, err := filepath.Abs(baseDir)
	if err != nil {
		return "", "", err
	}
	candidate := input
	if !filepath.IsAbs(candidate) {
		candidate = filepath.Join(absBase, candidate)
	}
	info, statErr := os.Stat(candidate)
	if statErr == nil {
		if info.IsDir() {
			return candidate, ".", nil
		}
		if filepath.Ext(candidate) != ".go" {
			return "", "", fmt.Errorf("go_input file must end in .go: %s", candidate)
		}
		return filepath.Dir(candidate), "file=" + candidate, nil
	}
	if !errors.Is(statErr, os.ErrNotExist) {
		return "", "", statErr
	}
	return absBase, input, nil
}

// internalPathElement reports the `internal` element of an import path, if
// any. Go already restricts who may import such a package, so bridging one to
// Dart would export something the module deliberately keeps private - and it
// is where the generated support package lives.
func internalPathElement(importPath string) string {
	for element := range strings.SplitSeq(importPath, "/") {
		if element == "internal" {
			return element
		}
	}
	return ""
}

func packageDir(pkg *packages.Package, fallback string) string {
	// CompiledGoFiles may point into the Go build cache (especially for cgo
	// packages).  GoFiles are the original user sources and therefore provide
	// the stable directory used for Dart source mirroring.
	for _, file := range pkg.GoFiles {
		if file == "" {
			continue
		}
		if absolute, err := filepath.Abs(file); err == nil {
			return filepath.Dir(absolute)
		}
		return filepath.Dir(filepath.Clean(file))
	}
	return fallback
}

func shouldSkipGeneratedFile(pkg *packages.Package, sourceFile string) bool {
	if sourceFile == "" || !isPackageGoFile(pkg, sourceFile) {
		return true
	}
	raw, err := os.ReadFile(sourceFile)
	if err != nil {
		return true
	}
	original, err := goparser.ParseFile(token.NewFileSet(), sourceFile, raw, goparser.ParseComments)
	if err != nil {
		return true
	}
	return ast.IsGenerated(original)
}

func isPackageGoFile(pkg *packages.Package, sourceFile string) bool {
	for _, file := range pkg.GoFiles {
		if sameFilePath(file, sourceFile) {
			return true
		}
	}
	return false
}

func sameFilePath(left, right string) bool {
	leftAbs, leftErr := filepath.Abs(left)
	rightAbs, rightErr := filepath.Abs(right)
	if leftErr != nil || rightErr != nil {
		return filepath.Clean(left) == filepath.Clean(right)
	}
	leftClean, rightClean := filepath.Clean(leftAbs), filepath.Clean(rightAbs)
	if runtime.GOOS == "windows" || runtime.GOOS == "darwin" {
		return strings.EqualFold(leftClean, rightClean)
	}
	return leftClean == rightClean
}

func packageErrors(pkgs []*packages.Package) error {
	var lines []string
	for _, pkg := range pkgs {
		for _, item := range pkg.Errors {
			lines = append(lines, item.Error())
		}
	}
	return errors.New(strings.Join(lines, "\n"))
}

var renameDirectivePattern = regexp.MustCompile(`^rename\s*=\s*(.+)$`)

var nullableDirectivePattern = regexp.MustCompile(`^nullable\s*=\s*(.+)$`)

// directiveSet is everything an `//fgb:` directive can request for one
// declaration.
type directiveSet struct {
	Mode     model.CallMode
	HasMode  bool
	Ignore   bool
	Opaque   bool
	Rename   string
	Nullable []string
}

// splitDirectiveTokens splits a directive body on commas, ignoring commas
// inside quotes so `nullable = "a,b"` stays one token.
func splitDirectiveTokens(body string) []string {
	var tokens []string
	var current strings.Builder
	quote := rune(0)
	for _, character := range body {
		switch {
		case quote != 0:
			if character == quote {
				quote = 0
			}
			current.WriteRune(character)
		case character == '"' || character == '\'':
			quote = character
			current.WriteRune(character)
		case character == ',':
			tokens = append(tokens, strings.TrimSpace(current.String()))
			current.Reset()
		default:
			current.WriteRune(character)
		}
	}
	if trailing := strings.TrimSpace(current.String()); trailing != "" || len(tokens) == 0 {
		tokens = append(tokens, trailing)
	}
	return tokens
}

// directiveStringValue unquotes a directive value when it is quoted.
func directiveStringValue(raw string) string {
	value := strings.TrimSpace(raw)
	if unquoted, err := strconv.Unquote(value); err == nil {
		return unquoted
	}
	return value
}

// parseDirectives understands `//fgb:sync`, `//fgb:async`, `//fgb:ignore`,
// `//fgb:opaque`, `//fgb:rename = "name"`, and
// `//fgb:nullable = "param1,param2"` - either as separate lines or
// comma-combined like `//fgb:async, rename = "name"`. The spelling follows
// the Go directive convention (`//tool:directive`, no space after `//`), so
// gofmt leaves the line alone and it never leaks into doc comments. Unmarked
// declarations are sync.
func parseDirectives(group *ast.CommentGroup) (directiveSet, error) {
	result := directiveSet{Mode: model.CallModeSync}
	modeSeen := false
	applyMode := func(value model.CallMode) error {
		if modeSeen && value != result.Mode {
			return fmt.Errorf("conflicting fgb call mode directives")
		}
		result.Mode, result.HasMode, modeSeen = value, true, true
		return nil
	}
	applyToken := func(token string) error {
		switch token {
		case "sync":
			return applyMode(model.CallModeSync)
		case "async":
			return applyMode(model.CallModeAsync)
		case "ignore":
			result.Ignore = true
			return nil
		case "opaque":
			result.Opaque = true
			return nil
		}
		if match := renameDirectivePattern.FindStringSubmatch(token); match != nil {
			value := directiveStringValue(match[1])
			if value == "" {
				return fmt.Errorf("invalid empty fgb rename")
			}
			result.Rename = value
			return nil
		}
		if match := nullableDirectivePattern.FindStringSubmatch(token); match != nil {
			for name := range strings.SplitSeq(directiveStringValue(match[1]), ",") {
				name = strings.TrimSpace(name)
				if name == "" {
					return fmt.Errorf("invalid empty parameter name in fgb nullable")
				}
				result.Nullable = append(result.Nullable, name)
			}
			if len(result.Nullable) == 0 {
				return fmt.Errorf("invalid empty fgb nullable")
			}
			return nil
		}
		return fmt.Errorf("invalid //fgb: directive %q (want sync, async, ignore, opaque, rename = \"name\", or nullable = \"a,b\")", token)
	}

	if group == nil {
		return result, nil
	}
	for _, comment := range group.List {
		inner, isDirective := strings.CutPrefix(comment.Text, "//fgb:")
		if !isDirective {
			// A spaced `// fgb:` spelling would silently count as prose (and
			// leak into doc comments), so fail loudly on the near-miss.
			if trimmed := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//")); strings.HasPrefix(trimmed, "fgb:") {
				return result, fmt.Errorf("malformed directive %q: write //fgb:... without a space after //", comment.Text)
			}
			continue
		}
		inner = strings.TrimSpace(inner)
		if inner == "" {
			return result, fmt.Errorf("invalid empty //fgb: directive")
		}
		for _, token := range splitDirectiveTokens(inner) {
			if err := applyToken(token); err != nil {
				return result, err
			}
		}
	}
	return result, nil
}

// mergeSpecDirectives combines the doc comments of a spec and its enclosing
// declaration group; the spec's own comment wins for renames.
func mergeSpecDirectives(specDoc, declDoc *ast.CommentGroup) (directiveSet, error) {
	fromSpec, err := parseDirectives(specDoc)
	if err != nil {
		return fromSpec, err
	}
	fromDecl, err := parseDirectives(declDoc)
	if err != nil {
		return fromDecl, err
	}
	if fromSpec.HasMode || fromDecl.HasMode || len(fromSpec.Nullable) != 0 || len(fromDecl.Nullable) != 0 {
		return fromSpec, fmt.Errorf("call mode and nullable directives apply to functions, not type declarations")
	}
	result := fromSpec
	result.Ignore = fromSpec.Ignore || fromDecl.Ignore
	result.Opaque = fromSpec.Opaque || fromDecl.Opaque
	if result.Rename == "" {
		result.Rename = fromDecl.Rename
	}
	return result, nil
}

// cleanDocs turns a comment group into Dart-doc-ready text. `//fgb:` lines
// follow the Go directive syntax, so ast.CommentGroup.Text() already excludes
// them; only trailing whitespace is normalized here.
func cleanDocs(group *ast.CommentGroup) string {
	if group == nil {
		return ""
	}
	var kept []string
	for line := range strings.SplitSeq(group.Text(), "\n") {
		kept = append(kept, strings.TrimRight(line, " \t"))
	}
	return strings.TrimSpace(strings.Join(kept, "\n"))
}

// DumpAST is a small test/debug helper that keeps AST printing deterministic.
func DumpAST(api *model.API) string {
	var buffer bytes.Buffer
	for _, file := range api.Package.Syntax {
		if ast.IsGenerated(file) {
			continue
		}
		_ = ast.Fprint(&buffer, api.Package.Fset, file, nil)
	}
	return buffer.String()
}
