package parser

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	goparser "go/parser"
	"go/token"
	"go/types"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/star4277/flutter-go-bridge-gokit/internal/model"
	"github.com/star4277/flutter-go-bridge-gokit/internal/names"
	"golang.org/x/tools/go/packages"
)

type Options struct {
	Input    string
	BaseDir  string
	PrintAST bool
	ASTOut   io.Writer
}

func Parse(options Options) (*model.API, error) {
	if options.Input == "" {
		return nil, errors.New("empty Go input")
	}
	if options.BaseDir == "" {
		options.BaseDir = "."
	}
	if options.ASTOut == nil {
		options.ASTOut = io.Discard
	}

	dir, pattern, err := loadTarget(options.BaseDir, options.Input)
	if err != nil {
		return nil, err
	}
	cfg := &packages.Config{
		Dir: dir,
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedCompiledGoFiles |
			packages.NeedImports |
			packages.NeedDeps |
			packages.NeedModule |
			packages.NeedSyntax |
			packages.NeedTypes |
			packages.NeedTypesInfo |
			packages.NeedTypesSizes,
		Tests: false,
	}
	loaded, err := packages.Load(cfg, pattern)
	if err != nil {
		return nil, err
	}
	if packages.PrintErrors(loaded) > 0 {
		return nil, packageErrors(loaded)
	}
	if len(loaded) != 1 {
		return nil, fmt.Errorf("go_input must resolve to exactly one package, got %d", len(loaded))
	}
	pkg := loaded[0]
	if pkg.Types == nil || pkg.TypesInfo == nil {
		return nil, errors.New("Go package loader did not provide type information")
	}

	api := &model.API{
		Package:   pkg,
		InputDir:  packageDir(pkg, dir),
		Types:     map[*types.TypeName]*model.TypeDecl{},
		Constants: map[*types.Named][]*model.Constant{},
	}

	seenSourceFiles := map[string]bool{}
	for index, file := range pkg.Syntax {
		// Syntax files are not required to have the same ordering as
		// CompiledGoFiles (notably when cgo or generated files are present).
		// Resolve the filename from the official FileSet position instead of
		// relying on an index coincidence; this is what keeps Dart source
		// files mapped to the correct Go file.
		sourceFile := ""
		if position := pkg.Fset.Position(file.Pos()); position.Filename != "" {
			sourceFile = position.Filename
		} else if index < len(pkg.CompiledGoFiles) {
			// A defensive fallback for unusual loaders that omit position names.
			sourceFile = pkg.CompiledGoFiles[index]
		}
		if sourceFile != "" {
			if !filepath.IsAbs(sourceFile) {
				sourceFile = filepath.Join(dir, sourceFile)
			}
			sourceFile = filepath.Clean(sourceFile)
		}
		// packages.Load can include compiler/cache-only syntax files that are
		// not part of the original package sources. They must not become Dart
		// files (or affect source mirroring).
		if !isPackageGoFile(pkg, sourceFile) {
			continue
		}
		// cmd/cgo annotates the original Go source AST with its own
		// "Code generated by cmd/cgo" comment.  Treating that AST as a
		// generated file would silently discard the user's API whenever an
		// input file imports "C".  Only skip generated ASTs that do not map
		// back to one of the package's original Go files, or whose on-disk
		// source is itself genuinely marked as generated.
		if ast.IsGenerated(file) && shouldSkipGeneratedFile(pkg, sourceFile) {
			continue
		}
		if sourceFile != "" && !seenSourceFiles[sourceFile] {
			seenSourceFiles[sourceFile] = true
			api.SourceFiles = append(api.SourceFiles, sourceFile)
		}
		if options.PrintAST {
			_ = ast.Fprint(options.ASTOut, pkg.Fset, file, nil)
		}
		if err := collectFile(api, file, sourceFile); err != nil {
			return nil, err
		}
	}

	sort.SliceStable(api.Callables, func(i, j int) bool {
		return api.Callables[i].Position < api.Callables[j].Position
	})
	for _, constants := range api.Constants {
		sort.SliceStable(constants, func(i, j int) bool {
			return constants[i].Position < constants[j].Position
		})
	}
	sort.Strings(api.SourceFiles)
	return api, nil
}

func collectFile(api *model.API, file *ast.File, sourceFile string) error {
	for _, declaration := range file.Decls {
		switch declaration := declaration.(type) {
		case *ast.FuncDecl:
			object, _ := api.Package.TypesInfo.Defs[declaration.Name].(*types.Func)
			if object == nil || !object.Exported() || hasIgnoreDirective(declaration.Doc) {
				continue
			}
			signature, _ := object.Type().(*types.Signature)
			if signature == nil {
				continue
			}
			mode, err := directiveCallMode(declaration.Doc)
			if err != nil {
				return fmt.Errorf("%s: %w", object.FullName(), err)
			}
			callable := &model.Callable{
				Func:       object,
				Signature:  signature,
				Position:   declaration.Pos(),
				SourceFile: sourceFile,
				Docs:       cleanDocs(declaration.Doc),
				DartName:   directiveValue(declaration.Doc, "dart_name"),
				Mode:       mode,
			}
			if callable.DartName == "" {
				callable.DartName = names.LowerCamel(object.Name())
			}
			if recv := signature.Recv(); recv != nil {
				receiverType := recv.Type()
				if pointer, ok := receiverType.(*types.Pointer); ok {
					callable.PointerRecv = true
					receiverType = pointer.Elem()
				}
				callable.Receiver, _ = types.Unalias(receiverType).(*types.Named)
				if callable.Receiver == nil || callable.Receiver.Obj() == nil || !callable.Receiver.Obj().Exported() {
					continue
				}
			}
			api.Callables = append(api.Callables, callable)

		case *ast.GenDecl:
			switch declaration.Tok {
			case token.TYPE:
				for _, spec := range declaration.Specs {
					typeSpec, _ := spec.(*ast.TypeSpec)
					if typeSpec == nil || !typeSpec.Name.IsExported() {
						continue
					}
					object, _ := api.Package.TypesInfo.Defs[typeSpec.Name].(*types.TypeName)
					if object == nil || hasIgnoreDirective(typeSpec.Doc) || hasIgnoreDirective(declaration.Doc) {
						continue
					}
					named, _ := object.Type().(*types.Named)
					if named == nil {
						continue
					}
					docs := typeSpec.Doc
					if docs == nil {
						docs = declaration.Doc
					}
					dartName := directiveValue(docs, "dart_name")
					if dartName == "" {
						dartName = names.UpperCamel(object.Name())
					}
					api.Types[object] = &model.TypeDecl{
						Object: object, Named: named, Position: typeSpec.Pos(), SourceFile: sourceFile, AST: typeSpec,
						Docs: cleanDocs(docs), DartName: dartName,
					}
				}
			case token.CONST:
				for _, spec := range declaration.Specs {
					valueSpec, _ := spec.(*ast.ValueSpec)
					if valueSpec == nil {
						continue
					}
					for _, identifier := range valueSpec.Names {
						object, _ := api.Package.TypesInfo.Defs[identifier].(*types.Const)
						if object == nil || !object.Exported() || hasIgnoreDirective(valueSpec.Doc) || hasIgnoreDirective(declaration.Doc) {
							continue
						}
						named, _ := types.Unalias(object.Type()).(*types.Named)
						if named == nil {
							continue
						}
						docs := valueSpec.Doc
						if docs == nil {
							docs = declaration.Doc
						}
						dartName := directiveValue(docs, "dart_name")
						if dartName == "" {
							dartName = names.LowerCamel(identifier.Name)
						}
						api.Constants[named] = append(api.Constants[named], &model.Constant{
							Object: object, Position: identifier.Pos(), Docs: cleanDocs(docs), DartName: dartName,
						})
					}
				}
			}
		}
	}
	return nil
}

func loadTarget(baseDir, input string) (dir, pattern string, err error) {
	absBase, err := filepath.Abs(baseDir)
	if err != nil {
		return "", "", err
	}
	candidate := input
	if !filepath.IsAbs(candidate) {
		candidate = filepath.Join(absBase, candidate)
	}
	info, statErr := os.Stat(candidate)
	if statErr == nil {
		if info.IsDir() {
			return candidate, ".", nil
		}
		if filepath.Ext(candidate) != ".go" {
			return "", "", fmt.Errorf("go_input file must end in .go: %s", candidate)
		}
		return filepath.Dir(candidate), "file=" + candidate, nil
	}
	if !errors.Is(statErr, os.ErrNotExist) {
		return "", "", statErr
	}
	return absBase, input, nil
}

func packageDir(pkg *packages.Package, fallback string) string {
	// CompiledGoFiles may point into the Go build cache (especially for cgo
	// packages).  GoFiles are the original user sources and therefore provide
	// the stable directory used for Dart source mirroring.
	for _, file := range pkg.GoFiles {
		if file == "" {
			continue
		}
		if absolute, err := filepath.Abs(file); err == nil {
			return filepath.Dir(absolute)
		}
		return filepath.Dir(filepath.Clean(file))
	}
	return fallback
}

func shouldSkipGeneratedFile(pkg *packages.Package, sourceFile string) bool {
	if sourceFile == "" || !isPackageGoFile(pkg, sourceFile) {
		return true
	}
	raw, err := os.ReadFile(sourceFile)
	if err != nil {
		return true
	}
	original, err := goparser.ParseFile(token.NewFileSet(), sourceFile, raw, goparser.ParseComments)
	if err != nil {
		return true
	}
	return ast.IsGenerated(original)
}

func isPackageGoFile(pkg *packages.Package, sourceFile string) bool {
	for _, file := range pkg.GoFiles {
		if sameFilePath(file, sourceFile) {
			return true
		}
	}
	return false
}

func sameFilePath(left, right string) bool {
	leftAbs, leftErr := filepath.Abs(left)
	rightAbs, rightErr := filepath.Abs(right)
	if leftErr != nil || rightErr != nil {
		return filepath.Clean(left) == filepath.Clean(right)
	}
	return strings.EqualFold(filepath.Clean(leftAbs), filepath.Clean(rightAbs))
}

func packageErrors(pkgs []*packages.Package) error {
	var lines []string
	for _, pkg := range pkgs {
		for _, item := range pkg.Errors {
			lines = append(lines, item.Error())
		}
	}
	return errors.New(strings.Join(lines, "\n"))
}

func hasIgnoreDirective(group *ast.CommentGroup) bool {
	return directiveValue(group, "ignore") != ""
}

var callModeDirectivePattern = regexp.MustCompile(`^(?:fgb|flutter_go_bridge)\s*\(\s*([^)]*?)\s*\)$`)

// directiveCallMode accepts the compact marker requested by the generator
// API (`// fgb(sync)` / `// fgb(async)`) as well as the colon form used by
// earlier versions (`// fgb:mode=async`). Unmarked declarations are sync.
func directiveCallMode(group *ast.CommentGroup) (model.CallMode, error) {
	mode := model.CallModeSync
	seen := false
	if group == nil {
		return mode, nil
	}
	for _, comment := range group.List {
		text := strings.TrimSpace(strings.TrimPrefix(strings.TrimPrefix(comment.Text, "//"), "/*"))
		text = strings.TrimSuffix(text, "*/")
		for _, line := range strings.Split(text, "\n") {
			line = strings.TrimSpace(line)
			candidate := callModeDirectivePattern.FindStringSubmatch(line)
			value := ""
			if len(candidate) == 2 {
				value = strings.TrimSpace(candidate[1])
				if value == "" {
					return mode, fmt.Errorf("invalid empty fgb call mode (want sync or async)")
				}
			} else {
				for _, prefix := range []string{"flutter_go_bridge:", "fgb:"} {
					if !strings.HasPrefix(line, prefix) {
						continue
					}
					raw := strings.TrimSpace(strings.TrimPrefix(line, prefix))
					switch {
					case raw == "sync" || raw == "async":
						value = raw
					case strings.HasPrefix(raw, "mode="):
						value = strings.TrimSpace(strings.TrimPrefix(raw, "mode="))
					}
					break
				}
			}
			if value == "" {
				continue
			}
			var parsed model.CallMode
			switch value {
			case "sync":
				parsed = model.CallModeSync
			case "async":
				parsed = model.CallModeAsync
			default:
				return mode, fmt.Errorf("invalid fgb call mode %q (want sync or async)", value)
			}
			if seen && parsed != mode {
				return mode, fmt.Errorf("conflicting fgb call mode directives")
			}
			mode, seen = parsed, true
		}
	}
	return mode, nil
}

func isBridgeDirectiveLine(line string) bool {
	line = strings.TrimSpace(line)
	if strings.HasPrefix(line, "flutter_go_bridge:") || strings.HasPrefix(line, "fgb:") {
		return true
	}
	return callModeDirectivePattern.MatchString(line)
}

func directiveValue(group *ast.CommentGroup, key string) string {
	if group == nil {
		return ""
	}
	for _, comment := range group.List {
		text := strings.TrimSpace(strings.TrimPrefix(strings.TrimPrefix(comment.Text, "//"), "/*"))
		text = strings.TrimSuffix(text, "*/")
		for _, prefix := range []string{"flutter_go_bridge:", "fgb:"} {
			if !strings.HasPrefix(text, prefix) {
				continue
			}
			value := strings.TrimSpace(strings.TrimPrefix(text, prefix))
			if value == key {
				return "true"
			}
			if strings.HasPrefix(value, key+"=") {
				return strings.TrimSpace(strings.TrimPrefix(value, key+"="))
			}
		}
	}
	return ""
}

func cleanDocs(group *ast.CommentGroup) string {
	if group == nil {
		return ""
	}
	var kept []string
	for _, line := range strings.Split(group.Text(), "\n") {
		trimmed := strings.TrimSpace(line)
		if isBridgeDirectiveLine(trimmed) {
			continue
		}
		kept = append(kept, strings.TrimRight(line, " \t"))
	}
	return strings.TrimSpace(strings.Join(kept, "\n"))
}

// DumpAST is a small test/debug helper that keeps AST printing deterministic.
func DumpAST(api *model.API) string {
	var buffer bytes.Buffer
	for _, file := range api.Package.Syntax {
		if ast.IsGenerated(file) {
			continue
		}
		_ = ast.Fprint(&buffer, api.Package.Fset, file, nil)
	}
	return buffer.String()
}
