// Code generated by flutter_go_bridge_codegen. DO NOT EDIT.
// ignore_for_file: unused_element, unused_import, unnecessary_import
import "bridge_generated.dart";
import 'dart:async';
import 'dart:typed_data';

int main() {
  final bridge = Generated.instance;
  return bridge.fgbInternalCall0();
}
