package generator

import (
	"fmt"
	"strconv"
	"strings"
)

func renderGoWeb(unit *unit) ([]byte, error) {
	r := &goRenderer{unit: unit}
	if unit.GoPreamble != "" {
		r.raw(strings.TrimRight(unit.GoPreamble, "\n"))
		r.line("")
	}
	r.line("// Code generated by flutter_go_bridge_codegen. DO NOT EDIT.")
	r.line("package main")
	r.line("")
	r.line("import (")
	imports := []string{
		"bytes", "encoding/binary", "fmt", "io", "math/big", "os", "reflect",
		"runtime/debug", "sync", "sync/atomic", "syscall/js", "unsafe",
	}
	for _, call := range unit.Calls {
		if isAsyncCall(call) {
			imports = append(imports, "context")
			break
		}
	}
	if unit.UsesTime {
		imports = append(imports, "time")
	}
	if unit.UsesInternetIP || unit.UsesIPPrefix {
		imports = append(imports, "net/netip")
	}
	if unit.UsesURL {
		imports = append(imports, "net/url")
	}
	if unit.UsesUUID {
		imports = append(imports, "github.com/gofrs/uuid/v5")
	}
	if unit.UsesShopspringDecimal {
		imports = append(imports, "github.com/shopspring/decimal")
	}
	if unit.UsesAPDDecimal {
		imports = append(imports, "github.com/cockroachdb/apd/v3")
	}
	for _, item := range imports {
		r.line("\t%q", item)
	}
	if unit.UsesRuntimePackage {
		r.line("\tfgbrt %q", unit.SupportPackagePath)
	}
	if !unit.Direct && len(unit.Calls) != 0 {
		r.line("\tapi %q", unit.PackagePath)
	}
	for _, item := range unit.ExternalImports {
		r.line("\t%s %q", item.Alias, item.Path)
	}
	r.line(")")
	r.line("")
	base, err := webGoRuntimeBase(goRuntimeSource)
	if err != nil {
		return nil, err
	}
	r.raw(base)
	r.line("")
	if unit.UsesTime {
		r.renderTimeHelpers()
	}
	for _, typ := range unit.Types {
		if err := r.renderDecoder(typ); err != nil {
			return nil, err
		}
		r.line("")
		if err := r.renderEncoder(typ); err != nil {
			return nil, err
		}
		r.line("")
	}
	r.renderDispatch()
	r.line("")
	transport := strings.ReplaceAll(goWebTransportSource, "__FGB_LIBRARY_NAME__", strconv.Quote(unit.LibraryName))
	r.raw(strings.TrimSpace(transport))
	if unit.NeedsMain {
		r.line("")
		r.line("func main() { select {} }")
	}
	return r.buffer.Bytes(), nil
}

func webGoRuntimeBase(source string) (string, error) {
	base, _, found := strings.Cut(source, "// CST/DCO helpers")
	if !found {
		return "", fmt.Errorf("Web runtime split marker is missing")
	}
	return strings.TrimSpace(base), nil
}

const goWebTransportSource = `
func fgbHandle(request []byte) (response []byte, transfer *fgbOpaqueTransfer) {
	transfer = &fgbOpaqueTransfer{}
	codec := fgbStandardMethodCodec{}
	defer func() {
		if recovered := recover(); recovered != nil {
			transfer.rollback()
			response = fgbEncodeCallError(codec, &fgbCallError{
				Code: "panic", Message: fmt.Sprintf("panic: %v", recovered),
				Details: map[any]any{"stack": fgbPanicStack()},
			})
		}
	}()
	call, err := codec.decodeMethodCall(request)
	if err != nil {
		return fgbEncodeCallError(codec, &fgbCallError{Code: "invalid_request", Message: err.Error()}), transfer
	}
	value, callErr := fgbDispatch(call, transfer)
	if callErr != nil {
		transfer.rollback()
		return fgbEncodeCallError(codec, callErr), transfer
	}
	response, err = codec.encodeSuccess(value)
	if err != nil {
		transfer.rollback()
		return fgbEncodeCallError(codec, &fgbCallError{Code: "encode_error", Message: err.Error()}), transfer
	}
	return response, transfer
}

func fgbPanicStack() []byte {
	if os.Getenv("FGB_DEBUG_PANIC_STACK") == "1" {
		return debug.Stack()
	}
	return nil
}

var fgbWebInvokeFunction js.Func

func fgbWebInvoke(_ js.Value, arguments []js.Value) any {
	if len(arguments) != 1 || arguments[0].Type() != js.TypeObject {
		return fgbWebBytes(fgbEncodeCallError(fgbStandardMethodCodec{}, &fgbCallError{
			Code: "invalid_request", Message: "Web bridge expects one Uint8Array argument",
		}))
	}
	request := make([]byte, arguments[0].Get("byteLength").Int())
	if copied := js.CopyBytesToGo(request, arguments[0]); copied != len(request) {
		return fgbWebBytes(fgbEncodeCallError(fgbStandardMethodCodec{}, &fgbCallError{
			Code: "invalid_request", Message: "could not copy the complete Web request",
		}))
	}
	response, transfer := fgbHandle(request)
	transfer.commit()
	return fgbWebBytes(response)
}

func fgbWebBytes(value []byte) js.Value {
	result := js.Global().Get("Uint8Array").New(len(value))
	js.CopyBytesToJS(result, value)
	return result
}

func init() {
	global := js.Global()
	registry := global.Get("__flutterGoBridge")
	if registry.Type() != js.TypeObject {
		registry = global.Get("Object").Call("create", js.Null())
		global.Set("__flutterGoBridge", registry)
	}
	fgbWebInvokeFunction = js.FuncOf(fgbWebInvoke)
	registry.Set(__FGB_LIBRARY_NAME__, fgbWebInvokeFunction)
}
`
