package generator

import (
	"bytes"
	"fmt"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	bridgemodel "github.com/star4277/flutter_go_bridge/internal/model"
)

type splitDartRenderer struct {
	unit   *unit
	buffer bytes.Buffer
}

type dartSourceGroup struct {
	Calls      []*callModel
	Structs    []*structModel
	Opaques    []*opaqueModel
	Named      []*namedModel
	Interfaces []*interfaceModel
}

// dartResultType is the Dart type a call hands back: nothing, a single value,
// or - for several non-error Go results - a record. Named Go results produce a
// named record so callers read `result.total` instead of `result.$2`.
func dartResultType(call *callModel) string {
	if call == nil || len(call.Results) == 0 {
		return "void"
	}
	if len(call.Results) == 1 {
		return call.Results[0].Type.DartType
	}
	fields := make([]string, 0, len(call.Results))
	for _, result := range call.Results {
		if call.NamedResults {
			fields = append(fields, fmt.Sprintf("%s %s", result.Type.DartType, result.DartName))
		} else {
			fields = append(fields, result.Type.DartType)
		}
	}
	if call.NamedResults {
		return "({" + strings.Join(fields, ", ") + "})"
	}
	return "(" + strings.Join(fields, ", ") + ")"
}

// dartResultDecodeLines renders the statements that turn one wire value into
// the call's Dart result. Several results arrive as a list and are rebuilt
// into a record.
func dartResultDecodeLines(call *callModel, wireExpression, indent string) []string {
	if len(call.Results) == 1 {
		return []string{fmt.Sprintf("%sreturn fgbDecode%d(%s, this, 'result');", indent, call.Results[0].Type.ID, wireExpression)}
	}
	lines := []string{fmt.Sprintf("%sfinal fgbRecord = fgbAsResultList(%s, %d);", indent, wireExpression, len(call.Results))}
	fields := make([]string, 0, len(call.Results))
	for index, result := range call.Results {
		value := fmt.Sprintf("fgbDecode%d(fgbRecord[%d], this, 'result.%d')", result.Type.ID, index, index)
		if call.NamedResults {
			value = result.DartName + ": " + value
		}
		fields = append(fields, value)
	}
	return append(lines, fmt.Sprintf("%sreturn (%s);", indent, strings.Join(fields, ", ")))
}

// dartParamType is the Dart spelling of a parameter in the public API.
// Callbacks marked `//fgb:nullable` accept null.
func dartParamType(param *paramModel) string {
	if param.Nullable {
		return param.Type.DartType + "?"
	}
	return param.Type.DartType
}

// dartEncoderValueType is the Dart parameter type of a generated encoder.
// Encoders for Go types that can be nil on their own always accept null, so
// one encoder serves both nullable and non-nullable parameters: a null value
// encodes as a null wire value (handle 0 for closures), which the Go side
// turns back into a nil value.
func dartEncoderValueType(typ *wireType) string {
	if typ.nilableWithoutPointer() {
		return typ.DartType + "?"
	}
	return typ.DartType
}

// dartParams renders the public API parameter list. Every generated Dart
// entrypoint uses named parameters; Go pointer parameters and nullable
// callbacks map to optional ones, everything else is required. A sink that
// the call owns (see callModel.StreamParam) is not part of the public API.
func dartParams(call *callModel) string {
	if call == nil || len(call.Params) == 0 {
		return ""
	}
	params := make([]string, 0, len(call.Params))
	for _, param := range call.Params {
		if param == call.StreamParam {
			continue
		}
		if param.Nullable || isPointerType(param.Type.Original) {
			params = append(params, fmt.Sprintf("%s %s", dartParamType(param), param.DartName))
		} else {
			params = append(params, fmt.Sprintf("required %s %s", dartParamType(param), param.DartName))
		}
	}
	if len(params) == 0 {
		return ""
	}
	return "{" + strings.Join(params, ", ") + "}"
}

func isAsyncCall(call *callModel) bool {
	return call != nil && call.Mode == bridgemodel.CallModeAsync
}

func renderDartSplit(unit *unit, configuredOutput string) (map[string][]byte, error) {
	root, central := dartOutputPaths(configuredOutput)
	groups, paths := dartSourceGroups(unit)
	orderedKeys := sortedSourceKeys(paths)
	result := map[string][]byte{}

	centralRenderer := &splitDartRenderer{unit: unit}
	centralRenderer.line("// Code generated by flutter_go_bridge_codegen. DO NOT EDIT.")
	centralRenderer.line("// ignore_for_file: unused_element, unused_import, unnecessary_import")
	centralRenderer.line("library flutter_go_bridge;")
	centralRenderer.line("import 'dart:async';")
	centralRenderer.line("import 'dart:convert';")
	centralRenderer.line("import 'dart:ffi' as ffi;")
	centralRenderer.line("import 'dart:io';")
	centralRenderer.line("import 'dart:isolate';")
	centralRenderer.line("import 'dart:typed_data';")
	for _, key := range orderedKeys {
		relative := paths[key]
		centralRenderer.line("import %s;", strconv.Quote(filepath.ToSlash(relative)))
	}
	centralRenderer.line("")
	if unit.DartPreamble != "" {
		centralRenderer.raw(strings.TrimRight(unit.DartPreamble, "\n"))
		centralRenderer.line("")
	}
	if hasCstDcoCalls(unit) {
		centralRenderer.raw(cstDartDefinitions(unit))
		centralRenderer.line("")
	}
	runtime := strings.ReplaceAll(dartRuntimeSource, "__FGB_LIBRARY_NAME__", strconv.Quote(unit.LibraryName))
	runtime = strings.ReplaceAll(runtime, "__FGB_BRIDGE_CLASS__", unit.ClassName)
	centralRenderer.raw(runtime)
	for _, typ := range unit.Types {
		if err := centralRenderer.renderDecoder(typ); err != nil {
			return nil, err
		}
		centralRenderer.line("")
		if err := centralRenderer.renderEncoder(typ); err != nil {
			return nil, err
		}
		centralRenderer.line("")
	}
	if hasCstDcoCalls(unit) {
		centralRenderer.renderCstEncoders()
	}
	centralRenderer.renderCentralCallMethods()
	result[central] = []byte(strings.ReplaceAll(centralRenderer.buffer.String(), "__FGB_BRIDGE_CLASS__", unit.ClassName))

	for _, key := range orderedKeys {
		relative := paths[key]
		sourcePath := filepath.Join(root, filepath.FromSlash(relative))
		if samePath(sourcePath, central) {
			return nil, fmt.Errorf("Dart source %s collides with bridge output %s; choose a different dart_output", relative, central)
		}
		centralImport := dartImportPath(sourcePath, central)
		renderer := &splitDartRenderer{unit: unit}
		renderer.line("// Code generated by flutter_go_bridge_codegen. DO NOT EDIT.")
		renderer.line("// ignore_for_file: unused_element, unused_import, unnecessary_import")
		renderer.line("import %s;", centralImport)
		// Go types may reference each other across files, so every API file can
		// see its siblings. Dart tolerates the resulting import cycles.
		for _, other := range orderedKeys {
			if other == key {
				continue
			}
			renderer.line("import %s;", dartImportPath(sourcePath, filepath.Join(root, filepath.FromSlash(paths[other]))))
		}
		renderer.line("import 'dart:async';")
		renderer.line("import 'dart:typed_data';")
		renderer.line("")
		group := groups[key]
		for _, declaration := range group.Interfaces {
			renderer.renderInterface(declaration)
		}
		for _, structure := range group.Structs {
			renderer.renderStruct(structure)
		}
		for _, opaque := range group.Opaques {
			renderer.renderOpaque(opaque)
		}
		for _, named := range group.Named {
			renderer.renderNamed(named)
		}
		for _, call := range group.Calls {
			renderer.renderTopCall(call)
		}
		result[sourcePath] = []byte(strings.ReplaceAll(renderer.buffer.String(), "__FGB_BRIDGE_CLASS__", unit.ClassName))
	}
	return result, nil
}

func sortedSourceKeys(paths map[string]string) []string {
	keys := make([]string, 0, len(paths))
	for key := range paths {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func dartImportPath(fromFile, targetFile string) string {
	relative, err := filepath.Rel(filepath.Dir(fromFile), targetFile)
	if err != nil || relative == "." {
		relative = filepath.Base(targetFile)
	}
	return strconv.Quote(filepath.ToSlash(relative))
}

func dartOutputPaths(configured string) (root, central string) {
	if strings.EqualFold(filepath.Ext(configured), ".dart") {
		return filepath.Dir(configured), configured
	}
	return configured, filepath.Join(configured, "bridge_generated.dart")
}

func dartSourceGroups(unit *unit) (map[string]*dartSourceGroup, map[string]string) {
	groups := map[string]*dartSourceGroup{}
	paths := map[string]string{}
	ensure := func(source string) string {
		key := cleanSourcePath(source)
		if key == "" {
			key = "<generated>"
		}
		if _, ok := groups[key]; !ok {
			groups[key] = &dartSourceGroup{}
		}
		if _, ok := paths[key]; !ok {
			if key == "<generated>" {
				paths[key] = "_generated.dart"
			} else {
				paths[key] = sourceDartPath(unit.MirrorRoot, source)
			}
		}
		return key
	}
	for _, source := range unit.SourceFiles {
		ensure(source)
	}
	for _, structure := range unit.Structs {
		ensure(structure.SourceFile)
		groups[cleanOrGenerated(structure.SourceFile)].Structs = append(groups[cleanOrGenerated(structure.SourceFile)].Structs, structure)
	}
	for _, opaque := range unit.Opaques {
		ensure(opaque.SourceFile)
		groups[cleanOrGenerated(opaque.SourceFile)].Opaques = append(groups[cleanOrGenerated(opaque.SourceFile)].Opaques, opaque)
	}
	for _, declaration := range unit.Interfaces {
		ensure(declaration.SourceFile)
		groups[cleanOrGenerated(declaration.SourceFile)].Interfaces = append(groups[cleanOrGenerated(declaration.SourceFile)].Interfaces, declaration)
	}
	for _, named := range unit.Named {
		ensure(named.SourceFile)
		groups[cleanOrGenerated(named.SourceFile)].Named = append(groups[cleanOrGenerated(named.SourceFile)].Named, named)
	}
	for _, call := range unit.TopCalls {
		key := ensure(call.SourceFile)
		groups[key].Calls = append(groups[key].Calls, call)
	}
	if len(paths) == 0 {
		paths["<generated>"] = "_generated.dart"
		groups["<generated>"] = &dartSourceGroup{}
	}
	return groups, paths
}

func cleanOrGenerated(source string) string {
	if source == "" {
		return "<generated>"
	}
	return cleanSourcePath(source)
}

func cleanSourcePath(value string) string {
	if value == "" {
		return ""
	}
	abs, err := filepath.Abs(value)
	if err != nil {
		return filepath.Clean(value)
	}
	return filepath.Clean(abs)
}

// sourceDartPath mirrors the Go package tree into the Dart output tree. The
// anchor is the Go module root, so go/api/lib.go becomes api/lib.dart next to
// bridge_generated.dart - the Dart layout then reads like the Go one instead
// of flattening every package into a single directory.
func sourceDartPath(mirrorRoot, source string) string {
	relative, err := filepath.Rel(mirrorRoot, source)
	if err != nil || relative == "." || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
		relative = filepath.Base(source)
	}
	relative = strings.TrimSuffix(relative, filepath.Ext(relative)) + ".dart"
	return filepath.ToSlash(relative)
}

func (r *splitDartRenderer) renderTopCall(call *callModel) {
	resultType := dartResultType(call)
	params := dartParams(call)
	args := make([]string, len(call.Params))
	for index, param := range call.Params {
		args[index] = param.DartName
	}
	r.dartDoc(call.Docs, "")
	if call.StreamParam != nil {
		r.renderStreamCall(call, "__FGB_BRIDGE_CLASS__.instance", args, params, "")
		r.line("")
		return
	}
	invocation := fmt.Sprintf("bridge.fgbInternalCall%d(%s)", call.ID, strings.Join(args, ", "))
	if isAsyncCall(call) {
		r.line("Future<%s> %s(%s) async {", resultType, call.DartName, params)
		r.line("  final bridge = __FGB_BRIDGE_CLASS__.instance;")
		if len(call.Results) == 0 {
			r.line("  await %s;", invocation)
		} else {
			r.line("  return await %s;", invocation)
		}
	} else {
		r.line("%s %s(%s) {", resultType, call.DartName, params)
		r.line("  final bridge = __FGB_BRIDGE_CLASS__.instance;")
		if len(call.Results) == 0 {
			r.line("  %s;", invocation)
		} else {
			r.line("  return %s;", invocation)
		}
	}
	r.line("}")
	r.line("")
}

// renderStreamCall emits a call that owns its stream: the generated function
// creates the StreamController and hands its sink to Go. The Go call only
// starts when the stream is listened to - a Dart stream is cold, and starting
// eagerly would let a discarded stream buffer forever. Cancelling the
// subscription releases the sink so the Go side learns to stop producing and
// retires the controller; a failing call surfaces as a stream error.
func (r *splitDartRenderer) renderStreamCall(call *callModel, bridge string, args []string, params, indent string) {
	elem := call.StreamParam.Type.Stream.DartType
	for index, param := range call.Params {
		if param == call.StreamParam {
			args[index] = "controller.sink"
		}
	}
	r.line("%sStream<%s> %s(%s) {", indent, elem, call.DartName, params)
	r.line("%s  final bridge = %s;", indent, bridge)
	r.line("%s  final controller = StreamController<%s>();", indent, elem)
	r.line("%s  controller.onListen = () {", indent)
	r.line("%s    bridge.fgbInternalStartStream(controller, bridge.fgbInternalCall%d(%s));", indent, call.ID, strings.Join(args, ", "))
	r.line("%s  };", indent)
	r.line("%s  return controller.stream;", indent)
	r.line("%s}", indent)
}

// renderInterface emits a Go interface as a Dart `abstract interface class`.
// The methods are declaration-only: a call on an interface value dispatches to
// the concrete class, which owns the bridged implementation.
func (r *splitDartRenderer) renderInterface(declaration *interfaceModel) {
	r.dartDoc(declaration.Docs, "")
	r.line("abstract interface class %s {", declaration.DartName)
	for _, method := range declaration.Methods {
		r.dartDoc(method.Docs, "  ")
		resultType := dartResultType(method)
		if isAsyncCall(method) {
			resultType = "Future<" + resultType + ">"
		}
		r.line("  %s %s(%s);", resultType, method.DartName, dartParams(method))
	}
	r.line("}")
	r.line("")
}

// dartImplementsClause renders the `implements` list for a bridged type.
func dartImplementsClause(interfaces []*interfaceModel) string {
	if len(interfaces) == 0 {
		return ""
	}
	names := make([]string, 0, len(interfaces))
	for _, declaration := range interfaces {
		names = append(names, declaration.DartName)
	}
	return " implements " + strings.Join(names, ", ")
}

func (r *splitDartRenderer) renderStruct(structure *structModel) {
	r.dartDoc(structure.Docs, "")
	// An embedded Go struct becomes the Dart superclass, so the promoted
	// fields are declared once - up there - and reached through inheritance.
	// Anything taking part in that hierarchy is a plain class: Dart forbids
	// extending a `final` one.
	declaration := "final class " + structure.DartName
	if structure.Subclassed || structure.Super != nil {
		declaration = "class " + structure.DartName
	}
	if structure.Super != nil {
		declaration += " extends " + structure.Super.DartName
	}
	declaration += dartImplementsClause(structure.Interfaces)
	r.line("%s {", declaration)
	for _, field := range structure.Fields {
		if field.NonFinal {
			r.line("  %s %s;", field.dartType(), field.DartName)
		} else {
			r.line("  final %s %s;", field.dartType(), field.DartName)
		}
	}
	r.line("")
	constructorKeyword := "const "
	for _, field := range structure.allFields() {
		if field.NonFinal {
			constructorKeyword = ""
			break
		}
	}
	if structure.Super != nil {
		// A const constructor cannot forward to a non-const superclass one.
		constructorKeyword = ""
	}
	r.line("  %s%s({", constructorKeyword, structure.DartName)
	for _, field := range structure.Super.allFields() {
		r.line("    %s,", dartConstructorParameter(field, "super"))
	}
	for _, field := range structure.Fields {
		r.line("    %s,", dartConstructorParameter(field, "this"))
	}
	r.line("  });")
	for _, call := range structure.Methods {
		r.line("")
		r.renderInstanceCall(call, "this", "__FGB_BRIDGE_CLASS__.instance", true, "  ")
	}
	r.line("}")
	r.line("")
}

// dartFieldDecode reads one struct field. A field marked `fgb:"nullable"`
// keeps a null wire value as null instead of letting the shared decoder
// normalize it.
func dartFieldDecode(field *fieldModel, source, path string) string {
	decoded := fmt.Sprintf("fgbDecode%d(%s, bridge, %s)", field.Type.ID, source, path)
	if field.Nullable {
		return fmt.Sprintf("%s == null ? null : %s", source, decoded)
	}
	return decoded
}

// dartConstructorParameter renders one constructor entry, forwarding promoted
// fields to the superclass and binding the struct's own fields directly.
func dartConstructorParameter(field *fieldModel, receiver string) string {
	switch {
	case field.DefaultValue != "":
		return fmt.Sprintf("%s.%s = %s", receiver, field.DartName, field.DefaultValue)
	case field.optional():
		return fmt.Sprintf("%s.%s", receiver, field.DartName)
	default:
		return fmt.Sprintf("required %s.%s", receiver, field.DartName)
	}
}

func (r *splitDartRenderer) renderOpaque(opaque *opaqueModel) {
	r.dartDoc(opaque.Docs, "")
	r.line("final class %s extends GoOpaque%s {", opaque.DartName, dartImplementsClause(opaque.Interfaces))
	r.line("  %s.fgbInternal({required super.fgbBridge, required super.fgbHandle});", opaque.DartName)
	for _, call := range opaque.Methods {
		r.line("")
		r.renderInstanceCall(call, "this", "fgbBridge", false, "  ")
	}
	r.line("}")
	r.line("")
}

func (r *splitDartRenderer) renderNamed(named *namedModel) {
	r.dartDoc(named.Docs, "")
	if named.Underlying == nil || named.Underlying.Kind == kindOpaque {
		return
	}
	r.line("extension type const %s(%s value) {", named.DartName, named.Underlying.DartType)
	for _, item := range named.Constants {
		if item.IsConst {
			r.line("  static const %s = %s(%s);", item.DartName, named.DartName, item.DartLiteral)
		} else {
			r.line("  static final %s = %s(%s);", item.DartName, named.DartName, item.DartLiteral)
		}
	}
	for _, call := range named.Methods {
		r.line("")
		r.renderInstanceCall(call, "this", "__FGB_BRIDGE_CLASS__.instance", true, "  ")
	}
	r.line("}")
	r.line("")
}

func (r *splitDartRenderer) renderInstanceCall(call *callModel, receiver, bridge string, valueReceiver bool, indent string) {
	resultType := dartResultType(call)
	params := dartParams(call)
	args := []string{receiver}
	for _, param := range call.Params {
		args = append(args, param.DartName)
	}
	invocation := fmt.Sprintf("%s.fgbInternalCall%d(%s)", bridge, call.ID, strings.Join(args, ", "))
	if valueReceiver {
		// Value objects do not retain a bridge; the generated API uses the
		// process-wide bridge singleton just like top-level functions.
		bridge = "__FGB_BRIDGE_CLASS__.instance"
	}
	r.dartDoc(call.Docs, indent)
	if call.Overrides {
		r.line("%s@override", indent)
	}
	if call.StreamParam != nil {
		r.renderStreamCall(call, bridge, args, params, indent)
		return
	}
	if isAsyncCall(call) {
		r.line("%sFuture<%s> %s(%s) async {", indent, resultType, call.DartName, params)
		if len(call.Results) == 0 {
			r.line("%s  await %s;", indent, invocation)
		} else {
			r.line("%s  return await %s;", indent, invocation)
		}
	} else {
		r.line("%s%s %s(%s) {", indent, resultType, call.DartName, params)
		if len(call.Results) == 0 {
			r.line("%s  %s;", indent, invocation)
		} else {
			r.line("%s  return %s;", indent, invocation)
		}
	}
	r.line("%s}", indent)
}

// renderStreamSinkRegistration registers the Dart sink and hands Go the
// resulting handle. The typed add closure is stored alongside the sink so the
// shared stream dispatcher can decode items without knowing their type.
func (r *splitDartRenderer) renderStreamSinkRegistration(typ *wireType, bridge string) {
	r.line("  return %s.fgbInternalRegisterStreamSink(value, (Object? raw) {", bridge)
	r.line("    value.add(fgbDecode%d(raw, %s, '$path item'));", typ.Stream.ID, bridge)
	r.line("  });")
}

// taggedImplementor pairs an implementation with its wire tag.
type taggedImplementor struct {
	*implementorModel
	Index int
}

// sortedImplementors orders the `value is X` checks so a subclass is tested
// before the class it extends - otherwise the superclass check would swallow
// it and the wrong tag would be sent.
func sortedImplementors(declaration *interfaceModel) []taggedImplementor {
	result := make([]taggedImplementor, 0, len(declaration.Implementors))
	for index, implementor := range declaration.Implementors {
		result = append(result, taggedImplementor{implementorModel: implementor, Index: index})
	}
	depth := func(item taggedImplementor) int {
		count := 0
		if item.Type.Kind != kindStruct {
			return count
		}
		for super := item.Type.Struct.Super; super != nil; super = super.Super {
			count++
		}
		return count
	}
	sort.SliceStable(result, func(i, j int) bool { return depth(result[i]) > depth(result[j]) })
	return result
}

// renderCallbackRegistration wraps the user closure into a uniform invoker:
// decode wire arguments, run the closure - `Future.sync` + `await` folds
// sync results, futures from async closures, and thrown errors into one
// path - then wire-encode the reply for Go. A null closure encodes as handle
// 0 so Go receives a nil func value.
func (r *splitDartRenderer) renderCallbackRegistration(typ *wireType, bridge string) {
	callback := typ.Callback
	r.line("  if (value == null) return 0;")
	r.line("  return %s.fgbInternalRegisterCallback((List<Object?> args) async {", bridge)
	r.line("    if (args.length != %d) throw FormatException('callback expects %d arguments');", len(callback.Params), len(callback.Params))
	arguments := make([]string, len(callback.Params))
	for index, param := range callback.Params {
		r.line("    final a%d = fgbDecode%d(args[%d], %s, 'callback[%d]');", index, param.ID, index, bridge, index)
		arguments[index] = fmt.Sprintf("a%d", index)
	}
	invocation := fmt.Sprintf("value(%s)", strings.Join(arguments, ", "))
	if callback.Result != nil {
		r.line("    final result = await Future.sync(() => %s);", invocation)
		r.line("    return fgbEncode%d(result, %s, 'callback result');", callback.Result.ID, bridge)
	} else {
		r.line("    await Future.sync(() => %s);", invocation)
		r.line("    return null;")
	}
	r.line("  });")
}

func (r *splitDartRenderer) line(format string, args ...any) {
	if len(args) == 0 {
		r.buffer.WriteString(format)
	} else {
		fmt.Fprintf(&r.buffer, format, args...)
	}
	r.buffer.WriteByte('\n')
}

func (r *splitDartRenderer) raw(value string) {
	r.buffer.WriteString(value)
	r.buffer.WriteByte('\n')
}

func (r *splitDartRenderer) dartDoc(docs, indent string) {
	if docs == "" {
		return
	}
	for line := range strings.SplitSeq(docs, "\n") {
		r.line("%s/// %s", indent, strings.ReplaceAll(line, "*/", "* /"))
	}
}

func (r *splitDartRenderer) renderDecoder(typ *wireType) error {
	r.line("%s fgbDecode%d(Object? value, __FGB_BRIDGE_CLASS__ bridge, String path) {", typ.DartType, typ.ID)
	switch typ.Kind {
	case kindBool:
		r.line("  if (value is! bool) throw FormatException('$path: expected bool');")
		r.line("  return value;")
	case kindString:
		r.line("  if (value is! String) throw FormatException('$path: expected String');")
		r.line("  return value;")
	case kindSigned, kindUnsigned:
		if strings.TrimSuffix(typ.DartType, "?") == "BigInt" {
			if strings.HasSuffix(typ.DartType, "?") {
				r.line("  if (value == null) return null;")
			}
			r.line("  if (value is BigInt) return value;")
			r.line("  if (value is String) return BigInt.parse(value, radix: 16);")
			r.line("  throw FormatException('$path: expected BigInt');")
		} else {
			r.line("  if (value is! int) throw FormatException('$path: expected int');")
			r.line("  return value;")
		}
	case kindFloat:
		r.line("  if (value is num) return value.toDouble();")
		r.line("  throw FormatException('$path: expected double');")
	case kindBigInt:
		if strings.HasSuffix(typ.DartType, "?") {
			r.line("  if (value == null) return null;")
		}
		r.line("  if (value is BigInt) return value;")
		r.line("  if (value is String) return BigInt.parse(value, radix: 16);")
		r.line("  throw FormatException('$path: expected BigInt');")
	case kindTime:
		r.line("  if (value is! String) throw FormatException('$path: expected RFC3339 String');")
		r.line("  return DateTime.parse(value);")
	case kindAny:
		r.line("  return value;")
	case kindPointer:
		r.line("  if (value == null) return null;")
		r.line("  return fgbDecode%d(value, bridge, path);", typ.Elem.ID)
	case kindBytes:
		r.line("  if (value is Uint8List) return value;")
		r.line("  if (value is List) return Uint8List.fromList(value.cast<int>());")
		r.line("  throw FormatException('$path: expected Uint8List');")
	case kindInt32List:
		r.line("  if (value is Int32List) return value;")
		r.line("  if (value is List) return Int32List.fromList(value.cast<int>());")
		r.line("  throw FormatException('$path: expected Int32List');")
	case kindInt64List:
		r.line("  if (value is Int64List) return value;")
		r.line("  if (value is List) return Int64List.fromList(value.cast<int>());")
		r.line("  throw FormatException('$path: expected Int64List');")
	case kindFloat64List:
		r.line("  if (value is Float64List) return value;")
		r.line("  if (value is List) return Float64List.fromList(value.cast<num>().map((item) => item.toDouble()).toList());")
		r.line("  throw FormatException('$path: expected Float64List');")
	case kindSlice, kindArray:
		r.line("  if (value is! List) throw FormatException('$path: expected List');")
		if typ.Kind == kindArray {
			r.line("  if (value.length != %d) throw FormatException('$path: expected %d elements');", typ.Length, typ.Length)
		}
		r.line("  return List<%s>.generate(value.length, (index) => fgbDecode%d(value[index], bridge, '$path[' + index.toString() + ']'), growable: false);", typ.Elem.DartType, typ.Elem.ID)
	case kindMap:
		r.line("  if (value is! Map) throw FormatException('$path: expected Map');")
		r.line("  final result = <%s, %s>{};", typ.Key.DartType, typ.Elem.DartType)
		r.line("  value.forEach((rawKey, rawValue) {")
		r.line("    final key = fgbDecode%d(rawKey, bridge, '$path.<key>');", typ.Key.ID)
		r.line("    final item = fgbDecode%d(rawValue, bridge, '$path[' + key.toString() + ']');", typ.Elem.ID)
		r.line("    result[key] = item;")
		r.line("  });")
		r.line("  return result;")
	case kindStruct:
		r.line("  if (value is Map) {")
		r.line("    return %s(", typ.Struct.DartName)
		for _, field := range typ.Struct.allFields() {
			source := fmt.Sprintf("value[%s]", strconv.Quote(field.WireName))
			r.line("      %s: %s,", field.DartName, dartFieldDecode(field, source, fmt.Sprintf("'$path.%s'", field.WireName)))
		}
		r.line("    );")
		r.line("  }")
		r.line("  if (value is List) {")
		r.line("    if (value.length != %d) throw FormatException('$path: expected %d fields');", len(typ.Struct.allFields()), len(typ.Struct.allFields()))
		r.line("    return %s(", typ.Struct.DartName)
		for index, field := range typ.Struct.allFields() {
			source := fmt.Sprintf("value[%d]", index)
			r.line("      %s: %s,", field.DartName, dartFieldDecode(field, source, fmt.Sprintf("'$path[%d]'", index)))
		}
		r.line("    );")
		r.line("  }")
		r.line("  throw FormatException('$path: expected Map or List');")
	case kindOpaque:
		r.line("  if (value == null) return null;")
		r.line("  if (value is! int || value <= 0) throw FormatException('$path: expected opaque handle');")
		r.line("  return %s.fgbInternal(fgbBridge: bridge, fgbHandle: value);", typ.Opaque.DartName)
	case kindDartOpaque:
		r.line("  if (value is! int) throw FormatException('$path: expected DartOpaque handle');")
		r.line("  return bridge.fgbInternalResolveDartOpaque(value, path);")
	case kindCallback:
		r.line("  throw UnsupportedError('$path: function values cannot travel from Go to Dart');")
	case kindStreamSink:
		r.line("  throw UnsupportedError('$path: stream sinks only travel from Dart to Go');")
	case kindInterface:
		// Nullability only exists in the Dart -> Go direction (//fgb:nullable),
		// so a value arriving from Go must be present.
		r.line("  if (value == null) throw FormatException('$path: Go returned a nil %s');", typ.Interface.GoName)
		r.line("  if (value is! List || value.length != 2) throw FormatException('$path: expected an interface envelope');")
		r.line("  switch (value[0]) {")
		for index, implementor := range typ.Interface.Implementors {
			r.line("    case %d:", index)
			r.line("      return fgbDecode%d(value[1], bridge, path);", implementor.Type.ID)
		}
		r.line("  }")
		r.line("  throw FormatException('$path: unknown %s implementation ${value[0]}');", typ.Interface.GoName)
	case kindNamed:
		r.line("  return %s(fgbDecode%d(value, bridge, path));", typ.Named.DartName, typ.Named.Underlying.ID)
	default:
		return fmt.Errorf("no Dart decoder for %s", typ.Kind)
	}
	r.line("}")
	return nil
}

func (r *splitDartRenderer) renderEncoder(typ *wireType) error {
	r.line("Object? fgbEncode%d(%s value, __FGB_BRIDGE_CLASS__ bridge, String path) {", typ.ID, dartEncoderValueType(typ))
	// Closures encode their own null case (as handle 0); every other nilable
	// type maps null straight through to a null wire value.
	if typ.Kind != kindCallback && typ.nilableWithoutPointer() {
		r.line("  if (value == null) return null;")
	}
	switch typ.Kind {
	case kindBool, kindString, kindSigned, kindFloat, kindAny:
		r.line("  return value;")
	case kindUnsigned, kindBigInt:
		if strings.TrimSuffix(typ.DartType, "?") == "BigInt" {
			if strings.HasSuffix(typ.DartType, "?") {
				r.line("  if (value == null) return null;")
			}
			r.line("  return value.toRadixString(16);")
		} else {
			r.line("  return value;")
		}
	case kindTime:
		r.line("  return value.toIso8601String();")
	case kindPointer:
		r.line("  if (value == null) return null;")
		r.line("  return fgbEncode%d(value, bridge, path);", typ.Elem.ID)
	case kindBytes, kindInt32List, kindInt64List, kindFloat64List:
		r.line("  return value;")
	case kindSlice, kindArray:
		r.line("  return value.map((item) => fgbEncode%d(item, bridge, path)).toList(growable: false);", typ.Elem.ID)
	case kindMap:
		r.line("  final result = <Object?, Object?>{};")
		r.line("  value.forEach((key, item) {")
		r.line("    result[fgbEncode%d(key, bridge, path)] = fgbEncode%d(item, bridge, path);", typ.Key.ID, typ.Elem.ID)
		r.line("  });")
		r.line("  return result;")
	case kindStruct:
		r.line("  return <Object?, Object?>{")
		for _, field := range typ.Struct.allFields() {
			r.line("    %s: fgbEncode%d(value.%s, bridge, path + %s),", strconv.Quote(field.WireName), field.Type.ID, field.DartName, strconv.Quote("."+field.WireName))
		}
		r.line("  };")
	case kindOpaque:
		r.line("  if (value == null) return null;")
		r.line("  if (!identical(value.fgbBridge, bridge)) throw StateError('opaque value belongs to a different bridge');")
		r.line("  return value.fgbHandle;")
	case kindDartOpaque:
		r.line("  return bridge.fgbInternalRegisterDartOpaque(value);")
	case kindStreamSink:
		r.renderStreamSinkRegistration(typ, "bridge")
	case kindInterface:
		// Most-derived first: a subclass also passes its superclass check.
		r.line("  if (value == null) return null;")
		for _, implementor := range sortedImplementors(typ.Interface) {
			r.line("  if (value is %s) return <Object?>[%d, fgbEncode%d(value, bridge, path)];", implementor.DartName, implementor.Index, implementor.Type.ID)
		}
		r.line("  throw ArgumentError('$path: ${value.runtimeType} is not a Go implementation of %s');", typ.Interface.DartName)
	case kindCallback:
		r.renderCallbackRegistration(typ, "bridge")
	case kindNamed:
		r.line("  return fgbEncode%d(value.value, bridge, path);", typ.Named.Underlying.ID)
	default:
		return fmt.Errorf("no Dart encoder for %s", typ.Kind)
	}
	r.line("}")
	return nil
}
