package generator

import (
	"bytes"
	"fmt"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	bridgemodel "github.com/star4277/flutter-go-bridge-gokit/internal/model"
)

type splitDartRenderer struct {
	unit   *unit
	buffer bytes.Buffer
}

type dartSourceGroup struct {
	Calls   []*callModel
	Structs []*structModel
	Opaques []*opaqueModel
	Named   []*namedModel
}

func dartResultType(call *callModel) string {
	if call == nil || call.Result == nil {
		return "void"
	}
	return call.Result.DartType
}

// dartParams renders the public API parameter list. Every generated Dart
// entrypoint uses named parameters; Go pointer parameters map to optional
// nullable ones, everything else is required.
func dartParams(call *callModel) string {
	if call == nil || len(call.Params) == 0 {
		return ""
	}
	params := make([]string, 0, len(call.Params))
	for _, param := range call.Params {
		if isPointerType(param.Type.Original) {
			params = append(params, fmt.Sprintf("%s %s", param.Type.DartType, param.DartName))
		} else {
			params = append(params, fmt.Sprintf("required %s %s", param.Type.DartType, param.DartName))
		}
	}
	return "{" + strings.Join(params, ", ") + "}"
}

func isAsyncCall(call *callModel) bool {
	return call != nil && call.Mode == bridgemodel.CallModeAsync
}

func renderDartSplit(unit *unit, configuredOutput string) (map[string][]byte, error) {
	root, central := dartOutputPaths(configuredOutput)
	groups, paths := dartSourceGroups(unit)
	orderedKeys := sortedSourceKeys(paths)
	result := map[string][]byte{}

	centralRenderer := &splitDartRenderer{unit: unit}
	centralRenderer.line("// Code generated by flutter_go_bridge_codegen. DO NOT EDIT.")
	centralRenderer.line("// ignore_for_file: unused_element, unused_import, unnecessary_import")
	centralRenderer.line("library flutter_go_bridge;")
	centralRenderer.line("import 'dart:async';")
	centralRenderer.line("import 'dart:convert';")
	centralRenderer.line("import 'dart:ffi' as ffi;")
	centralRenderer.line("import 'dart:io';")
	centralRenderer.line("import 'dart:isolate';")
	centralRenderer.line("import 'dart:typed_data';")
	for _, key := range orderedKeys {
		relative := paths[key]
		centralRenderer.line("import %s;", strconv.Quote(filepath.ToSlash(relative)))
	}
	centralRenderer.line("")
	if unit.DartPreamble != "" {
		centralRenderer.raw(strings.TrimRight(unit.DartPreamble, "\n"))
		centralRenderer.line("")
	}
	if hasCstDcoCalls(unit) {
		centralRenderer.raw(cstDartDefinitions(unit))
		centralRenderer.line("")
	}
	runtime := strings.ReplaceAll(dartRuntimeSource, "__FGB_LIBRARY_NAME__", strconv.Quote(unit.LibraryName))
	runtime = strings.ReplaceAll(runtime, "__FGB_BRIDGE_CLASS__", unit.ClassName)
	centralRenderer.raw(runtime)
	for _, typ := range unit.Types {
		if err := centralRenderer.renderDecoder(typ); err != nil {
			return nil, err
		}
		centralRenderer.line("")
		if err := centralRenderer.renderEncoder(typ); err != nil {
			return nil, err
		}
		centralRenderer.line("")
	}
	if hasCstDcoCalls(unit) {
		centralRenderer.renderCstEncoders()
	}
	centralRenderer.renderCentralCallMethods()
	result[central] = []byte(strings.ReplaceAll(centralRenderer.buffer.String(), "__FGB_BRIDGE_CLASS__", unit.ClassName))

	for _, key := range orderedKeys {
		relative := paths[key]
		sourcePath := filepath.Join(root, filepath.FromSlash(relative))
		if samePath(sourcePath, central) {
			return nil, fmt.Errorf("Dart source %s collides with bridge output %s; choose a different dart_output", relative, central)
		}
		centralImport := dartImportPath(sourcePath, central)
		renderer := &splitDartRenderer{unit: unit}
		renderer.line("// Code generated by flutter_go_bridge_codegen. DO NOT EDIT.")
		renderer.line("// ignore_for_file: unused_element, unused_import, unnecessary_import")
		renderer.line("import %s;", centralImport)
		renderer.line("import 'dart:typed_data';")
		renderer.line("")
		group := groups[key]
		for _, structure := range group.Structs {
			renderer.renderStruct(structure)
		}
		for _, opaque := range group.Opaques {
			renderer.renderOpaque(opaque)
		}
		for _, named := range group.Named {
			renderer.renderNamed(named)
		}
		for _, call := range group.Calls {
			renderer.renderTopCall(call)
		}
		result[sourcePath] = []byte(strings.ReplaceAll(renderer.buffer.String(), "__FGB_BRIDGE_CLASS__", unit.ClassName))
	}
	return result, nil
}

func sortedSourceKeys(paths map[string]string) []string {
	keys := make([]string, 0, len(paths))
	for key := range paths {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func dartImportPath(fromFile, targetFile string) string {
	relative, err := filepath.Rel(filepath.Dir(fromFile), targetFile)
	if err != nil || relative == "." {
		relative = filepath.Base(targetFile)
	}
	return strconv.Quote(filepath.ToSlash(relative))
}

func dartOutputPaths(configured string) (root, central string) {
	if strings.EqualFold(filepath.Ext(configured), ".dart") {
		return filepath.Dir(configured), configured
	}
	return configured, filepath.Join(configured, "bridge_generated.dart")
}

func dartSourceGroups(unit *unit) (map[string]*dartSourceGroup, map[string]string) {
	groups := map[string]*dartSourceGroup{}
	paths := map[string]string{}
	ensure := func(source string) string {
		key := cleanSourcePath(source)
		if key == "" {
			key = "<generated>"
		}
		if _, ok := groups[key]; !ok {
			groups[key] = &dartSourceGroup{}
		}
		if _, ok := paths[key]; !ok {
			if key == "<generated>" {
				paths[key] = "_generated.dart"
			} else {
				paths[key] = sourceDartPath(unit.InputDir, source)
			}
		}
		return key
	}
	for _, source := range unit.SourceFiles {
		ensure(source)
	}
	for _, structure := range unit.Structs {
		ensure(structure.SourceFile)
		groups[cleanOrGenerated(structure.SourceFile)].Structs = append(groups[cleanOrGenerated(structure.SourceFile)].Structs, structure)
	}
	for _, opaque := range unit.Opaques {
		ensure(opaque.SourceFile)
		groups[cleanOrGenerated(opaque.SourceFile)].Opaques = append(groups[cleanOrGenerated(opaque.SourceFile)].Opaques, opaque)
	}
	for _, named := range unit.Named {
		ensure(named.SourceFile)
		groups[cleanOrGenerated(named.SourceFile)].Named = append(groups[cleanOrGenerated(named.SourceFile)].Named, named)
	}
	for _, call := range unit.TopCalls {
		key := ensure(call.SourceFile)
		groups[key].Calls = append(groups[key].Calls, call)
	}
	if len(paths) == 0 {
		paths["<generated>"] = "_generated.dart"
		groups["<generated>"] = &dartSourceGroup{}
	}
	return groups, paths
}

func cleanOrGenerated(source string) string {
	if source == "" {
		return "<generated>"
	}
	return cleanSourcePath(source)
}

func cleanSourcePath(value string) string {
	if value == "" {
		return ""
	}
	abs, err := filepath.Abs(value)
	if err != nil {
		return filepath.Clean(value)
	}
	return filepath.Clean(abs)
}

func sourceDartPath(inputDir, source string) string {
	relative, err := filepath.Rel(inputDir, source)
	if err != nil || relative == "." || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
		relative = filepath.Base(source)
	}
	relative = strings.TrimSuffix(relative, filepath.Ext(relative)) + ".dart"
	// Mirror the Go input tree directly below the Dart output root. For
	// example, api/foo.go becomes api/foo.dart; there is no synthetic wrapper
	// directory.
	return filepath.ToSlash(relative)
}

func (r *splitDartRenderer) renderTopCall(call *callModel) {
	resultType := dartResultType(call)
	params := dartParams(call)
	args := make([]string, len(call.Params))
	for index, param := range call.Params {
		args[index] = param.DartName
	}
	invocation := fmt.Sprintf("bridge.fgbInternalCall%d(%s)", call.ID, strings.Join(args, ", "))
	r.dartDoc(call.Docs, "")
	if isAsyncCall(call) {
		r.line("Future<%s> %s(%s) async {", resultType, call.DartName, params)
		r.line("  final bridge = __FGB_BRIDGE_CLASS__.instance;")
		if call.Result == nil {
			r.line("  await %s;", invocation)
		} else {
			r.line("  return await %s;", invocation)
		}
	} else {
		r.line("%s %s(%s) {", resultType, call.DartName, params)
		r.line("  final bridge = __FGB_BRIDGE_CLASS__.instance;")
		if call.Result == nil {
			r.line("  %s;", invocation)
		} else {
			r.line("  return %s;", invocation)
		}
	}
	r.line("}")
	r.line("")
}

func (r *splitDartRenderer) renderStruct(structure *structModel) {
	r.dartDoc(structure.Docs, "")
	r.line("final class %s {", structure.DartName)
	for _, field := range structure.Fields {
		if field.NonFinal {
			r.line("  %s %s;", field.Type.DartType, field.DartName)
		} else {
			r.line("  final %s %s;", field.Type.DartType, field.DartName)
		}
	}
	r.line("")
	constructorKeyword := "const "
	for _, field := range structure.Fields {
		if field.NonFinal {
			constructorKeyword = ""
			break
		}
	}
	r.line("  %s%s({", constructorKeyword, structure.DartName)
	for _, field := range structure.Fields {
		switch {
		case field.DefaultValue != "":
			r.line("    this.%s = %s,", field.DartName, field.DefaultValue)
		case field.Optional:
			r.line("    this.%s,", field.DartName)
		default:
			r.line("    required this.%s,", field.DartName)
		}
	}
	r.line("  });")
	for _, call := range structure.Methods {
		r.line("")
		r.renderInstanceCall(call, "this", "__FGB_BRIDGE_CLASS__.instance", true, "  ")
	}
	r.line("}")
	r.line("")
}

func (r *splitDartRenderer) renderOpaque(opaque *opaqueModel) {
	r.dartDoc(opaque.Docs, "")
	r.line("final class %s extends GoOpaque {", opaque.DartName)
	r.line("  %s.fgbInternal({required super.fgbBridge, required super.fgbHandle});", opaque.DartName)
	for _, call := range opaque.Methods {
		r.line("")
		r.renderInstanceCall(call, "this", "fgbBridge", false, "  ")
	}
	r.line("}")
	r.line("")
}

func (r *splitDartRenderer) renderNamed(named *namedModel) {
	r.dartDoc(named.Docs, "")
	if named.Underlying == nil || named.Underlying.Kind == kindOpaque {
		return
	}
	r.line("extension type const %s(%s value) {", named.DartName, named.Underlying.DartType)
	for _, item := range named.Constants {
		if item.IsConst {
			r.line("  static const %s = %s(%s);", item.DartName, named.DartName, item.DartLiteral)
		} else {
			r.line("  static final %s = %s(%s);", item.DartName, named.DartName, item.DartLiteral)
		}
	}
	for _, call := range named.Methods {
		r.line("")
		r.renderInstanceCall(call, "this", "__FGB_BRIDGE_CLASS__.instance", true, "  ")
	}
	r.line("}")
	r.line("")
}

func (r *splitDartRenderer) renderInstanceCall(call *callModel, receiver, bridge string, valueReceiver bool, indent string) {
	resultType := dartResultType(call)
	params := dartParams(call)
	args := []string{receiver}
	for _, param := range call.Params {
		args = append(args, param.DartName)
	}
	invocation := fmt.Sprintf("%s.fgbInternalCall%d(%s)", bridge, call.ID, strings.Join(args, ", "))
	if valueReceiver {
		// Value objects do not retain a bridge; the generated API uses the
		// process-wide bridge singleton just like top-level functions.
		bridge = "__FGB_BRIDGE_CLASS__.instance"
	}
	r.dartDoc(call.Docs, indent)
	if isAsyncCall(call) {
		r.line("%sFuture<%s> %s(%s) async {", indent, resultType, call.DartName, params)
		if call.Result == nil {
			r.line("%s  await %s;", indent, invocation)
		} else {
			r.line("%s  return await %s;", indent, invocation)
		}
	} else {
		r.line("%s%s %s(%s) {", indent, resultType, call.DartName, params)
		if call.Result == nil {
			r.line("%s  %s;", indent, invocation)
		} else {
			r.line("%s  return %s;", indent, invocation)
		}
	}
	r.line("%s}", indent)
}

func (r *splitDartRenderer) line(format string, args ...any) {
	if len(args) == 0 {
		r.buffer.WriteString(format)
	} else {
		fmt.Fprintf(&r.buffer, format, args...)
	}
	r.buffer.WriteByte('\n')
}

func (r *splitDartRenderer) raw(value string) {
	r.buffer.WriteString(value)
	r.buffer.WriteByte('\n')
}

func (r *splitDartRenderer) dartDoc(docs, indent string) {
	if docs == "" {
		return
	}
	for line := range strings.SplitSeq(docs, "\n") {
		r.line("%s/// %s", indent, strings.ReplaceAll(line, "*/", "* /"))
	}
}

func (r *splitDartRenderer) renderDecoder(typ *wireType) error {
	r.line("%s fgbDecode%d(Object? value, __FGB_BRIDGE_CLASS__ bridge, String path) {", typ.DartType, typ.ID)
	switch typ.Kind {
	case kindBool:
		r.line("  if (value is! bool) throw FormatException('$path: expected bool');")
		r.line("  return value;")
	case kindString:
		r.line("  if (value is! String) throw FormatException('$path: expected String');")
		r.line("  return value;")
	case kindSigned, kindUnsigned:
		if strings.TrimSuffix(typ.DartType, "?") == "BigInt" {
			if strings.HasSuffix(typ.DartType, "?") {
				r.line("  if (value == null) return null;")
			}
			r.line("  if (value is BigInt) return value;")
			r.line("  if (value is String) return BigInt.parse(value, radix: 16);")
			r.line("  throw FormatException('$path: expected BigInt');")
		} else {
			r.line("  if (value is! int) throw FormatException('$path: expected int');")
			r.line("  return value;")
		}
	case kindFloat:
		r.line("  if (value is num) return value.toDouble();")
		r.line("  throw FormatException('$path: expected double');")
	case kindBigInt:
		if strings.HasSuffix(typ.DartType, "?") {
			r.line("  if (value == null) return null;")
		}
		r.line("  if (value is BigInt) return value;")
		r.line("  if (value is String) return BigInt.parse(value, radix: 16);")
		r.line("  throw FormatException('$path: expected BigInt');")
	case kindTime:
		r.line("  if (value is! String) throw FormatException('$path: expected RFC3339 String');")
		r.line("  return DateTime.parse(value);")
	case kindAny:
		r.line("  return value;")
	case kindPointer:
		r.line("  if (value == null) return null;")
		r.line("  return fgbDecode%d(value, bridge, path);", typ.Elem.ID)
	case kindBytes:
		r.line("  if (value is Uint8List) return value;")
		r.line("  if (value is List) return Uint8List.fromList(value.cast<int>());")
		r.line("  throw FormatException('$path: expected Uint8List');")
	case kindInt32List:
		r.line("  if (value is Int32List) return value;")
		r.line("  if (value is List) return Int32List.fromList(value.cast<int>());")
		r.line("  throw FormatException('$path: expected Int32List');")
	case kindInt64List:
		r.line("  if (value is Int64List) return value;")
		r.line("  if (value is List) return Int64List.fromList(value.cast<int>());")
		r.line("  throw FormatException('$path: expected Int64List');")
	case kindFloat64List:
		r.line("  if (value is Float64List) return value;")
		r.line("  if (value is List) return Float64List.fromList(value.cast<num>().map((item) => item.toDouble()).toList());")
		r.line("  throw FormatException('$path: expected Float64List');")
	case kindSlice, kindArray:
		r.line("  if (value is! List) throw FormatException('$path: expected List');")
		if typ.Kind == kindArray {
			r.line("  if (value.length != %d) throw FormatException('$path: expected %d elements');", typ.Length, typ.Length)
		}
		r.line("  return List<%s>.generate(value.length, (index) => fgbDecode%d(value[index], bridge, '$path[' + index.toString() + ']'), growable: false);", typ.Elem.DartType, typ.Elem.ID)
	case kindMap:
		r.line("  if (value is! Map) throw FormatException('$path: expected Map');")
		r.line("  final result = <%s, %s>{};", typ.Key.DartType, typ.Elem.DartType)
		r.line("  value.forEach((rawKey, rawValue) {")
		r.line("    final key = fgbDecode%d(rawKey, bridge, '$path.<key>');", typ.Key.ID)
		r.line("    final item = fgbDecode%d(rawValue, bridge, '$path[' + key.toString() + ']');", typ.Elem.ID)
		r.line("    result[key] = item;")
		r.line("  });")
		r.line("  return result;")
	case kindStruct:
		r.line("  if (value is Map) {")
		r.line("    return %s(", typ.Struct.DartName)
		for _, field := range typ.Struct.Fields {
			r.line("      %s: fgbDecode%d(value[%s], bridge, '$path.%s'),", field.DartName, field.Type.ID, strconv.Quote(field.WireName), field.WireName)
		}
		r.line("    );")
		r.line("  }")
		r.line("  if (value is List) {")
		r.line("    if (value.length != %d) throw FormatException('$path: expected %d fields');", len(typ.Struct.Fields), len(typ.Struct.Fields))
		r.line("    return %s(", typ.Struct.DartName)
		for index, field := range typ.Struct.Fields {
			r.line("      %s: fgbDecode%d(value[%d], bridge, '$path[%d]'),", field.DartName, field.Type.ID, index, index)
		}
		r.line("    );")
		r.line("  }")
		r.line("  throw FormatException('$path: expected Map or List');")
	case kindOpaque:
		r.line("  if (value == null) return null;")
		r.line("  if (value is! int || value <= 0) throw FormatException('$path: expected opaque handle');")
		r.line("  return %s.fgbInternal(fgbBridge: bridge, fgbHandle: value);", typ.Opaque.DartName)
	case kindDartOpaque:
		r.line("  if (value is! int) throw FormatException('$path: expected DartOpaque handle');")
		r.line("  return bridge.fgbInternalResolveDartOpaque(value, path);")
	case kindNamed:
		r.line("  return %s(fgbDecode%d(value, bridge, path));", typ.Named.DartName, typ.Named.Underlying.ID)
	default:
		return fmt.Errorf("no Dart decoder for %s", typ.Kind)
	}
	r.line("}")
	return nil
}

func (r *splitDartRenderer) renderEncoder(typ *wireType) error {
	r.line("Object? fgbEncode%d(%s value, __FGB_BRIDGE_CLASS__ bridge, String path) {", typ.ID, typ.DartType)
	switch typ.Kind {
	case kindBool, kindString, kindSigned, kindFloat, kindAny:
		r.line("  return value;")
	case kindUnsigned, kindBigInt:
		if strings.TrimSuffix(typ.DartType, "?") == "BigInt" {
			if strings.HasSuffix(typ.DartType, "?") {
				r.line("  if (value == null) return null;")
			}
			r.line("  return value.toRadixString(16);")
		} else {
			r.line("  return value;")
		}
	case kindTime:
		r.line("  return value.toIso8601String();")
	case kindPointer:
		r.line("  if (value == null) return null;")
		r.line("  return fgbEncode%d(value, bridge, path);", typ.Elem.ID)
	case kindBytes, kindInt32List, kindInt64List, kindFloat64List:
		r.line("  return value;")
	case kindSlice, kindArray:
		r.line("  return value.map((item) => fgbEncode%d(item, bridge, path)).toList(growable: false);", typ.Elem.ID)
	case kindMap:
		r.line("  final result = <Object?, Object?>{};")
		r.line("  value.forEach((key, item) {")
		r.line("    result[fgbEncode%d(key, bridge, path)] = fgbEncode%d(item, bridge, path);", typ.Key.ID, typ.Elem.ID)
		r.line("  });")
		r.line("  return result;")
	case kindStruct:
		r.line("  return <Object?, Object?>{")
		for _, field := range typ.Struct.Fields {
			r.line("    %s: fgbEncode%d(value.%s, bridge, path + %s),", strconv.Quote(field.WireName), field.Type.ID, field.DartName, strconv.Quote("."+field.WireName))
		}
		r.line("  };")
	case kindOpaque:
		r.line("  if (value == null) return null;")
		r.line("  if (!identical(value.fgbBridge, bridge)) throw StateError('opaque value belongs to a different bridge');")
		r.line("  return value.fgbHandle;")
	case kindDartOpaque:
		r.line("  return bridge.fgbInternalRegisterDartOpaque(value);")
	case kindNamed:
		r.line("  return fgbEncode%d(value.value, bridge, path);", typ.Named.Underlying.ID)
	default:
		return fmt.Errorf("no Dart encoder for %s", typ.Kind)
	}
	r.line("}")
	return nil
}
