package generator

import (
	"bytes"
	"fmt"
	"go/types"
	"strconv"
	"strings"
)

type goRenderer struct {
	unit   *unit
	buffer bytes.Buffer
}

func renderGo(unit *unit) ([]byte, error) {
	r := &goRenderer{unit: unit}
	if unit.GoPreamble != "" {
		r.raw(strings.TrimRight(unit.GoPreamble, "\n"))
		r.line("")
	}
	r.line("// Code generated by flutter_go_bridge_codegen. DO NOT EDIT.")
	r.line("package main")
	r.line("")
	r.line("/*")
	cgoPreamble := strings.TrimSpace(goCgoPreambleSource)
	if hasCstDcoCalls(unit) {
		cgoPreamble += "\n\n" + cstForwardDeclarations(unit)
	}
	r.raw(cgoPreamble)
	r.line("*/")
	r.line(`import "C"`)
	r.line("")
	r.line("import (")
	imports := []string{
		"bytes", "encoding/binary", "fmt", "io", "math/big", "reflect",
		"runtime", "runtime/debug", "sync", "sync/atomic", "unsafe",
	}
	if unit.UsesTime {
		imports = append(imports, "time")
	}
	for _, item := range imports {
		r.line("\t%q", item)
	}
	if unit.UsesDartOpaque {
		// The exported ABI already owns the identifier `fgb` (the sync
		// entrypoint), so the runtime package needs an alias.
		r.line("\tfgbrt %q", dartOpaquePackagePath)
	}
	if !unit.Direct {
		r.line("\tapi %q", unit.PackagePath)
	}
	r.line(")")
	r.line("")
	r.raw(strings.TrimSpace(goRuntimeSource))
	r.line("")
	if unit.NeedsMain {
		r.line("// Required for c-shared and c-archive build modes.")
		r.line("func main() {}")
		r.line("")
	}
	if hasCstDcoCalls(unit) {
		r.renderCstDecoders()
		r.renderDcoEncoders()
	}

	for _, typ := range unit.Types {
		if err := r.renderDecoder(typ); err != nil {
			return nil, err
		}
		r.line("")
		if err := r.renderEncoder(typ); err != nil {
			return nil, err
		}
		r.line("")
	}
	r.renderDispatch()
	// Keep the CST ABI present even for a package whose current API only uses
	// the Standard fallback; the Dart runtime can then use one stable binding
	// layout and future regenerated calls do not change symbol discovery.
	r.renderCstDispatch()
	return r.buffer.Bytes(), nil
}

func (r *goRenderer) renderDecoder(typ *wireType) error {
	goType := r.goType(typ.Original)
	r.line("func fgbDecode%d(value any, path string) (%s, error) {", typ.ID, goType)
	switch typ.Kind {
	case kindBool:
		r.line("\tresult, ok := value.(bool)")
		r.line("\tif !ok { return false, fgbTypeError(path, \"bool\", value) }")
		r.line("\treturn result, nil")
	case kindString:
		r.line("\tresult, ok := value.(string)")
		r.line("\tif !ok { return \"\", fgbTypeError(path, \"string\", value) }")
		r.line("\treturn result, nil")
	case kindSigned:
		r.line("\traw, err := fgbAsInt64(value, path)")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.renderSignedRangeCheck(typ, goType)
		r.line("\treturn %s(raw), nil", goType)
	case kindUnsigned:
		r.line("\traw, err := fgbAsUint64(value, path)")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.renderUnsignedRangeCheck(typ, goType)
		r.line("\treturn %s(raw), nil", goType)
	case kindFloat:
		r.line("\traw, err := fgbAsFloat64(value, path)")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.line("\treturn %s(raw), nil", goType)
	case kindBigInt:
		r.renderBigIntDecoder(typ, goType)
	case kindTime:
		r.line("\traw, ok := value.(string)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"RFC3339 string\", value) }", goType)
		r.line("\tresult, err := time.Parse(time.RFC3339Nano, raw)")
		r.line("\tif err != nil { var zero %s; return zero, fmt.Errorf(\"%%s: invalid time: %%w\", path, err) }", goType)
		r.line("\treturn result, nil")
	case kindAny:
		r.line("\treturn value, nil")
	case kindPointer:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\tdecoded, err := fgbDecode%d(value, path)", typ.Elem.ID)
		r.line("\tif err != nil { return nil, err }")
		r.line("\treturn &decoded, nil")
	case kindBytes:
		r.line("\traw, ok := value.([]byte)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"Uint8List\", value) }", goType)
		r.line("\treturn append(%s(nil), raw...), nil", goType)
	case kindInt32List:
		r.line("\traw, ok := value.([]int32)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"Int32List\", value) }", goType)
		r.line("\treturn append(%s(nil), raw...), nil", goType)
	case kindInt64List:
		r.line("\traw, ok := value.([]int64)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"Int64List\", value) }", goType)
		r.line("\treturn append(%s(nil), raw...), nil", goType)
	case kindFloat64List:
		r.line("\traw, ok := value.([]float64)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"Float64List\", value) }", goType)
		r.line("\treturn append(%s(nil), raw...), nil", goType)
	case kindSlice:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\traw, ok := value.([]any)")
		r.line("\tif !ok { return nil, fgbTypeError(path, \"List\", value) }")
		r.line("\tresult := make(%s, len(raw))", goType)
		r.line("\tfor index, item := range raw {")
		r.line("\t\tdecoded, err := fgbDecode%d(item, fmt.Sprintf(\"%%s[%%d]\", path, index))", typ.Elem.ID)
		r.line("\t\tif err != nil { return nil, err }")
		r.line("\t\tresult[index] = decoded")
		r.line("\t}")
		r.line("\treturn result, nil")
	case kindArray:
		r.line("\traw, ok := value.([]any)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"List\", value) }", goType)
		r.line("\tif len(raw) != %d { var zero %s; return zero, fmt.Errorf(\"%%s: expected %d elements, got %%d\", path, len(raw)) }", typ.Length, goType, typ.Length)
		r.line("\tvar result %s", goType)
		r.line("\tfor index, item := range raw {")
		r.line("\t\tdecoded, err := fgbDecode%d(item, fmt.Sprintf(\"%%s[%%d]\", path, index))", typ.Elem.ID)
		r.line("\t\tif err != nil { var zero %s; return zero, err }", goType)
		r.line("\t\tresult[index] = decoded")
		r.line("\t}")
		r.line("\treturn result, nil")
	case kindMap:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\traw, ok := value.(map[any]any)")
		r.line("\tif !ok { return nil, fgbTypeError(path, \"Map\", value) }")
		r.line("\tresult := make(%s, len(raw))", goType)
		r.line("\tfor rawKey, rawValue := range raw {")
		r.line("\t\tkey, err := fgbDecode%d(rawKey, path+\".<key>\")", typ.Key.ID)
		r.line("\t\tif err != nil { return nil, err }")
		r.line("\t\tdecoded, err := fgbDecode%d(rawValue, fmt.Sprintf(\"%%s[%%v]\", path, key))", typ.Elem.ID)
		r.line("\t\tif err != nil { return nil, err }")
		r.line("\t\tresult[key] = decoded")
		r.line("\t}")
		r.line("\treturn result, nil")
	case kindStruct:
		r.line("\traw, ok := value.(map[any]any)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"Map\", value) }", goType)
		r.line("\tvar result %s", goType)
		for _, field := range typ.Struct.Fields {
			r.line("\tdecoded%s, err := fgbDecode%d(raw[%s], path+%s)", field.GoName, field.Type.ID, strconv.Quote(field.WireName), strconv.Quote("."+field.WireName))
			r.line("\tif err != nil { var zero %s; return zero, err }", goType)
			r.line("\tresult.%s = decoded%s", field.GoName, field.GoName)
		}
		r.line("\treturn result, nil")
	case kindOpaque:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\thandle, err := fgbAsHandle(value, path)")
		r.line("\tif err != nil { return nil, err }")
		r.line("\traw, ok := fgbHandles.Load(handle)")
		r.raw("\tif !ok { return nil, fmt.Errorf(\"%s: unknown or released handle %d\", path, handle) }")
		r.line("\tresult, ok := raw.(%s)", goType)
		r.raw("\tif !ok { return nil, fmt.Errorf(\"%s: handle %d has incompatible Go type %T\", path, handle, raw) }")
		r.line("\treturn result, nil")
	case kindDartOpaque:
		r.line("\traw, err := fgbAsInt64(value, path)")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.line("\tif raw == 0 { var zero %s; return zero, fmt.Errorf(\"%%s: invalid DartOpaque handle 0\", path) }", goType)
		r.line("\treturn fgbrt.NewDartOpaque(raw, fgbReleaseDartOpaque), nil")
	case kindNamed:
		r.line("\tdecoded, err := fgbDecode%d(value, path)", typ.Named.Underlying.ID)
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.line("\treturn %s(decoded), nil", goType)
	default:
		return fmt.Errorf("no Go decoder for %s", typ.Kind)
	}
	r.line("}")
	return nil
}

func (r *goRenderer) renderEncoder(typ *wireType) error {
	goType := r.goType(typ.Original)
	r.line("func fgbEncode%d(value %s) (any, error) {", typ.ID, goType)
	switch typ.Kind {
	case kindBool, kindString:
		r.line("\treturn value, nil")
	case kindSigned:
		if typ.BitSize <= 32 && typ.BasicKind != types.Int {
			r.line("\treturn int32(value), nil")
		} else {
			r.line("\treturn int64(value), nil")
		}
	case kindUnsigned:
		if typ.DartType == "BigInt" {
			r.line("\treturn new(big.Int).SetUint64(uint64(value)), nil")
		} else if typ.BitSize <= 16 {
			r.line("\treturn int32(value), nil")
		} else {
			r.line("\treturn int64(value), nil")
		}
	case kindFloat:
		r.line("\treturn float64(value), nil")
	case kindBigInt:
		r.renderBigIntEncoder(typ)
	case kindTime:
		r.line("\treturn value.Format(time.RFC3339Nano), nil")
	case kindAny:
		r.line("\treturn fgbNormalize(value, 0)")
	case kindPointer:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\treturn fgbEncode%d(*value)", typ.Elem.ID)
	case kindBytes, kindInt32List, kindInt64List, kindFloat64List:
		r.line("\tif value == nil { return %s{}, nil }", goType)
		r.line("\treturn value, nil")
	case kindSlice:
		r.line("\tif value == nil { return []any{}, nil }")
		r.line("\tresult := make([]any, len(value))")
		r.line("\tfor index, item := range value {")
		r.line("\t\tencoded, err := fgbEncode%d(item)", typ.Elem.ID)
		r.raw("\t\tif err != nil { return nil, fmt.Errorf(\"element %d: %w\", index, err) }")
		r.line("\t\tresult[index] = encoded")
		r.line("\t}")
		r.line("\treturn result, nil")
	case kindArray:
		r.line("\tresult := make([]any, len(value))")
		r.line("\tfor index, item := range value {")
		r.line("\t\tencoded, err := fgbEncode%d(item)", typ.Elem.ID)
		r.raw("\t\tif err != nil { return nil, fmt.Errorf(\"element %d: %w\", index, err) }")
		r.line("\t\tresult[index] = encoded")
		r.line("\t}")
		r.line("\treturn result, nil")
	case kindMap:
		r.line("\tif value == nil { return map[any]any{}, nil }")
		r.line("\tresult := make(map[any]any, len(value))")
		r.line("\tfor key, item := range value {")
		r.line("\t\tencodedKey, err := fgbEncode%d(key)", typ.Key.ID)
		r.raw("\t\tif err != nil { return nil, fmt.Errorf(\"map key: %w\", err) }")
		r.line("\t\tencoded, err := fgbEncode%d(item)", typ.Elem.ID)
		r.raw("\t\tif err != nil { return nil, fmt.Errorf(\"map value: %w\", err) }")
		r.line("\t\tresult[encodedKey] = encoded")
		r.line("\t}")
		r.line("\treturn result, nil")
	case kindStruct:
		r.line("\tresult := make(map[any]any, %d)", len(typ.Struct.Fields))
		for _, field := range typ.Struct.Fields {
			r.line("\tencoded%s, err := fgbEncode%d(value.%s)", field.GoName, field.Type.ID, field.GoName)
			r.line("\tif err != nil { return nil, fmt.Errorf(%s+\": %%w\", err) }", strconv.Quote(field.WireName))
			r.line("\tresult[%s] = encoded%s", strconv.Quote(field.WireName), field.GoName)
		}
		r.line("\treturn result, nil")
	case kindOpaque:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\thandle := fgbNextHandle.Add(1)")
		r.line("\tif handle == 0 { return nil, fmt.Errorf(\"opaque handle space exhausted\") }")
		r.line("\tfgbHandles.Store(handle, value)")
		r.line("\treturn int64(handle), nil")
	case kindDartOpaque:
		r.line("\tif !value.IsValid() { return nil, fmt.Errorf(\"cannot encode an invalid DartOpaque\") }")
		r.line("\treturn value.Handle(), nil")
	case kindNamed:
		underlyingGo := r.goType(typ.Named.Underlying.Original)
		r.line("\treturn fgbEncode%d(%s(value))", typ.Named.Underlying.ID, underlyingGo)
	default:
		return fmt.Errorf("no Go encoder for %s", typ.Kind)
	}
	r.line("}")
	return nil
}

func (r *goRenderer) renderDispatch() {
	r.line("func fgbDispatch(call fgbMethodCall) (any, *fgbCallError) {")
	r.line("\tswitch call.Method {")
	for _, call := range r.unit.Calls {
		r.line("\tcase %s:", strconv.Quote(call.WireName))
		argumentCount := len(call.Params)
		if call.Receiver != nil {
			argumentCount++
		}
		if argumentCount == 0 {
			r.line("\t\tif _, err := fgbRequireArgs(call.Arguments, 0); err != nil { return nil, fgbInvalidArguments(call.Method, err) }")
		} else {
			r.line("\t\targs, err := fgbRequireArgs(call.Arguments, %d)", argumentCount)
			r.line("\t\tif err != nil { return nil, fgbInvalidArguments(call.Method, err) }")
		}
		argOffset := 0
		if call.Receiver != nil {
			r.line("\t\treceiver, err := fgbDecode%d(args[0], \"receiver\")", call.Receiver.ID)
			r.line("\t\tif err != nil { return nil, fgbInvalidArguments(call.Method, err) }")
			argOffset = 1
		}
		for index, param := range call.Params {
			r.line("\t\targ%d, err := fgbDecode%d(args[%d], %s)", index, param.Type.ID, index+argOffset, strconv.Quote(param.DartName))
			r.line("\t\tif err != nil { return nil, fgbInvalidArguments(call.Method, err) }")
		}
		callExpr := r.goCallExpression(call)
		switch {
		case call.Result != nil && call.HasError:
			r.line("\t\tresult, goErr := %s", callExpr)
			r.line("\t\tif goErr != nil { return nil, fgbGoError(call.Method, goErr) }")
		case call.Result != nil:
			r.line("\t\tresult := %s", callExpr)
		case call.HasError:
			r.line("\t\tgoErr := %s", callExpr)
			r.line("\t\tif goErr != nil { return nil, fgbGoError(call.Method, goErr) }")
		default:
			r.line("\t\t%s", callExpr)
		}
		if call.Result != nil {
			r.line("\t\tencoded, err := fgbEncode%d(result)", call.Result.ID)
			r.line("\t\tif err != nil { return nil, &fgbCallError{Code: \"encode_error\", Message: err.Error(), Details: map[any]any{\"method\": call.Method}} }")
			r.line("\t\treturn encoded, nil")
		} else {
			r.line("\t\treturn nil, nil")
		}
	}
	r.line("\tdefault:")
	r.raw("\t\treturn nil, &fgbCallError{Code: \"method_not_found\", Message: fmt.Sprintf(\"unknown method %q\", call.Method)}")
	r.line("\t}")
	r.line("}")
}

func (r *goRenderer) goCallExpression(call *callModel) string {
	var target string
	if call.Receiver == nil {
		target = call.GoTarget
	} else {
		target = "receiver." + call.GoTarget
	}
	args := make([]string, len(call.Params))
	for index := range call.Params {
		args[index] = fmt.Sprintf("arg%d", index)
	}
	return target + "(" + strings.Join(args, ", ") + ")"
}

func (r *goRenderer) renderSignedRangeCheck(typ *wireType, goType string) {
	switch typ.BasicKind {
	case types.Int8:
		r.line("\tif raw < -128 || raw > 127 { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of int8 range\", path) }", goType)
	case types.Int16:
		r.line("\tif raw < -32768 || raw > 32767 { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of int16 range\", path) }", goType)
	case types.Int32:
		r.line("\tif raw < -2147483648 || raw > 2147483647 { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of int32 range\", path) }", goType)
	case types.Int:
		r.line("\tif int64(int(raw)) != raw { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of int range\", path) }", goType)
	}
}

func (r *goRenderer) renderUnsignedRangeCheck(typ *wireType, goType string) {
	switch typ.BasicKind {
	case types.Uint8:
		r.line("\tif raw > 255 { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of uint8 range\", path) }", goType)
	case types.Uint16:
		r.line("\tif raw > 65535 { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of uint16 range\", path) }", goType)
	case types.Uint32:
		r.line("\tif raw > 4294967295 { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of uint32 range\", path) }", goType)
	case types.Uint, types.Uintptr:
		r.line("\tif uint64(%s(raw)) != raw { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of %s range\", path) }", goType, goType, goType)
	}
}

func (r *goRenderer) renderBigIntDecoder(typ *wireType, goType string) {
	_, pointer := typ.Original.(*types.Pointer)
	if pointer {
		r.line("\tif value == nil { return nil, nil }")
	}
	r.line("\tvar parsed *big.Int")
	r.line("\tswitch raw := value.(type) {")
	r.line("\tcase *big.Int:")
	r.line("\t\tparsed = new(big.Int).Set(raw)")
	r.line("\tcase string:")
	r.line("\t\tvar ok bool")
	r.line("\t\tparsed, ok = new(big.Int).SetString(raw, 16)")
	r.line("\t\tif !ok { var zero %s; return zero, fmt.Errorf(\"%%s: invalid hexadecimal BigInt\", path) }", goType)
	r.line("\tdefault:")
	r.line("\t\tvar zero %s; return zero, fgbTypeError(path, \"BigInt hexadecimal string\", value)", goType)
	r.line("\t}")
	if pointer {
		r.line("\treturn parsed, nil")
	} else {
		r.line("\treturn *parsed, nil")
	}
}

func (r *goRenderer) renderBigIntEncoder(typ *wireType) {
	_, pointer := typ.Original.(*types.Pointer)
	if pointer {
		r.line("\tif value == nil { return nil, nil }")
		r.line("\treturn new(big.Int).Set(value), nil")
	} else {
		r.line("\treturn new(big.Int).Set(&value), nil")
	}
}

func (r *goRenderer) goType(typ types.Type) string {
	return types.TypeString(typ, func(pkg *types.Package) string {
		if pkg == nil {
			return ""
		}
		if pkg.Path() == r.unit.PackagePath {
			if r.unit.Direct {
				return ""
			}
			return "api"
		}
		switch pkg.Path() {
		case "time":
			return "time"
		case "math/big":
			return "big"
		case dartOpaquePackagePath:
			return "fgbrt"
		default:
			return pkg.Name()
		}
	})
}

func (r *goRenderer) line(format string, args ...any) {
	if len(args) == 0 {
		r.buffer.WriteString(format)
	} else {
		fmt.Fprintf(&r.buffer, format, args...)
	}
	r.buffer.WriteByte('\n')
}

func (r *goRenderer) raw(value string) {
	r.buffer.WriteString(value)
	r.buffer.WriteByte('\n')
}
