package generator

import (
	"fmt"
	"path/filepath"
	"strconv"
	"strings"
)

// renderDartDual mirrors flutter_rust_bridge's generated Dart layout: the
// public API, models, and standard codecs live in one shared library, while
// conditional imports select only the platform-specific transport.
func renderDartDual(native, web *unit, configuredOutput string) (map[string][]byte, error) {
	root, central := dartOutputPaths(configuredOutput)
	ioPath := dartPlatformOutputPath(central, "io")
	webPath := dartPlatformOutputPath(central, "web")
	_, paths := dartSourceGroups(native)
	orderedKeys := sortedSourceKeys(paths)

	result := map[string][]byte{}
	common, err := renderDartDualCommon(native, central, ioPath, webPath, paths, orderedKeys)
	if err != nil {
		return nil, err
	}
	result[central] = common

	ioSource, err := renderDartDualPlatform(native, ioPath, central, paths, orderedKeys, false)
	if err != nil {
		return nil, err
	}
	result[ioPath] = ioSource
	webSource, err := renderDartDualPlatform(web, webPath, central, paths, orderedKeys, true)
	if err != nil {
		return nil, err
	}
	result[webPath] = webSource

	// The source renderer is platform-neutral except for dart:io imports. Use
	// Web import rules so InternetAddress is supplied by the conditional wire
	// library, then keep this one shared API tree.
	apiUnit := *native
	apiUnit.Target = "web"
	apiFiles, err := renderDartSplit(&apiUnit, central)
	if err != nil {
		return nil, err
	}
	for path, content := range apiFiles {
		if !samePath(path, central) {
			result[path] = content
		}
	}

	// Keep the collision check tied to the common output even though source
	// rendering above used the same path already.
	for _, key := range orderedKeys {
		sourcePath := filepath.Join(root, filepath.FromSlash(paths[key]))
		if samePath(sourcePath, central) || samePath(sourcePath, ioPath) || samePath(sourcePath, webPath) {
			return nil, fmt.Errorf("Dart source %s collides with generated bridge output; choose a different dart_output", paths[key])
		}
	}
	return result, nil
}

func dartPlatformOutputPath(central, platform string) string {
	ext := filepath.Ext(central)
	return strings.TrimSuffix(central, ext) + "." + platform + ext
}

func renderDartDualCommon(unit *unit, central, ioPath, webPath string, paths map[string]string, orderedKeys []string) ([]byte, error) {
	r := &splitDartRenderer{unit: unit}
	r.line("// Code generated by flutter_go_bridge_codegen. DO NOT EDIT.")
	r.line("// ignore_for_file: unused_element, unused_import, unnecessary_import")
	r.line("import 'dart:async';")
	r.line("import 'dart:convert';")
	r.line("import 'dart:typed_data';")
	r.line("import %s", conditionalDartURI(central, ioPath, webPath))
	r.line("export %s", conditionalDartURI(central, ioPath, webPath))
	if unit.UsesUUID {
		r.line("import 'package:uuid/uuid.dart';")
	}
	if unit.UsesDecimal {
		r.line("import 'package:decimal/decimal.dart';")
	}
	for _, key := range orderedKeys {
		r.line("import %s;", strconv.Quote(filepath.ToSlash(paths[key])))
	}
	r.line("")
	if unit.DartPreamble != "" {
		r.raw(strings.TrimRight(unit.DartPreamble, "\n"))
		r.line("")
	}
	runtime, err := dartCommonRuntimeSource()
	if err != nil {
		return nil, err
	}
	r.raw(strings.ReplaceAll(runtime, "__FGB_BRIDGE_CLASS__", unit.ClassName))
	for _, declaration := range unit.Interfaces {
		r.renderInterfaceAbsentClass(declaration)
	}
	for _, typ := range unit.Types {
		if err := r.renderDecoder(typ); err != nil {
			return nil, err
		}
		r.line("")
		if err := r.renderEncoder(typ); err != nil {
			return nil, err
		}
		r.line("")
	}
	return []byte(strings.ReplaceAll(r.buffer.String(), "__FGB_BRIDGE_CLASS__", unit.ClassName)), nil
}

func renderDartDualPlatform(unit *unit, output, common string, paths map[string]string, orderedKeys []string, web bool) ([]byte, error) {
	r := &splitDartRenderer{unit: unit}
	r.line("// Code generated by flutter_go_bridge_codegen. DO NOT EDIT.")
	r.line("// ignore_for_file: unused_element, unused_import, unnecessary_import")
	if web {
		r.line("// Static analysis selects the IO conditional import; Web compilation selects this library.")
		r.line("// ignore_for_file: argument_type_not_assignable")
	}
	r.line("import 'dart:async';")
	r.line("import 'dart:convert';")
	if web {
		r.line("import 'dart:js_interop';")
		r.line("import 'dart:js_interop_unsafe';")
		if unit.UseFlutterWebLoader {
			r.line("import 'package:flutter/services.dart';")
			r.line("import 'package:flutter/widgets.dart';")
		}
	} else {
		r.line("import 'dart:ffi' as ffi;")
		r.line("import 'dart:io';")
		r.line("import 'dart:isolate';")
		if unit.UsesInternetIP {
			r.line("export 'dart:io' show InternetAddress;")
		}
	}
	r.line("import 'dart:typed_data';")
	r.line("import %s;", dartImportPath(output, common))
	root := filepath.Dir(common)
	for _, key := range orderedKeys {
		r.line("import %s;", dartImportPath(output, filepath.Join(root, filepath.FromSlash(paths[key]))))
	}
	if unit.UsesUUID {
		r.line("import 'package:uuid/uuid.dart';")
	}
	if unit.UsesDecimal {
		r.line("import 'package:decimal/decimal.dart';")
	}
	r.line("")

	var runtime string
	var err error
	if web {
		runtime = dartWebPlatformRuntimeSource(unit)
	} else {
		runtime, err = dartNativePlatformRuntimeSource(unit)
		if err != nil {
			return nil, err
		}
	}
	r.raw(runtime)
	if !web && hasCstDcoCalls(unit) {
		r.raw(cstDartDefinitions(unit))
		r.line("")
		r.renderCstEncoders()
	}
	r.renderCentralCallMethods()
	return []byte(strings.ReplaceAll(r.buffer.String(), "__FGB_BRIDGE_CLASS__", unit.ClassName)), nil
}

func conditionalDartURI(from, ioPath, webPath string) string {
	return dartImportPath(from, ioPath) + "\n    if (dart.library.js_interop) " + dartImportPath(from, webPath) + ";"
}
