package generator

import (
	"bytes"
	"fmt"
	"go/types"
	"strconv"
	"strings"

	bridgemodel "github.com/star4277/flutter_go_bridge/internal/model"
)

type goRenderer struct {
	unit   *unit
	buffer bytes.Buffer
}

func renderGo(unit *unit) ([]byte, error) {
	r := &goRenderer{unit: unit}
	if unit.GoPreamble != "" {
		r.raw(strings.TrimRight(unit.GoPreamble, "\n"))
		r.line("")
	}
	r.line("// Code generated by flutter_go_bridge_codegen. DO NOT EDIT.")
	r.line("package main")
	r.line("")
	r.line("/*")
	cgoPreamble := strings.TrimSpace(goCgoPreambleSource)
	if hasCstDcoCalls(unit) {
		cgoPreamble += "\n\n" + cstForwardDeclarations(unit)
	}
	r.raw(cgoPreamble)
	r.line("*/")
	r.line(`import "C"`)
	r.line("")
	r.line("import (")
	imports := []string{
		"bytes", "encoding/binary", "fmt", "io", "math/big", "reflect",
		"os", "runtime", "runtime/debug", "sync", "sync/atomic", "unsafe",
	}
	// The stream runtime always carries the cancellation plumbing, so context
	// is part of the fixed import set.
	imports = append(imports, "context")
	if unit.UsesTime {
		imports = append(imports, "time")
	}
	if unit.UsesInternetIP || unit.UsesIPPrefix {
		imports = append(imports, "net/netip")
	}
	if unit.UsesURL {
		imports = append(imports, "net/url")
	}
	if unit.UsesUUID {
		imports = append(imports, "github.com/gofrs/uuid/v5")
	}
	if unit.UsesShopspringDecimal {
		imports = append(imports, "github.com/shopspring/decimal")
	}
	if unit.UsesAPDDecimal {
		imports = append(imports, "github.com/cockroachdb/apd/v3")
	}
	for _, item := range imports {
		r.line("\t%q", item)
	}
	if unit.UsesRuntimePackage {
		// The exported ABI already owns the identifier `fgb` (the sync
		// entrypoint), so the runtime package needs an alias.
		r.line("\tfgbrt %q", unit.SupportPackagePath)
	}
	if !unit.Direct {
		r.line("\tapi %q", unit.PackagePath)
	}
	for _, item := range unit.ExternalImports {
		r.line("\t%s %q", item.Alias, item.Path)
	}
	r.line(")")
	r.line("")
	r.raw(strings.TrimSpace(goRuntimeSource))
	r.line("")
	if unit.usesCgoScalars() {
		r.renderCgoReflectionHelpers()
		r.line("")
	}
	if unit.UsesTime {
		r.renderTimeHelpers()
	}
	if unit.NeedsMain {
		r.line("// Required for c-shared and c-archive build modes.")
		r.line("func main() {}")
		r.line("")
	}
	if hasCstDcoCalls(unit) {
		r.renderCstDecoders()
		r.renderDcoEncoders()
	}

	for _, typ := range unit.Types {
		if err := r.renderDecoder(typ); err != nil {
			return nil, err
		}
		r.line("")
		if err := r.renderEncoder(typ); err != nil {
			return nil, err
		}
		r.line("")
	}
	for _, typ := range unit.Types {
		if typ.Kind == kindCallback {
			r.renderCallbackFactory(typ)
			r.line("")
		}
		if typ.Kind == kindStreamSink {
			if typ.ChannelStream {
				r.renderStreamChannelHelpers(typ)
			} else {
				r.renderStreamSinkFactory(typ)
			}
			r.line("")
		}
	}
	r.renderDispatch()
	// Keep the CST ABI present even for a package whose current API only uses
	// the Standard fallback; the Dart runtime can then use one stable binding
	// layout and future regenerated calls do not change symbol discovery.
	r.renderCstDispatch()
	return r.buffer.Bytes(), nil
}

func (r *goRenderer) renderTimeHelpers() {
	r.line("const (")
	r.line("\tfgbDartDateTimeMinMicroseconds int64 = -8640000000000000000")
	r.line("\tfgbDartDateTimeMaxMicroseconds int64 = 8640000000000000000")
	r.line(")")
	r.line("")
	r.line("func fgbTimeUnixMicro(value time.Time) (int64, error) {")
	r.line("\tif value.Before(time.UnixMicro(fgbDartDateTimeMinMicroseconds)) || value.After(time.UnixMicro(fgbDartDateTimeMaxMicroseconds)) {")
	r.raw("\t\treturn 0, fmt.Errorf(\"time %s is outside Dart DateTime range\", value.Format(time.RFC3339Nano))")
	r.line("\t}")
	r.line("\treturn value.UnixMicro(), nil")
	r.line("}")
	r.line("")
}

func (r *goRenderer) renderCgoReflectionHelpers() {
	r.raw(`func fgbReflectCall(function any, arguments []any) ([]reflect.Value, error) {
	target := reflect.ValueOf(function)
	if !target.IsValid() || target.Kind() != reflect.Func {
		return nil, fmt.Errorf("CGo bridge target is not a function")
	}
	targetType := target.Type()
	if len(arguments) != targetType.NumIn() {
		return nil, fmt.Errorf("CGo bridge target wants %d arguments, got %d", targetType.NumIn(), len(arguments))
	}
	converted := make([]reflect.Value, len(arguments))
	for index, argument := range arguments {
		want := targetType.In(index)
		if argument == nil {
			switch want.Kind() {
			case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
				converted[index] = reflect.Zero(want)
				continue
			default:
				return nil, fmt.Errorf("argument %d is null, want %s", index, want)
			}
		}
		value := reflect.ValueOf(argument)
		switch {
		case value.Type().AssignableTo(want):
			converted[index] = value
		case value.Type().ConvertibleTo(want):
			converted[index] = value.Convert(want)
		default:
			return nil, fmt.Errorf("argument %d has type %s, want %s", index, value.Type(), want)
		}
	}
	return target.Call(converted), nil
}

func fgbReflectResult[T any](value reflect.Value) (T, error) {
	var zero T
	if !value.IsValid() {
		return zero, fmt.Errorf("invalid CGo result")
	}
	want := reflect.TypeFor[T]()
	if value.Type().AssignableTo(want) {
		return value.Interface().(T), nil
	}
	if value.Type().ConvertibleTo(want) {
		return value.Convert(want).Interface().(T), nil
	}
	return zero, fmt.Errorf("CGo result has type %s, want %s", value.Type(), want)
}

func fgbReflectError(value reflect.Value) error {
	if !value.IsValid() || ((value.Kind() == reflect.Interface || value.Kind() == reflect.Pointer) && value.IsNil()) {
		return nil
	}
	result, _ := value.Interface().(error)
	return result
}

func fgbSetCgoField(target any, name string, value any) error {
	structure := reflect.ValueOf(target)
	if !structure.IsValid() || structure.Kind() != reflect.Pointer || structure.IsNil() {
		return fmt.Errorf("CGo field target must be a non-null pointer")
	}
	field := structure.Elem().FieldByName(name)
	if !field.IsValid() || !field.CanSet() {
		return fmt.Errorf("CGo field %s is not settable", name)
	}
	source := reflect.ValueOf(value)
	if !source.IsValid() || !source.Type().ConvertibleTo(field.Type()) {
		return fmt.Errorf("CGo field %s cannot accept %T", name, value)
	}
	field.Set(source.Convert(field.Type()))
	return nil
}`)
}

func (r *goRenderer) renderDecoder(typ *wireType) error {
	goType := r.goType(typ.Original)
	decodeType := goType
	if typ.usesPointerCodec(map[int]bool{}) {
		decodeType = "*" + goType
	}
	r.line("func fgbDecode%d(value any, path string) (%s, error) {", typ.ID, decodeType)
	switch typ.Kind {
	case kindBool:
		r.line("\tresult, ok := value.(bool)")
		r.line("\tif !ok { return false, fgbTypeError(path, \"bool\", value) }")
		r.line("\treturn result, nil")
	case kindString:
		r.line("\tresult, ok := value.(string)")
		r.line("\tif !ok { return \"\", fgbTypeError(path, \"string\", value) }")
		r.line("\treturn result, nil")
	case kindError:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\traw, ok := value.(string)")
		r.line("\tif !ok { return nil, fgbTypeError(path, \"error string\", value) }")
		r.raw("\treturn fmt.Errorf(\"%s\", raw), nil")
	case kindSigned:
		r.line("\traw, err := fgbAsInt64(value, path)")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.renderSignedRangeCheck(typ, goType)
		r.line("\treturn %s(raw), nil", goType)
	case kindUnsigned:
		r.line("\traw, err := fgbAsUint64(value, path)")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.renderUnsignedRangeCheck(typ, goType)
		r.line("\treturn %s(raw), nil", goType)
	case kindFloat:
		r.line("\traw, err := fgbAsFloat64(value, path)")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.line("\treturn %s(raw), nil", goType)
	case kindBigInt:
		r.renderBigIntDecoder(typ, goType)
	case kindTime:
		r.line("\traw, err := fgbAsInt64(value, path)")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.line("\treturn time.UnixMicro(raw).UTC(), nil")
	case kindInternetIP:
		r.line("\traw, ok := value.(string)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"IP string\", value) }", goType)
		r.line("\tif raw == \"\" { return netip.Addr{}, nil }")
		r.line("\tresult, err := netip.ParseAddr(raw)")
		r.line("\tif err != nil { var zero %s; return zero, fmt.Errorf(\"%%s: invalid IP: %%w\", path, err) }", goType)
		r.line("\treturn result, nil")
	case kindIPPrefix:
		r.line("\traw, ok := value.(string)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"CIDR prefix string\", value) }", goType)
		r.line("\tif raw == \"\" { return netip.Prefix{}, nil }")
		r.line("\tresult, err := netip.ParsePrefix(raw)")
		r.line("\tif err != nil { var zero %s; return zero, fmt.Errorf(\"%%s: invalid CIDR prefix: %%w\", path, err) }", goType)
		r.line("\treturn result, nil")
	case kindURL:
		r.line("\traw, ok := value.(string)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"URI string\", value) }", goType)
		r.renderURLParse(goType, "raw")
	case kindUUID:
		r.line("\traw, ok := value.(string)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"UUID string\", value) }", goType)
		r.line("\tresult, err := uuid.FromString(raw)")
		r.line("\tif err != nil { var zero %s; return zero, fmt.Errorf(\"%%s: invalid UUID: %%w\", path, err) }", goType)
		r.line("\treturn result, nil")
	case kindDecimal:
		r.line("\traw, ok := value.(string)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"Decimal string\", value) }", goType)
		if isShopspringDecimal(types.Unalias(typ.Original).(*types.Named)) {
			r.line("\tresult, err := decimal.NewFromString(raw)")
		} else {
			r.line("\tparsed, _, err := apd.NewFromString(raw)")
			r.line("\tvar result %s", goType)
			r.line("\tif parsed != nil { result = *parsed }")
		}
		r.line("\tif err != nil { var zero %s; return zero, fmt.Errorf(\"%%s: invalid Decimal: %%w\", path, err) }", goType)
		r.line("\treturn result, nil")
	case kindDuration:
		r.line("\traw, err := fgbAsInt64(value, path)")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.renderDurationFromMicroseconds(goType, "raw")
	case kindAny:
		r.line("\treturn value, nil")
	case kindPointer:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\tdecoded, err := fgbDecode%d(value, path)", typ.Elem.ID)
		r.line("\tif err != nil { return nil, err }")
		if typ.Elem.usesPointerCodec(map[int]bool{}) {
			r.line("\treturn decoded, nil")
		} else {
			r.line("\treturn &decoded, nil")
		}
	case kindBytes:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\traw, ok := value.([]byte)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"Uint8List\", value) }", goType)
		r.renderTypedListCopy(goType)
	case kindInt32List:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\traw, ok := value.([]int32)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"Int32List\", value) }", goType)
		r.renderTypedListCopy(goType)
	case kindInt64List:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\traw, ok := value.([]int64)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"Int64List\", value) }", goType)
		r.renderTypedListCopy(goType)
	case kindFloat64List:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\traw, ok := value.([]float64)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"Float64List\", value) }", goType)
		r.renderTypedListCopy(goType)
	case kindSlice:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\traw, ok := value.([]any)")
		r.line("\tif !ok { return nil, fgbTypeError(path, \"List\", value) }")
		r.line("\tresult := make(%s, len(raw))", goType)
		r.line("\tfor index, item := range raw {")
		r.line("\t\tdecoded, err := fgbDecode%d(item, fmt.Sprintf(\"%%s[%%d]\", path, index))", typ.Elem.ID)
		r.line("\t\tif err != nil { return nil, err }")
		r.line("\t\tresult[index] = decoded")
		r.line("\t}")
		r.line("\treturn result, nil")
	case kindArray:
		r.line("\traw, ok := value.([]any)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"List\", value) }", goType)
		r.line("\tif len(raw) != %d { var zero %s; return zero, fmt.Errorf(\"%%s: expected %d elements, got %%d\", path, len(raw)) }", typ.Length, goType, typ.Length)
		r.line("\tvar result %s", goType)
		r.line("\tfor index, item := range raw {")
		r.line("\t\tdecoded, err := fgbDecode%d(item, fmt.Sprintf(\"%%s[%%d]\", path, index))", typ.Elem.ID)
		r.line("\t\tif err != nil { var zero %s; return zero, err }", goType)
		r.line("\t\tresult[index] = decoded")
		r.line("\t}")
		r.line("\treturn result, nil")
	case kindMap:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\traw, ok := value.(map[any]any)")
		r.line("\tif !ok { return nil, fgbTypeError(path, \"Map\", value) }")
		r.line("\tresult := make(%s, len(raw))", goType)
		r.line("\tfor rawKey, rawValue := range raw {")
		r.line("\t\tkey, err := fgbDecode%d(rawKey, path+\".<key>\")", typ.Key.ID)
		r.line("\t\tif err != nil { return nil, err }")
		r.line("\t\tdecoded, err := fgbDecode%d(rawValue, fmt.Sprintf(\"%%s[%%v]\", path, key))", typ.Elem.ID)
		r.line("\t\tif err != nil { return nil, err }")
		r.line("\t\tresult[key] = decoded")
		r.line("\t}")
		r.line("\treturn result, nil")
	case kindStruct:
		fields := typ.Struct.allFields()
		if len(fields) == 0 {
			r.line("\t_, ok := value.(map[any]any)")
		} else {
			r.line("\traw, ok := value.(map[any]any)")
		}
		if typ.usesPointerCodec(map[int]bool{}) {
			r.line("\tif !ok { return nil, fgbTypeError(path, \"Map\", value) }")
			r.line("\tresult := new(%s)", goType)
		} else {
			r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"Map\", value) }", goType)
			r.line("\tvar result %s", goType)
		}
		for _, field := range fields {
			if field.Type.Kind == kindAtomic {
				r.line("\tdecoded%s, err := fgbDecode%d(raw[%s], path+%s)", field.GoName, field.Type.Atomic.Value.ID, strconv.Quote(field.WireName), strconv.Quote("."+field.WireName))
				if typ.usesPointerCodec(map[int]bool{}) {
					r.line("\tif err != nil { return nil, err }")
				} else {
					r.line("\tif err != nil { var zero %s; return zero, err }", goType)
				}
				r.line("\tresult.%s.Store(decoded%s)", field.GoName, field.GoName)
				continue
			}
			r.line("\tdecoded%s, err := fgbDecode%d(raw[%s], path+%s)", field.GoName, field.Type.ID, strconv.Quote(field.WireName), strconv.Quote("."+field.WireName))
			if typ.usesPointerCodec(map[int]bool{}) {
				r.line("\tif err != nil { return nil, err }")
			} else {
				r.line("\tif err != nil { var zero %s; return zero, err }", goType)
			}
			if field.Type.CgoScalar {
				if typ.usesPointerCodec(map[int]bool{}) {
					r.line("\tif err := fgbSetCgoField(result, %s, decoded%s); err != nil { return nil, fmt.Errorf(\"%%s: %%w\", path, err) }", strconv.Quote(field.GoName), field.GoName)
				} else {
					r.line("\tif err := fgbSetCgoField(&result, %s, decoded%s); err != nil { var zero %s; return zero, fmt.Errorf(\"%%s: %%w\", path, err) }", strconv.Quote(field.GoName), field.GoName, goType)
				}
				continue
			}
			r.line("\tresult.%s = decoded%s", field.GoName, field.GoName)
		}
		r.line("\treturn result, nil")
	case kindOpaque:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\thandle, err := fgbAsHandle(value, path)")
		r.line("\tif err != nil { return nil, err }")
		r.line("\traw, ok := fgbLoadOpaque(handle)")
		r.raw("\tif !ok { return nil, fmt.Errorf(\"%s: unknown or released handle %d\", path, handle) }")
		if typ.Opaque.Synthetic && !isPointerType(typ.Original) {
			r.line("\tboxed, ok := raw.(*%s)", goType)
			r.raw("\tif !ok { return nil, fmt.Errorf(\"%s: handle %d has incompatible Go type %T\", path, handle, raw) }")
			r.line("\treturn *boxed, nil")
			break
		}
		r.line("\tresult, ok := raw.(%s)", goType)
		r.raw("\tif !ok { return nil, fmt.Errorf(\"%s: handle %d has incompatible Go type %T\", path, handle, raw) }")
		r.line("\treturn result, nil")
	case kindDartOpaque:
		r.line("\traw, err := fgbAsInt64(value, path)")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.line("\tif raw == 0 { var zero %s; return zero, fmt.Errorf(\"%%s: invalid DartOpaque handle 0\", path) }", goType)
		r.line("\tgeneration := fgbCurrentDartOpaqueGeneration()")
		r.line("\treturn fgbrt.NewDartOpaque(raw, func(handle int64) { fgbReleaseDartOpaque(generation, handle) }), nil")
	case kindCallback:
		r.line("\traw, err := fgbAsInt64(value, path)")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.line("\treturn fgbMakeCallback%d(context.Background(), raw), nil", typ.ID)
	case kindStreamSink:
		if typ.ChannelStream {
			// Channel streams are wired up by the dispatcher, which owns the
			// channel; there is nothing to decode from a value here.
			r.line("\tvar zero %s", goType)
			r.raw("\treturn zero, fmt.Errorf(\"%s: channel streams are only supported as direct call parameters\", path)\n")
			break
		}
		r.line("\traw, err := fgbAsInt64(value, path)")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.line("\tif raw == 0 { var zero %s; return zero, fmt.Errorf(\"%%s: invalid stream handle 0\", path) }", goType)
		r.line("\treturn fgbMakeStreamSink%d(raw), nil", typ.ID)
	case kindInterface:
		// A tagged union: [implementorTag, payload]. Dependency interfaces use
		// content tags; input interfaces retain their historical integer ABI.
		r.line("\tif value == nil { var zero %s; return zero, nil }", goType)
		r.line("\traw, ok := value.([]any)")
		r.line("\tif !ok || len(raw) != 2 { var zero %s; return zero, fgbTypeError(path, \"interface envelope\", value) }", goType)
		if typ.Interface.UsesContentTags {
			r.line("\ttag, ok := raw[0].(string)")
			r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path+\".tag\", \"interface type tag\", raw[0]) }", goType)
		} else {
			r.line("\ttag, err := fgbAsInt64(raw[0], path+\".tag\")")
			r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		}
		r.line("\tswitch tag {")
		for index, implementor := range typ.Interface.Implementors {
			r.line("\tcase %s:", interfaceWireTagLiteral(typ.Interface, implementor, index))
			r.line("\t\treturn fgbDecode%d(raw[1], path)", implementor.Type.ID)
		}
		r.line("\t}")
		r.line("\tvar zero %s; return zero, fmt.Errorf(\"%%s: unknown %s implementation %%v\", path, tag)", goType, typ.Interface.GoName)
	case kindNamed:
		r.line("\tdecoded, err := fgbDecode%d(value, path)", typ.Named.Underlying.ID)
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.line("\treturn %s(decoded), nil", goType)
	case kindAtomic:
		r.line("\tdecoded, err := fgbDecode%d(value, path)", typ.Atomic.Value.ID)
		r.line("\tif err != nil { return nil, err }")
		r.line("\tresult := new(%s)", goType)
		r.line("\tresult.Store(decoded)")
		r.line("\treturn result, nil")
	default:
		return fmt.Errorf("no Go decoder for %s", typ.Kind)
	}
	r.line("}")
	return nil
}

// renderTypedListCopy copies a decoded typed list. `append(T(nil), raw...)`
// would look equivalent but returns nil for an empty input, which would erase
// the difference between an empty list and a nil one.
func (r *goRenderer) renderTypedListCopy(goType string) {
	r.line("\tresult := make(%s, len(raw))", goType)
	r.line("\tcopy(result, raw)")
	r.line("\treturn result, nil")
}

func (r *goRenderer) renderEncoder(typ *wireType) error {
	goType := r.goType(typ.Original)
	encodeType := goType
	if typ.usesPointerCodec(map[int]bool{}) {
		encodeType = "*" + goType
	}
	r.line("func fgbEncode%d(value %s, depth int, transfer *fgbOpaqueTransfer) (any, error) {", typ.ID, encodeType)
	r.line("\tif depth > 64 { return nil, fmt.Errorf(\"value nesting exceeds 64 levels (cyclic reference?)\") }")
	switch typ.Kind {
	case kindBool, kindString:
		r.line("\treturn value, nil")
	case kindError:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\treturn value.Error(), nil")
	case kindSigned:
		if typ.BitSize <= 32 && typ.BasicKind != types.Int {
			r.line("\treturn int32(value), nil")
		} else {
			r.line("\treturn int64(value), nil")
		}
	case kindUnsigned:
		if typ.DartType == "BigInt" {
			r.line("\treturn new(big.Int).SetUint64(uint64(value)), nil")
		} else if typ.BitSize <= 16 {
			r.line("\treturn int32(value), nil")
		} else {
			r.line("\treturn int64(value), nil")
		}
	case kindFloat:
		r.line("\treturn float64(value), nil")
	case kindBigInt:
		r.renderBigIntEncoder(typ)
	case kindTime:
		r.line("\treturn fgbTimeUnixMicro(value)")
	case kindInternetIP:
		// netip.Addr.String returns an empty string for the invalid zero value,
		// which InternetAddress represents without changing pointer nullability.
		r.line("\treturn value.String(), nil")
	case kindIPPrefix:
		// netip.Prefix.String would emit "invalid Prefix" for the zero value, so
		// the wire uses the empty string that ParsePrefix's decoder maps back.
		r.line("\tif !value.IsValid() { return \"\", nil }")
		r.line("\treturn value.String(), nil")
	case kindUUID:
		r.line("\treturn value.String(), nil")
	case kindDecimal:
		if isAPDDecimal(types.Unalias(typ.Original).(*types.Named)) {
			r.line("\tif value.Form != apd.Finite { return nil, fmt.Errorf(\"apd Decimal must be finite\") }")
		}
		r.line("\treturn value.String(), nil")
	case kindURL:
		r.line("\treturn value.String(), nil")
	case kindDuration:
		r.line("\treturn int64(value / time.Microsecond), nil")
	case kindAny:
		r.line("\treturn fgbNormalize(value, depth)")
	case kindPointer:
		r.line("\tif value == nil { return nil, nil }")
		if typ.Elem.usesPointerCodec(map[int]bool{}) {
			r.line("\treturn fgbEncode%d(value, depth+1, transfer)", typ.Elem.ID)
		} else {
			r.line("\treturn fgbEncode%d(*value, depth+1, transfer)", typ.Elem.ID)
		}
	case kindBytes, kindInt32List, kindInt64List, kindFloat64List:
		r.line("\tif value == nil { return %s{}, nil }", goType)
		r.line("\treturn value, nil")
	case kindSlice:
		r.line("\tif value == nil { return []any{}, nil }")
		r.line("\tresult := make([]any, len(value))")
		r.line("\tfor index, item := range value {")
		r.line("\t\tencoded, err := fgbEncode%d(item, depth+1, transfer)", typ.Elem.ID)
		r.raw("\t\tif err != nil { return nil, fmt.Errorf(\"element %d: %w\", index, err) }")
		r.line("\t\tresult[index] = encoded")
		r.line("\t}")
		r.line("\treturn result, nil")
	case kindArray:
		r.line("\tresult := make([]any, len(value))")
		r.line("\tfor index, item := range value {")
		r.line("\t\tencoded, err := fgbEncode%d(item, depth+1, transfer)", typ.Elem.ID)
		r.raw("\t\tif err != nil { return nil, fmt.Errorf(\"element %d: %w\", index, err) }")
		r.line("\t\tresult[index] = encoded")
		r.line("\t}")
		r.line("\treturn result, nil")
	case kindMap:
		r.line("\tif value == nil { return map[any]any{}, nil }")
		r.line("\tresult := make(map[any]any, len(value))")
		r.line("\tfor key, item := range value {")
		r.line("\t\tencodedKey, err := fgbEncode%d(key, depth+1, transfer)", typ.Key.ID)
		r.raw("\t\tif err != nil { return nil, fmt.Errorf(\"map key: %w\", err) }")
		r.line("\t\tencoded, err := fgbEncode%d(item, depth+1, transfer)", typ.Elem.ID)
		r.raw("\t\tif err != nil { return nil, fmt.Errorf(\"map value: %w\", err) }")
		r.line("\t\tresult[encodedKey] = encoded")
		r.line("\t}")
		r.line("\treturn result, nil")
	case kindStruct:
		if typ.usesPointerCodec(map[int]bool{}) {
			r.line("\tif value == nil { return nil, nil }")
		}
		fields := typ.Struct.allFields()
		r.line("\tresult := make(map[any]any, %d)", len(fields))
		for _, field := range fields {
			encodeID := field.Type.ID
			encodeExpr := fmt.Sprintf("value.%s", field.GoName)
			if field.Type.Kind == kindAtomic {
				encodeID = field.Type.Atomic.Value.ID
				encodeExpr = fmt.Sprintf("value.%s.Load()", field.GoName)
			}
			encodeExpr = r.goWireValue(field.Type, encodeExpr)
			// A nullable field keeps its nil: the shared encoders normalize a
			// nil slice or map to an empty one, which would erase exactly the
			// distinction the field was marked for.
			if field.Nullable {
				r.line("\tvar encoded%s any", field.GoName)
				r.line("\tif value.%s != nil {", field.GoName)
				r.line("\t\traw, err := fgbEncode%d(value.%s, depth+1, transfer)", field.Type.ID, field.GoName)
				r.line("\t\tif err != nil { return nil, fmt.Errorf(%s+\": %%w\", err) }", strconv.Quote(field.WireName))
				r.line("\t\tencoded%s = raw", field.GoName)
				r.line("\t}")
				r.line("\tresult[%s] = encoded%s", strconv.Quote(field.WireName), field.GoName)
				continue
			}
			r.line("\tencoded%s, err := fgbEncode%d(%s, depth+1, transfer)", field.GoName, encodeID, encodeExpr)
			r.line("\tif err != nil { return nil, fmt.Errorf(%s+\": %%w\", err) }", strconv.Quote(field.WireName))
			r.line("\tresult[%s] = encoded%s", strconv.Quote(field.WireName), field.GoName)
		}
		r.line("\treturn result, nil")
	case kindOpaque:
		r.line("\tif value == nil { return nil, nil }")
		if typ.Opaque.Synthetic && !isPointerType(typ.Original) {
			r.line("\tboxed := new(%s)", goType)
			r.line("\t*boxed = value")
			r.line("\thandle, err := fgbStoreOpaque(boxed, transfer)")
		} else {
			r.line("\thandle, err := fgbStoreOpaque(value, transfer)")
		}
		r.line("\tif err != nil { return nil, err }")
		r.line("\treturn int64(handle), nil")
	case kindDartOpaque:
		r.line("\tif !value.IsValid() { return nil, fmt.Errorf(\"cannot encode an invalid DartOpaque\") }")
		r.line("\treturn value.Handle(), nil")
	case kindCallback:
		r.line("\treturn nil, fmt.Errorf(\"function values cannot be encoded\")")
	case kindStreamSink:
		r.line("\treturn nil, fmt.Errorf(\"stream sinks cannot be sent to Dart\")")
	case kindInterface:
		// Tag the value with the concrete type so the other side knows which
		// decoder to use. Most-derived first is irrelevant here: Go's type
		// switch matches the dynamic type exactly. A nil interface encodes as
		// null; the Dart decoder materializes an absent stand-in for it.
		r.line("\tif value == nil { return nil, nil }")
		r.line("\tswitch typed := value.(type) {")
		for index, implementor := range typ.Interface.Implementors {
			for _, dynamic := range implementor.GoTypes {
				r.line("\tcase %s:", r.goType(dynamic.Type))
				value := "typed"
				if dynamic.AddressValue {
					value = "&typed"
				}
				r.line("\t\tencoded, err := fgbEncode%d(%s, depth+1, transfer)", implementor.Type.ID, value)
				r.line("\t\tif err != nil { return nil, err }")
				r.line("\t\treturn []any{%s, encoded}, nil", goInterfaceWireTagLiteral(typ.Interface, implementor, index))
			}
		}
		r.line("\t}")
		r.raw("\treturn nil, fmt.Errorf(\"%T does not implement a bridged " + typ.Interface.GoName + " implementation\", value)")
	case kindNamed:
		underlyingGo := r.goType(typ.Named.Underlying.Original)
		r.line("\treturn fgbEncode%d(%s(value), depth+1, transfer)", typ.Named.Underlying.ID, underlyingGo)
	case kindAtomic:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\treturn fgbEncode%d(value.Load(), depth+1, transfer)", typ.Atomic.Value.ID)
	default:
		return fmt.Errorf("no Go encoder for %s", typ.Kind)
	}
	r.line("}")
	return nil
}

func goInterfaceWireTagLiteral(declaration *interfaceModel, implementor *implementorModel, index int) string {
	if declaration.UsesContentTags {
		return strconv.Quote(implementor.WireTag)
	}
	return fmt.Sprintf("int64(%d)", index)
}

func (r *goRenderer) goWireValue(typ *wireType, expression string) string {
	if typ != nil && typ.CgoScalar {
		return fmt.Sprintf("%s(%s)", r.goType(typ.Original), expression)
	}
	return expression
}

// renderCallbackFactory synthesizes the Go func value handed to user code for
// a Dart-supplied closure. Invoking it encodes the arguments, posts a request
// to the Dart event loop, and parks the goroutine until Dart replies - which
// is why callbacks are restricted to //fgb:async calls. Without a trailing
// `error` result, transport and Dart-side failures panic; the dispatch
// recover() then reports them to the original caller.
func (r *goRenderer) renderCallbackFactory(typ *wireType) {
	callback := typ.Callback
	goType := r.goType(typ.Original)
	r.line("func fgbMakeCallback%d(ctx context.Context, handle int64) %s {", typ.ID, goType)
	r.line("\t// Handle 0 means Dart passed null for a //fgb:nullable callback.")
	r.line("\tif handle == 0 { return nil }")
	r.line("\ttarget := fgbCallbackTargetRef.Load()")
	r.line("\tgeneration := int64(0)")
	r.line("\tif target != nil { generation = target.generation }")
	r.line("\tref := fgbNewCallbackRef(generation, handle)")

	params := make([]string, len(callback.Params))
	for index, param := range callback.Params {
		params[index] = fmt.Sprintf("a%d %s", index, r.goType(param.Original))
	}
	var results []string
	if callback.Result != nil {
		results = append(results, r.goType(callback.Result.Original))
	}
	if callback.HasError {
		results = append(results, "error")
	}
	resultText := ""
	switch len(results) {
	case 1:
		resultText = " " + results[0]
	case 2:
		resultText = " (" + strings.Join(results, ", ") + ")"
	}
	r.line("\treturn func(%s)%s {", strings.Join(params, ", "), resultText)
	r.line("\t\ttransfer := &fgbOpaqueTransfer{}")
	r.line("\t\tdefer transfer.rollback()")

	fail := func(wrap string) {
		switch {
		case callback.HasError && callback.Result != nil:
			r.line("\t\tif err != nil { var zero %s; return zero, %s }", r.goType(callback.Result.Original), wrap)
		case callback.HasError:
			r.line("\t\tif err != nil { return %s }", wrap)
		default:
			r.line("\t\tif err != nil { panic(%s) }", wrap)
		}
	}

	arguments := make([]string, len(callback.Params))
	for index, param := range callback.Params {
		r.line("\t\tencoded%d, err := fgbEncode%d(a%d, 0, transfer)", index, param.ID, index)
		fail(fmt.Sprintf("fmt.Errorf(\"callback argument %d: %%w\", err)", index))
		arguments[index] = fmt.Sprintf("encoded%d", index)
	}
	r.line("\t\treply, err := fgbInvokeCallback(ctx, generation, handle, []any{%s}, transfer)", strings.Join(arguments, ", "))
	r.line("\t\truntime.KeepAlive(ref)")
	fail("err")
	if callback.Result != nil {
		r.line("\t\tresult, err := fgbDecode%d(reply, \"callback result\")", callback.Result.ID)
		fail("fmt.Errorf(\"callback result: %w\", err)")
		if callback.HasError {
			r.line("\t\treturn result, nil")
		} else {
			r.line("\t\treturn result")
		}
	} else {
		r.line("\t\t_ = reply")
		if callback.HasError {
			r.line("\t\treturn nil")
		}
	}
	r.line("\t}")
	r.line("}")
}

// renderStreamSinkFactory binds the generated element encoder to the runtime
// sink so user code only sees fgb.StreamSink[T].
func (r *goRenderer) renderStreamSinkFactory(typ *wireType) {
	r.line("func fgbMakeStreamSink%d(handle int64) %s {", typ.ID, r.goType(typ.Original))
	r.line("\t// Capture the isolate generation at creation time: a hot restart")
	r.line("\t// retires this sink even if its producer goroutine keeps running.")
	r.line("\tgeneration := fgbCurrentStreamGeneration()")
	r.line("\treturn fgbrt.NewStreamSink(handle, func(value %s) (any, error) {", r.goType(typ.Stream.Original))
	r.line("\t\ttransfer := &fgbOpaqueTransfer{}")
	r.line("\t\tencoded, err := fgbEncode%d(value, 0, transfer)", typ.Stream.ID)
	r.line("\t\tif err != nil { transfer.rollback(); return nil, err }")
	r.line("\t\treturn fgbStreamPayload{value: encoded, transfer: transfer}, nil")
	r.line("\t}, func(handle int64, kind int32, payload any) bool {")
	r.line("\t\treturn fgbPostStreamEvent(generation, handle, kind, payload)")
	r.line("\t}, func(handle int64) {")
	r.line("\t\tfgbReleaseStreamSink(generation, handle)")
	r.line("\t})")
	r.line("}")
}

// renderGoCallStatement emits the Go call plus the shared error handling.
// Non-error results are bound to result<k>, every `error` result to goErr<j>;
// any non-nil error fails the call, and several are reported together.
func (r *goRenderer) renderGoCallStatement(call *callModel, indent, methodExpr string) {
	if call.Reflective {
		r.renderReflectiveGoCallStatement(call, indent, methodExpr)
		return
	}
	assignments := make([]string, 0, len(call.Results)+call.ErrorCount)
	nextResult, nextError := 0, 0
	for _, isError := range call.resultShape() {
		if isError {
			assignments = append(assignments, fmt.Sprintf("goErr%d", nextError))
			nextError++
			continue
		}
		assignments = append(assignments, fmt.Sprintf("result%d", nextResult))
		nextResult++
	}
	callExpr := r.goCallExpression(call)
	if len(assignments) == 0 {
		r.line("%s%s", indent, callExpr)
	} else {
		r.line("%s%s := %s", indent, strings.Join(assignments, ", "), callExpr)
	}
	switch call.ErrorCount {
	case 0:
	case 1:
		r.line("%sif goErr0 != nil { return nil, fgbGoError(%s, goErr0) }", indent, methodExpr)
	default:
		r.line("%svar fgbErrs []any", indent)
		for index := 0; index < call.ErrorCount; index++ {
			r.line("%sif goErr%d != nil { fgbErrs = append(fgbErrs, goErr%d.Error()) }", indent, index, index)
		}
		r.line("%sif len(fgbErrs) != 0 { return nil, fgbGoErrors(%s, fgbErrs) }", indent, methodExpr)
	}
}

func (r *goRenderer) renderReflectiveGoCallStatement(call *callModel, indent, methodExpr string) {
	target := call.GoTarget
	if call.Receiver != nil {
		target = "receiver." + call.GoTarget
	}
	arguments := r.goCallArguments(call)
	r.line("%sfgbValues, fgbReflectErr := fgbReflectCall(%s, []any{%s})", indent, target, strings.Join(arguments, ", "))
	r.line("%sif fgbReflectErr != nil { return nil, fgbInvalidArguments(%s, fgbReflectErr) }", indent, methodExpr)
	if len(call.resultShape()) == 0 {
		r.line("%s_ = fgbValues", indent)
	}
	nextResult, nextError := 0, 0
	for position, isError := range call.resultShape() {
		if isError {
			r.line("%sgoErr%d := fgbReflectError(fgbValues[%d])", indent, nextError, position)
			nextError++
			continue
		}
		result := call.Results[nextResult]
		r.line("%sresult%d, err := fgbReflectResult[%s](fgbValues[%d])", indent, nextResult, r.goType(result.Type.Original), position)
		r.line("%sif err != nil { return nil, &fgbCallError{Code: \"encode_error\", Message: err.Error(), Details: map[any]any{\"method\": %s}} }", indent, methodExpr)
		nextResult++
	}
	switch call.ErrorCount {
	case 0:
	case 1:
		r.line("%sif goErr0 != nil { return nil, fgbGoError(%s, goErr0) }", indent, methodExpr)
	default:
		r.line("%svar fgbErrs []any", indent)
		for index := 0; index < call.ErrorCount; index++ {
			r.line("%sif goErr%d != nil { fgbErrs = append(fgbErrs, goErr%d.Error()) }", indent, index, index)
		}
		r.line("%sif len(fgbErrs) != 0 { return nil, fgbGoErrors(%s, fgbErrs) }", indent, methodExpr)
	}
}

func (r *goRenderer) renderDispatch() {
	r.line("func fgbDispatch(call fgbMethodCall, transfer *fgbOpaqueTransfer) (any, *fgbCallError) {")
	r.line("\tswitch call.Method {")
	for _, call := range r.unit.Calls {
		r.line("\tcase %s:", strconv.Quote(call.WireName))
		r.renderCallContextSetup(call, "\t\t")
		argumentCount := len(call.Params)
		if call.Receiver != nil {
			argumentCount++
		}
		if argumentCount == 0 {
			r.line("\t\tif _, err := fgbRequireArgs(call.Arguments, 0); err != nil { return nil, fgbInvalidArguments(call.Method, err) }")
		} else {
			r.line("\t\targs, err := fgbRequireArgs(call.Arguments, %d)", argumentCount)
			r.line("\t\tif err != nil { return nil, fgbInvalidArguments(call.Method, err) }")
		}
		argOffset := 0
		if call.Receiver != nil {
			r.line("\t\treceiver, err := fgbDecode%d(args[0], \"receiver\")", call.Receiver.ID)
			r.line("\t\tif err != nil { return nil, fgbInvalidArguments(call.Method, err) }")
			argOffset = 1
		}
		for index, param := range call.Params {
			if param.Type.Kind == kindStreamSink && param.Type.ChannelStream {
				// Handled by renderStreamChannelSetup below.
				continue
			}
			if param.Type.Kind == kindCallback {
				r.line("\t\traw%d, err := fgbAsInt64(args[%d], %s)", index, index+argOffset, strconv.Quote(param.DartName))
				r.line("\t\targ%d := fgbMakeCallback%d(fgbCtx, raw%d)", index, param.Type.ID, index)
			} else {
				r.line("\t\targ%d, err := fgbDecode%d(args[%d], %s)", index, param.Type.ID, index+argOffset, strconv.Quote(param.DartName))
			}
			r.line("\t\tif err != nil { return nil, fgbInvalidArguments(call.Method, err) }")
		}
		r.renderStreamChannelSetup(call, "\t\t", func(index int) string {
			return fmt.Sprintf("fgbMustStreamHandle(args[%d])", index+argOffset)
		})
		r.renderGoCallStatement(call, "\t\t", "call.Method")
		switch len(call.Results) {
		case 0:
			r.line("\t\treturn nil, nil")
		case 1:
			r.line("\t\tencoded, err := fgbEncode%d(result0, 0, transfer)", call.Results[0].Type.ID)
			r.line("\t\tif err != nil { return nil, &fgbCallError{Code: \"encode_error\", Message: err.Error(), Details: map[any]any{\"method\": call.Method}} }")
			r.line("\t\treturn encoded, nil")
		default:
			// Several results travel as one list and become a Dart record.
			for index, result := range call.Results {
				r.line("\t\tencoded%d, err := fgbEncode%d(result%d, 0, transfer)", index, result.Type.ID, index)
				r.line("\t\tif err != nil { return nil, &fgbCallError{Code: \"encode_error\", Message: err.Error(), Details: map[any]any{\"method\": call.Method}} }")
			}
			encoded := make([]string, len(call.Results))
			for index := range call.Results {
				encoded[index] = fmt.Sprintf("encoded%d", index)
			}
			r.line("\t\treturn []any{%s}, nil", strings.Join(encoded, ", "))
		}
	}
	r.line("\tdefault:")
	r.raw("\t\treturn nil, &fgbCallError{Code: \"method_not_found\", Message: fmt.Sprintf(\"unknown method %q\", call.Method)}")
	r.line("\t}")
	r.line("}")
}

func (r *goRenderer) goCallExpression(call *callModel) string {
	var target string
	if call.Receiver == nil {
		target = call.GoTarget
	} else {
		target = "receiver." + call.GoTarget
	}
	return target + "(" + strings.Join(r.goCallArguments(call), ", ") + ")"
}

func (r *goRenderer) goCallArguments(call *callModel) []string {
	// call.Params holds only the parameters that cross the wire; a
	// context.Context is supplied by the bridge and spliced back in here.
	total := len(call.Params)
	if call.ContextIndex >= 0 {
		total++
	}
	args := make([]string, 0, total)
	next := 0
	for position := 0; position < total; position++ {
		if position == call.ContextIndex {
			args = append(args, "fgbCtx")
			continue
		}
		args = append(args, fmt.Sprintf("arg%d", next))
		next++
	}
	return args
}

// renderStreamChannelSetup emits the bridge-owned plumbing for `chan<- T`
// parameters and for a context.Context: the channel is created and drained
// here and closed once the call returns, and the context is cancelled as soon
// as the Dart side stops listening.
func (r *goRenderer) renderStreamChannelSetup(call *callModel, indent string, handleExpr func(index int) string) {
	var streamHandles []string
	for index, param := range call.Params {
		if param.Type.Kind != kindStreamSink {
			continue
		}
		// Every async call has an internal context. The handle ties cancellation
		// to it even when the user function does not accept context.Context.
		needsHandle := param.Type.ChannelStream || call.Mode == bridgemodel.CallModeAsync
		if needsHandle {
			r.line("%shandle%d := %s", indent, index, handleExpr(index))
			if call.Mode == bridgemodel.CallModeAsync {
				streamHandles = append(streamHandles, fmt.Sprintf("handle%d", index))
			}
		}
		if param.Type.ChannelStream {
			r.line("%sarg%d := fgbMakeStreamChannel%d(handle%d)", indent, index, param.Type.ID, index)
			r.line("%sdefer fgbCloseStreamChannel%d(arg%d)", indent, param.Type.ID, index)
		}
	}
	if call.Mode != bridgemodel.CallModeAsync {
		return
	}
	if len(streamHandles) != 0 {
		// Cancelling the Dart subscription cancels the Go context, which is
		// how a cooperative producer learns to stop early. Register every
		// sink so cancelling any subscription stops the call. Capture the
		// generation once so the deferred cleanup cannot target a later one.
		r.line("%sfgbStreamGen := fgbCurrentStreamGeneration()", indent)
		for _, handle := range streamHandles {
			r.line("%sfgbRegisterStreamCancel(fgbStreamGen, %s, fgbCancel)", indent, handle)
			r.line("%sdefer fgbUnregisterStreamCancel(fgbStreamGen, %s)", indent, handle)
		}
	}
}

func (r *goRenderer) renderCallContextSetup(call *callModel, indent string) {
	if call.Mode != bridgemodel.CallModeAsync {
		return
	}
	r.line("%sfgbCtx, fgbCancel := context.WithCancel(context.Background())", indent)
	r.line("%sdefer fgbCancel()", indent)
	r.line("%s_ = fgbCtx", indent)
}

// renderStreamChannelHelpers emits the typed drain/close pair for one channel
// stream type.
func (r *goRenderer) renderStreamChannelHelpers(typ *wireType) {
	elemGo := r.goType(typ.Stream.Original)
	r.line("func fgbMakeStreamChannel%d(handle int64) chan %s {", typ.ID, elemGo)
	r.line("\t// Same generation guard as the sink factory: a hot restart retires")
	r.line("\t// this producer along with the isolate that started it.")
	r.line("\tgeneration := fgbCurrentStreamGeneration()")
	r.line("\tch := make(chan %s, 16)", elemGo)
	r.line("\tgo func() {")
	r.line("\t\t// Keep draining even after the Dart side stopped listening, so a")
	r.line("\t\t// producer that ignores ctx.Done() never blocks forever.")
	r.line("\t\tfor value := range ch {")
	r.line("\t\t\ttransfer := &fgbOpaqueTransfer{}")
	r.line("\t\t\tencoded, err := fgbEncode%d(value, 0, transfer)", typ.Stream.ID)
	r.line("\t\t\tif err != nil { transfer.rollback(); continue }")
	r.line("\t\t\tfgbPostStreamEvent(generation, handle, 0, fgbStreamPayload{value: encoded, transfer: transfer})")
	r.line("\t\t}")
	r.line("\t\tfgbReleaseStreamSink(generation, handle)")
	r.line("\t}()")
	r.line("\treturn ch")
	r.line("}")
	r.line("")
	r.line("// fgbCloseStreamChannel%d ends the stream once the call returns; a user", typ.ID)
	r.line("// function that closed the channel itself is tolerated.")
	r.line("func fgbCloseStreamChannel%d(ch chan %s) {", typ.ID, elemGo)
	r.line("\tdefer func() { _ = recover() }()")
	r.line("\tclose(ch)")
	r.line("}")
}

func (r *goRenderer) renderSignedRangeCheck(typ *wireType, goType string) {
	switch typ.BasicKind {
	case types.Int8:
		r.line("\tif raw < -128 || raw > 127 { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of int8 range\", path) }", goType)
	case types.Int16:
		r.line("\tif raw < -32768 || raw > 32767 { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of int16 range\", path) }", goType)
	case types.Int32:
		r.line("\tif raw < -2147483648 || raw > 2147483647 { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of int32 range\", path) }", goType)
	case types.Int:
		r.line("\tif int64(int(raw)) != raw { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of int range\", path) }", goType)
	}
}

func (r *goRenderer) renderUnsignedRangeCheck(typ *wireType, goType string) {
	switch typ.BasicKind {
	case types.Uint8:
		r.line("\tif raw > 255 { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of uint8 range\", path) }", goType)
	case types.Uint16:
		r.line("\tif raw > 65535 { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of uint16 range\", path) }", goType)
	case types.Uint32:
		r.line("\tif raw > 4294967295 { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of uint32 range\", path) }", goType)
	case types.Uint, types.Uintptr:
		r.line("\tif uint64(%s(raw)) != raw { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of %s range\", path) }", goType, goType, goType)
	}
}

func (r *goRenderer) renderBigIntDecoder(typ *wireType, goType string) {
	_, pointer := typ.Original.(*types.Pointer)
	if pointer {
		r.line("\tif value == nil { return nil, nil }")
	}
	r.line("\tvar parsed *big.Int")
	r.line("\tswitch raw := value.(type) {")
	r.line("\tcase *big.Int:")
	r.line("\t\tparsed = new(big.Int).Set(raw)")
	r.line("\tcase string:")
	r.line("\t\tvar ok bool")
	r.line("\t\tparsed, ok = new(big.Int).SetString(raw, 16)")
	r.line("\t\tif !ok { var zero %s; return zero, fmt.Errorf(\"%%s: invalid hexadecimal BigInt\", path) }", goType)
	r.line("\tdefault:")
	r.line("\t\tvar zero %s; return zero, fgbTypeError(path, \"BigInt hexadecimal string\", value)", goType)
	r.line("\t}")
	if pointer {
		r.line("\treturn parsed, nil")
	} else {
		r.line("\treturn *parsed, nil")
	}
}

func (r *goRenderer) renderBigIntEncoder(typ *wireType) {
	_, pointer := typ.Original.(*types.Pointer)
	if pointer {
		r.line("\tif value == nil { return nil, nil }")
		r.line("\treturn new(big.Int).Set(value), nil")
	} else {
		r.line("\treturn new(big.Int).Set(&value), nil")
	}
}

func (r *goRenderer) renderDurationFromMicroseconds(goType, expression string) {
	r.line("\tconst maxDurationMicroseconds = int64(^uint64(0)>>1) / int64(time.Microsecond)")
	r.line("\tif %s < -maxDurationMicroseconds || %s > maxDurationMicroseconds { var zero %s; return zero, fmt.Errorf(\"%%s: duration out of time.Duration range\", path) }", expression, expression, goType)
	r.line("\treturn %s(%s) * %s(time.Microsecond), nil", goType, expression, goType)
}

// renderURLParse turns the wire text back into a url.URL. url.Parse yields a
// pointer, and the empty string parses into the zero value, so the zero URL
// survives a round trip without a special case.
func (r *goRenderer) renderURLParse(goType, expression string) {
	r.line("\tparsed, err := url.Parse(%s)", expression)
	r.line("\tif err != nil { var zero %s; return zero, fmt.Errorf(\"%%s: invalid URI: %%w\", path, err) }", goType)
	r.line("\treturn *parsed, nil")
}

func (r *goRenderer) goType(typ types.Type) string {
	return types.TypeString(typ, func(pkg *types.Package) string {
		if pkg == nil {
			return ""
		}
		if pkg.Path() == r.unit.PackagePath {
			if r.unit.Direct {
				return ""
			}
			return "api"
		}
		switch pkg.Path() {
		case "time":
			return "time"
		case "math/big":
			return "big"
		case r.unit.SupportPackagePath:
			return "fgbrt"
		case "sync/atomic":
			return "atomic"
		default:
			if alias := r.unit.GoPackageAliases[pkg.Path()]; alias != "" {
				return alias
			}
			return pkg.Name()
		}
	})
}

func (r *goRenderer) line(format string, args ...any) {
	if len(args) == 0 {
		r.buffer.WriteString(format)
	} else {
		fmt.Fprintf(&r.buffer, format, args...)
	}
	r.buffer.WriteByte('\n')
}

func (r *goRenderer) raw(value string) {
	r.buffer.WriteString(value)
	r.buffer.WriteByte('\n')
}
