package generator

import (
	"bytes"
	"fmt"
	"go/types"
	"strconv"
	"strings"
)

type goRenderer struct {
	unit   *unit
	buffer bytes.Buffer
}

func renderGo(unit *unit) ([]byte, error) {
	r := &goRenderer{unit: unit}
	if unit.GoPreamble != "" {
		r.raw(strings.TrimRight(unit.GoPreamble, "\n"))
		r.line("")
	}
	r.line("// Code generated by flutter_go_bridge_codegen. DO NOT EDIT.")
	r.line("package main")
	r.line("")
	r.line("/*")
	cgoPreamble := strings.TrimSpace(goCgoPreambleSource)
	if hasCstDcoCalls(unit) {
		cgoPreamble += "\n\n" + cstForwardDeclarations(unit)
	}
	r.raw(cgoPreamble)
	r.line("*/")
	r.line(`import "C"`)
	r.line("")
	r.line("import (")
	imports := []string{
		"bytes", "encoding/binary", "fmt", "io", "math/big", "reflect",
		"runtime", "runtime/debug", "sync", "sync/atomic", "unsafe",
	}
	// The stream runtime always carries the cancellation plumbing, so context
	// is part of the fixed import set.
	imports = append(imports, "context")
	if unit.UsesTime {
		imports = append(imports, "time")
	}
	if unit.UsesInternetIP {
		imports = append(imports, "net/netip")
	}
	if unit.UsesUUID {
		imports = append(imports, "github.com/gofrs/uuid/v5")
	}
	for _, item := range imports {
		r.line("\t%q", item)
	}
	if unit.UsesRuntimePackage {
		// The exported ABI already owns the identifier `fgb` (the sync
		// entrypoint), so the runtime package needs an alias.
		r.line("\tfgbrt %q", unit.SupportPackagePath)
	}
	if !unit.Direct {
		r.line("\tapi %q", unit.PackagePath)
	}
	for _, item := range unit.ExternalImports {
		r.line("\t%s %q", item.Alias, item.Path)
	}
	r.line(")")
	r.line("")
	r.raw(strings.TrimSpace(goRuntimeSource))
	r.line("")
	if unit.NeedsMain {
		r.line("// Required for c-shared and c-archive build modes.")
		r.line("func main() {}")
		r.line("")
	}
	if hasCstDcoCalls(unit) {
		r.renderCstDecoders()
		r.renderDcoEncoders()
	}

	for _, typ := range unit.Types {
		if err := r.renderDecoder(typ); err != nil {
			return nil, err
		}
		r.line("")
		if err := r.renderEncoder(typ); err != nil {
			return nil, err
		}
		r.line("")
	}
	for _, typ := range unit.Types {
		if typ.Kind == kindCallback {
			r.renderCallbackFactory(typ)
			r.line("")
		}
		if typ.Kind == kindStreamSink {
			if typ.ChannelStream {
				r.renderStreamChannelHelpers(typ)
			} else {
				r.renderStreamSinkFactory(typ)
			}
			r.line("")
		}
	}
	r.renderDispatch()
	// Keep the CST ABI present even for a package whose current API only uses
	// the Standard fallback; the Dart runtime can then use one stable binding
	// layout and future regenerated calls do not change symbol discovery.
	r.renderCstDispatch()
	return r.buffer.Bytes(), nil
}

func (r *goRenderer) renderDecoder(typ *wireType) error {
	goType := r.goType(typ.Original)
	r.line("func fgbDecode%d(value any, path string) (%s, error) {", typ.ID, goType)
	switch typ.Kind {
	case kindBool:
		r.line("\tresult, ok := value.(bool)")
		r.line("\tif !ok { return false, fgbTypeError(path, \"bool\", value) }")
		r.line("\treturn result, nil")
	case kindString:
		r.line("\tresult, ok := value.(string)")
		r.line("\tif !ok { return \"\", fgbTypeError(path, \"string\", value) }")
		r.line("\treturn result, nil")
	case kindSigned:
		r.line("\traw, err := fgbAsInt64(value, path)")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.renderSignedRangeCheck(typ, goType)
		r.line("\treturn %s(raw), nil", goType)
	case kindUnsigned:
		r.line("\traw, err := fgbAsUint64(value, path)")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.renderUnsignedRangeCheck(typ, goType)
		r.line("\treturn %s(raw), nil", goType)
	case kindFloat:
		r.line("\traw, err := fgbAsFloat64(value, path)")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.line("\treturn %s(raw), nil", goType)
	case kindBigInt:
		r.renderBigIntDecoder(typ, goType)
	case kindTime:
		r.line("\traw, ok := value.(string)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"RFC3339 string\", value) }", goType)
		r.line("\tresult, err := time.Parse(time.RFC3339Nano, raw)")
		r.line("\tif err != nil { var zero %s; return zero, fmt.Errorf(\"%%s: invalid time: %%w\", path, err) }", goType)
		r.line("\treturn result, nil")
	case kindInternetIP:
		r.line("\traw, ok := value.(string)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"IP string\", value) }", goType)
		r.line("\tif raw == \"\" { return netip.Addr{}, nil }")
		r.line("\tresult, err := netip.ParseAddr(raw)")
		r.line("\tif err != nil { var zero %s; return zero, fmt.Errorf(\"%%s: invalid IP: %%w\", path, err) }", goType)
		r.line("\treturn result, nil")
	case kindUUID:
		r.line("\traw, ok := value.(string)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"UUID string\", value) }", goType)
		r.line("\tresult, err := uuid.FromString(raw)")
		r.line("\tif err != nil { var zero %s; return zero, fmt.Errorf(\"%%s: invalid UUID: %%w\", path, err) }", goType)
		r.line("\treturn result, nil")
	case kindDuration:
		r.line("\traw, err := fgbAsInt64(value, path)")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.renderDurationFromMicroseconds(goType, "raw")
	case kindAny:
		r.line("\treturn value, nil")
	case kindPointer:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\tdecoded, err := fgbDecode%d(value, path)", typ.Elem.ID)
		r.line("\tif err != nil { return nil, err }")
		r.line("\treturn &decoded, nil")
	case kindBytes:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\traw, ok := value.([]byte)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"Uint8List\", value) }", goType)
		r.renderTypedListCopy(goType)
	case kindInt32List:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\traw, ok := value.([]int32)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"Int32List\", value) }", goType)
		r.renderTypedListCopy(goType)
	case kindInt64List:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\traw, ok := value.([]int64)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"Int64List\", value) }", goType)
		r.renderTypedListCopy(goType)
	case kindFloat64List:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\traw, ok := value.([]float64)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"Float64List\", value) }", goType)
		r.renderTypedListCopy(goType)
	case kindSlice:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\traw, ok := value.([]any)")
		r.line("\tif !ok { return nil, fgbTypeError(path, \"List\", value) }")
		r.line("\tresult := make(%s, len(raw))", goType)
		r.line("\tfor index, item := range raw {")
		r.line("\t\tdecoded, err := fgbDecode%d(item, fmt.Sprintf(\"%%s[%%d]\", path, index))", typ.Elem.ID)
		r.line("\t\tif err != nil { return nil, err }")
		r.line("\t\tresult[index] = decoded")
		r.line("\t}")
		r.line("\treturn result, nil")
	case kindArray:
		r.line("\traw, ok := value.([]any)")
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"List\", value) }", goType)
		r.line("\tif len(raw) != %d { var zero %s; return zero, fmt.Errorf(\"%%s: expected %d elements, got %%d\", path, len(raw)) }", typ.Length, goType, typ.Length)
		r.line("\tvar result %s", goType)
		r.line("\tfor index, item := range raw {")
		r.line("\t\tdecoded, err := fgbDecode%d(item, fmt.Sprintf(\"%%s[%%d]\", path, index))", typ.Elem.ID)
		r.line("\t\tif err != nil { var zero %s; return zero, err }", goType)
		r.line("\t\tresult[index] = decoded")
		r.line("\t}")
		r.line("\treturn result, nil")
	case kindMap:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\traw, ok := value.(map[any]any)")
		r.line("\tif !ok { return nil, fgbTypeError(path, \"Map\", value) }")
		r.line("\tresult := make(%s, len(raw))", goType)
		r.line("\tfor rawKey, rawValue := range raw {")
		r.line("\t\tkey, err := fgbDecode%d(rawKey, path+\".<key>\")", typ.Key.ID)
		r.line("\t\tif err != nil { return nil, err }")
		r.line("\t\tdecoded, err := fgbDecode%d(rawValue, fmt.Sprintf(\"%%s[%%v]\", path, key))", typ.Elem.ID)
		r.line("\t\tif err != nil { return nil, err }")
		r.line("\t\tresult[key] = decoded")
		r.line("\t}")
		r.line("\treturn result, nil")
	case kindStruct:
		fields := typ.Struct.allFields()
		if len(fields) == 0 {
			r.line("\t_, ok := value.(map[any]any)")
		} else {
			r.line("\traw, ok := value.(map[any]any)")
		}
		r.line("\tif !ok { var zero %s; return zero, fgbTypeError(path, \"Map\", value) }", goType)
		r.line("\tvar result %s", goType)
		for _, field := range fields {
			r.line("\tdecoded%s, err := fgbDecode%d(raw[%s], path+%s)", field.GoName, field.Type.ID, strconv.Quote(field.WireName), strconv.Quote("."+field.WireName))
			r.line("\tif err != nil { var zero %s; return zero, err }", goType)
			r.line("\tresult.%s = decoded%s", field.GoName, field.GoName)
		}
		r.line("\treturn result, nil")
	case kindOpaque:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\thandle, err := fgbAsHandle(value, path)")
		r.line("\tif err != nil { return nil, err }")
		r.line("\traw, ok := fgbHandles.Load(handle)")
		r.raw("\tif !ok { return nil, fmt.Errorf(\"%s: unknown or released handle %d\", path, handle) }")
		r.line("\tresult, ok := raw.(%s)", goType)
		r.raw("\tif !ok { return nil, fmt.Errorf(\"%s: handle %d has incompatible Go type %T\", path, handle, raw) }")
		r.line("\treturn result, nil")
	case kindDartOpaque:
		r.line("\traw, err := fgbAsInt64(value, path)")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.line("\tif raw == 0 { var zero %s; return zero, fmt.Errorf(\"%%s: invalid DartOpaque handle 0\", path) }", goType)
		r.line("\treturn fgbrt.NewDartOpaque(raw, fgbReleaseDartOpaque), nil")
	case kindCallback:
		r.line("\traw, err := fgbAsInt64(value, path)")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.line("\treturn fgbMakeCallback%d(raw), nil", typ.ID)
	case kindStreamSink:
		if typ.ChannelStream {
			// Channel streams are wired up by the dispatcher, which owns the
			// channel; there is nothing to decode from a value here.
			r.line("\tvar zero %s", goType)
			r.line("\treturn zero, fmt.Errorf(\"%%s: channel streams are only supported as direct call parameters\", path)")
			break
		}
		r.line("\traw, err := fgbAsInt64(value, path)")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.line("\tif raw == 0 { var zero %s; return zero, fmt.Errorf(\"%%s: invalid stream handle 0\", path) }", goType)
		r.line("\treturn fgbMakeStreamSink%d(raw), nil", typ.ID)
	case kindInterface:
		// A tagged union: [implementorIndex, payload].
		r.line("\tif value == nil { var zero %s; return zero, nil }", goType)
		r.line("\traw, ok := value.([]any)")
		r.line("\tif !ok || len(raw) != 2 { var zero %s; return zero, fgbTypeError(path, \"interface envelope\", value) }", goType)
		r.line("\ttag, err := fgbAsInt64(raw[0], path+\".tag\")")
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.line("\tswitch tag {")
		for index, implementor := range typ.Interface.Implementors {
			r.line("\tcase %d:", index)
			r.line("\t\treturn fgbDecode%d(raw[1], path)", implementor.Type.ID)
		}
		r.line("\t}")
		r.line("\tvar zero %s; return zero, fmt.Errorf(\"%%s: unknown %s implementation %%d\", path, tag)", goType, typ.Interface.GoName)
	case kindNamed:
		r.line("\tdecoded, err := fgbDecode%d(value, path)", typ.Named.Underlying.ID)
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.line("\treturn %s(decoded), nil", goType)
	case kindAtomic:
		r.line("\tdecoded, err := fgbDecode%d(value, path)", typ.Atomic.Value.ID)
		r.line("\tif err != nil { var zero %s; return zero, err }", goType)
		r.line("\tvar result %s", goType)
		r.line("\tresult.Store(decoded)")
		r.line("\treturn result, nil")
	default:
		return fmt.Errorf("no Go decoder for %s", typ.Kind)
	}
	r.line("}")
	return nil
}

// renderTypedListCopy copies a decoded typed list. `append(T(nil), raw...)`
// would look equivalent but returns nil for an empty input, which would erase
// the difference between an empty list and a nil one.
func (r *goRenderer) renderTypedListCopy(goType string) {
	r.line("\tresult := make(%s, len(raw))", goType)
	r.line("\tcopy(result, raw)")
	r.line("\treturn result, nil")
}

func (r *goRenderer) renderEncoder(typ *wireType) error {
	goType := r.goType(typ.Original)
	r.line("func fgbEncode%d(value %s) (any, error) {", typ.ID, goType)
	switch typ.Kind {
	case kindBool, kindString:
		r.line("\treturn value, nil")
	case kindSigned:
		if typ.BitSize <= 32 && typ.BasicKind != types.Int {
			r.line("\treturn int32(value), nil")
		} else {
			r.line("\treturn int64(value), nil")
		}
	case kindUnsigned:
		if typ.DartType == "BigInt" {
			r.line("\treturn new(big.Int).SetUint64(uint64(value)), nil")
		} else if typ.BitSize <= 16 {
			r.line("\treturn int32(value), nil")
		} else {
			r.line("\treturn int64(value), nil")
		}
	case kindFloat:
		r.line("\treturn float64(value), nil")
	case kindBigInt:
		r.renderBigIntEncoder(typ)
	case kindTime:
		r.line("\treturn value.Format(time.RFC3339Nano), nil")
	case kindInternetIP:
		// netip.Addr.String returns an empty string for the invalid zero value,
		// which InternetAddress represents without changing pointer nullability.
		r.line("\treturn value.String(), nil")
	case kindUUID:
		r.line("\treturn value.String(), nil")
	case kindDuration:
		r.line("\treturn int64(value / time.Microsecond), nil")
	case kindAny:
		r.line("\treturn fgbNormalize(value, 0)")
	case kindPointer:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\treturn fgbEncode%d(*value)", typ.Elem.ID)
	case kindBytes, kindInt32List, kindInt64List, kindFloat64List:
		r.line("\tif value == nil { return %s{}, nil }", goType)
		r.line("\treturn value, nil")
	case kindSlice:
		r.line("\tif value == nil { return []any{}, nil }")
		r.line("\tresult := make([]any, len(value))")
		r.line("\tfor index, item := range value {")
		r.line("\t\tencoded, err := fgbEncode%d(item)", typ.Elem.ID)
		r.raw("\t\tif err != nil { return nil, fmt.Errorf(\"element %d: %w\", index, err) }")
		r.line("\t\tresult[index] = encoded")
		r.line("\t}")
		r.line("\treturn result, nil")
	case kindArray:
		r.line("\tresult := make([]any, len(value))")
		r.line("\tfor index, item := range value {")
		r.line("\t\tencoded, err := fgbEncode%d(item)", typ.Elem.ID)
		r.raw("\t\tif err != nil { return nil, fmt.Errorf(\"element %d: %w\", index, err) }")
		r.line("\t\tresult[index] = encoded")
		r.line("\t}")
		r.line("\treturn result, nil")
	case kindMap:
		r.line("\tif value == nil { return map[any]any{}, nil }")
		r.line("\tresult := make(map[any]any, len(value))")
		r.line("\tfor key, item := range value {")
		r.line("\t\tencodedKey, err := fgbEncode%d(key)", typ.Key.ID)
		r.raw("\t\tif err != nil { return nil, fmt.Errorf(\"map key: %w\", err) }")
		r.line("\t\tencoded, err := fgbEncode%d(item)", typ.Elem.ID)
		r.raw("\t\tif err != nil { return nil, fmt.Errorf(\"map value: %w\", err) }")
		r.line("\t\tresult[encodedKey] = encoded")
		r.line("\t}")
		r.line("\treturn result, nil")
	case kindStruct:
		fields := typ.Struct.allFields()
		r.line("\tresult := make(map[any]any, %d)", len(fields))
		for _, field := range fields {
			// A nullable field keeps its nil: the shared encoders normalize a
			// nil slice or map to an empty one, which would erase exactly the
			// distinction the field was marked for.
			if field.Nullable {
				r.line("\tvar encoded%s any", field.GoName)
				r.line("\tif value.%s != nil {", field.GoName)
				r.line("\t\traw, err := fgbEncode%d(value.%s)", field.Type.ID, field.GoName)
				r.line("\t\tif err != nil { return nil, fmt.Errorf(%s+\": %%w\", err) }", strconv.Quote(field.WireName))
				r.line("\t\tencoded%s = raw", field.GoName)
				r.line("\t}")
				r.line("\tresult[%s] = encoded%s", strconv.Quote(field.WireName), field.GoName)
				continue
			}
			r.line("\tencoded%s, err := fgbEncode%d(value.%s)", field.GoName, field.Type.ID, field.GoName)
			r.line("\tif err != nil { return nil, fmt.Errorf(%s+\": %%w\", err) }", strconv.Quote(field.WireName))
			r.line("\tresult[%s] = encoded%s", strconv.Quote(field.WireName), field.GoName)
		}
		r.line("\treturn result, nil")
	case kindOpaque:
		r.line("\tif value == nil { return nil, nil }")
		r.line("\thandle := fgbNextHandle.Add(1)")
		r.line("\tif handle == 0 { return nil, fmt.Errorf(\"opaque handle space exhausted\") }")
		r.line("\tfgbHandles.Store(handle, value)")
		r.line("\treturn int64(handle), nil")
	case kindDartOpaque:
		r.line("\tif !value.IsValid() { return nil, fmt.Errorf(\"cannot encode an invalid DartOpaque\") }")
		r.line("\treturn value.Handle(), nil")
	case kindCallback:
		r.line("\treturn nil, fmt.Errorf(\"function values cannot be encoded\")")
	case kindStreamSink:
		r.line("\treturn nil, fmt.Errorf(\"stream sinks cannot be sent to Dart\")")
	case kindInterface:
		// Tag the value with the concrete type so the other side knows which
		// decoder to use. Most-derived first is irrelevant here: Go's type
		// switch matches the dynamic type exactly.
		r.line("\tif value == nil { return nil, fmt.Errorf(\"cannot send a nil %s to Dart\") }", typ.Interface.GoName)
		r.line("\tswitch typed := value.(type) {")
		for index, implementor := range typ.Interface.Implementors {
			r.line("\tcase %s:", r.goType(implementor.Type.Original))
			r.line("\t\tencoded, err := fgbEncode%d(typed)", implementor.Type.ID)
			r.line("\t\tif err != nil { return nil, err }")
			r.line("\t\treturn []any{int64(%d), encoded}, nil", index)
		}
		r.line("\t}")
		r.raw("\treturn nil, fmt.Errorf(\"%T does not implement a bridged " + typ.Interface.GoName + " implementation\", value)")
	case kindNamed:
		underlyingGo := r.goType(typ.Named.Underlying.Original)
		r.line("\treturn fgbEncode%d(%s(value))", typ.Named.Underlying.ID, underlyingGo)
	case kindAtomic:
		r.line("\treturn fgbEncode%d(value.Load())", typ.Atomic.Value.ID)
	default:
		return fmt.Errorf("no Go encoder for %s", typ.Kind)
	}
	r.line("}")
	return nil
}

// renderCallbackFactory synthesizes the Go func value handed to user code for
// a Dart-supplied closure. Invoking it encodes the arguments, posts a request
// to the Dart event loop, and parks the goroutine until Dart replies - which
// is why callbacks are restricted to //fgb:async calls. Without a trailing
// `error` result, transport and Dart-side failures panic; the dispatch
// recover() then reports them to the original caller.
func (r *goRenderer) renderCallbackFactory(typ *wireType) {
	callback := typ.Callback
	goType := r.goType(typ.Original)
	r.line("func fgbMakeCallback%d(handle int64) %s {", typ.ID, goType)
	r.line("\t// Handle 0 means Dart passed null for a //fgb:nullable callback.")
	r.line("\tif handle == 0 { return nil }")
	r.line("\tref := fgbNewCallbackRef(handle)")

	params := make([]string, len(callback.Params))
	for index, param := range callback.Params {
		params[index] = fmt.Sprintf("a%d %s", index, r.goType(param.Original))
	}
	var results []string
	if callback.Result != nil {
		results = append(results, r.goType(callback.Result.Original))
	}
	if callback.HasError {
		results = append(results, "error")
	}
	resultText := ""
	switch len(results) {
	case 1:
		resultText = " " + results[0]
	case 2:
		resultText = " (" + strings.Join(results, ", ") + ")"
	}
	r.line("\treturn func(%s)%s {", strings.Join(params, ", "), resultText)

	fail := func(wrap string) {
		switch {
		case callback.HasError && callback.Result != nil:
			r.line("\t\tif err != nil { var zero %s; return zero, %s }", r.goType(callback.Result.Original), wrap)
		case callback.HasError:
			r.line("\t\tif err != nil { return %s }", wrap)
		default:
			r.line("\t\tif err != nil { panic(%s) }", wrap)
		}
	}

	arguments := make([]string, len(callback.Params))
	for index, param := range callback.Params {
		r.line("\t\tencoded%d, err := fgbEncode%d(a%d)", index, param.ID, index)
		fail(fmt.Sprintf("fmt.Errorf(\"callback argument %d: %%w\", err)", index))
		arguments[index] = fmt.Sprintf("encoded%d", index)
	}
	r.line("\t\treply, err := fgbInvokeCallback(handle, []any{%s})", strings.Join(arguments, ", "))
	r.line("\t\truntime.KeepAlive(ref)")
	fail("err")
	if callback.Result != nil {
		r.line("\t\tresult, err := fgbDecode%d(reply, \"callback result\")", callback.Result.ID)
		fail("fmt.Errorf(\"callback result: %w\", err)")
		if callback.HasError {
			r.line("\t\treturn result, nil")
		} else {
			r.line("\t\treturn result")
		}
	} else {
		r.line("\t\t_ = reply")
		if callback.HasError {
			r.line("\t\treturn nil")
		}
	}
	r.line("\t}")
	r.line("}")
}

// renderStreamSinkFactory binds the generated element encoder to the runtime
// sink so user code only sees fgb.StreamSink[T].
func (r *goRenderer) renderStreamSinkFactory(typ *wireType) {
	r.line("func fgbMakeStreamSink%d(handle int64) %s {", typ.ID, r.goType(typ.Original))
	r.line("\t// Capture the isolate generation at creation time: a hot restart")
	r.line("\t// retires this sink even if its producer goroutine keeps running.")
	r.line("\tgeneration := fgbCurrentStreamGeneration()")
	r.line("\treturn fgbrt.NewStreamSink(handle, func(value %s) (any, error) {", r.goType(typ.Stream.Original))
	r.line("\t\treturn fgbEncode%d(value)", typ.Stream.ID)
	r.line("\t}, func(handle int64, kind int32, payload any) bool {")
	r.line("\t\treturn fgbPostStreamEvent(generation, handle, kind, payload)")
	r.line("\t}, func(handle int64) {")
	r.line("\t\tfgbReleaseStreamSink(generation, handle)")
	r.line("\t})")
	r.line("}")
}

// renderGoCallStatement emits the Go call plus the shared error handling.
// Non-error results are bound to result<k>, every `error` result to goErr<j>;
// any non-nil error fails the call, and several are reported together.
func (r *goRenderer) renderGoCallStatement(call *callModel, indent, methodExpr string) {
	assignments := make([]string, 0, len(call.Results)+call.ErrorCount)
	nextResult, nextError := 0, 0
	for _, isError := range call.resultShape() {
		if isError {
			assignments = append(assignments, fmt.Sprintf("goErr%d", nextError))
			nextError++
			continue
		}
		assignments = append(assignments, fmt.Sprintf("result%d", nextResult))
		nextResult++
	}
	callExpr := r.goCallExpression(call)
	if len(assignments) == 0 {
		r.line("%s%s", indent, callExpr)
	} else {
		r.line("%s%s := %s", indent, strings.Join(assignments, ", "), callExpr)
	}
	switch call.ErrorCount {
	case 0:
	case 1:
		r.line("%sif goErr0 != nil { return nil, fgbGoError(%s, goErr0) }", indent, methodExpr)
	default:
		r.line("%svar fgbErrs []any", indent)
		for index := 0; index < call.ErrorCount; index++ {
			r.line("%sif goErr%d != nil { fgbErrs = append(fgbErrs, goErr%d.Error()) }", indent, index, index)
		}
		r.line("%sif len(fgbErrs) != 0 { return nil, fgbGoErrors(%s, fgbErrs) }", indent, methodExpr)
	}
}

func (r *goRenderer) renderDispatch() {
	r.line("func fgbDispatch(call fgbMethodCall) (any, *fgbCallError) {")
	r.line("\tswitch call.Method {")
	for _, call := range r.unit.Calls {
		r.line("\tcase %s:", strconv.Quote(call.WireName))
		argumentCount := len(call.Params)
		if call.Receiver != nil {
			argumentCount++
		}
		if argumentCount == 0 {
			r.line("\t\tif _, err := fgbRequireArgs(call.Arguments, 0); err != nil { return nil, fgbInvalidArguments(call.Method, err) }")
		} else {
			r.line("\t\targs, err := fgbRequireArgs(call.Arguments, %d)", argumentCount)
			r.line("\t\tif err != nil { return nil, fgbInvalidArguments(call.Method, err) }")
		}
		argOffset := 0
		if call.Receiver != nil {
			r.line("\t\treceiver, err := fgbDecode%d(args[0], \"receiver\")", call.Receiver.ID)
			r.line("\t\tif err != nil { return nil, fgbInvalidArguments(call.Method, err) }")
			argOffset = 1
		}
		for index, param := range call.Params {
			if param.Type.Kind == kindStreamSink && param.Type.ChannelStream {
				// Handled by renderStreamChannelSetup below.
				continue
			}
			r.line("\t\targ%d, err := fgbDecode%d(args[%d], %s)", index, param.Type.ID, index+argOffset, strconv.Quote(param.DartName))
			r.line("\t\tif err != nil { return nil, fgbInvalidArguments(call.Method, err) }")
		}
		r.renderStreamChannelSetup(call, "\t\t", func(index int) string {
			return fmt.Sprintf("fgbMustStreamHandle(args[%d])", index+argOffset)
		})
		r.renderGoCallStatement(call, "\t\t", "call.Method")
		switch len(call.Results) {
		case 0:
			r.line("\t\treturn nil, nil")
		case 1:
			r.line("\t\tencoded, err := fgbEncode%d(result0)", call.Results[0].Type.ID)
			r.line("\t\tif err != nil { return nil, &fgbCallError{Code: \"encode_error\", Message: err.Error(), Details: map[any]any{\"method\": call.Method}} }")
			r.line("\t\treturn encoded, nil")
		default:
			// Several results travel as one list and become a Dart record.
			for index, result := range call.Results {
				r.line("\t\tencoded%d, err := fgbEncode%d(result%d)", index, result.Type.ID, index)
				r.line("\t\tif err != nil { return nil, &fgbCallError{Code: \"encode_error\", Message: err.Error(), Details: map[any]any{\"method\": call.Method}} }")
			}
			encoded := make([]string, len(call.Results))
			for index := range call.Results {
				encoded[index] = fmt.Sprintf("encoded%d", index)
			}
			r.line("\t\treturn []any{%s}, nil", strings.Join(encoded, ", "))
		}
	}
	r.line("\tdefault:")
	r.raw("\t\treturn nil, &fgbCallError{Code: \"method_not_found\", Message: fmt.Sprintf(\"unknown method %q\", call.Method)}")
	r.line("\t}")
	r.line("}")
}

func (r *goRenderer) goCallExpression(call *callModel) string {
	var target string
	if call.Receiver == nil {
		target = call.GoTarget
	} else {
		target = "receiver." + call.GoTarget
	}
	// call.Params holds only the parameters that cross the wire; a
	// context.Context is supplied by the bridge and spliced back in here.
	total := len(call.Params)
	if call.ContextIndex >= 0 {
		total++
	}
	args := make([]string, 0, total)
	next := 0
	for position := 0; position < total; position++ {
		if position == call.ContextIndex {
			args = append(args, "fgbCtx")
			continue
		}
		args = append(args, fmt.Sprintf("arg%d", next))
		next++
	}
	return target + "(" + strings.Join(args, ", ") + ")"
}

// renderStreamChannelSetup emits the bridge-owned plumbing for `chan<- T`
// parameters and for a context.Context: the channel is created and drained
// here and closed once the call returns, and the context is cancelled as soon
// as the Dart side stops listening.
func (r *goRenderer) renderStreamChannelSetup(call *callModel, indent string, handleExpr func(index int) string) {
	streamHandle := ""
	for index, param := range call.Params {
		if param.Type.Kind != kindStreamSink {
			continue
		}
		// The handle is needed for the channel plumbing, and for tying a
		// context to the stream's lifetime.
		needsHandle := param.Type.ChannelStream || call.ContextIndex >= 0
		if needsHandle {
			r.line("%shandle%d := %s", indent, index, handleExpr(index))
			if streamHandle == "" {
				streamHandle = fmt.Sprintf("handle%d", index)
			}
		}
		if param.Type.ChannelStream {
			r.line("%sarg%d := fgbMakeStreamChannel%d(handle%d)", indent, index, param.Type.ID, index)
			r.line("%sdefer fgbCloseStreamChannel%d(arg%d)", indent, param.Type.ID, index)
		}
	}
	if call.ContextIndex < 0 {
		return
	}
	r.line("%sfgbCtx, fgbCancel := context.WithCancel(context.Background())", indent)
	r.line("%sdefer fgbCancel()", indent)
	if streamHandle != "" {
		// Cancelling the Dart subscription cancels the Go context, which is
		// how a cooperative producer learns to stop early. Capture the
		// generation once so the deferred cleanup cannot target a later one.
		r.line("%sfgbStreamGen := fgbCurrentStreamGeneration()", indent)
		r.line("%sfgbRegisterStreamCancel(fgbStreamGen, %s, fgbCancel)", indent, streamHandle)
		r.line("%sdefer fgbUnregisterStreamCancel(fgbStreamGen, %s)", indent, streamHandle)
	}
}

// renderStreamChannelHelpers emits the typed drain/close pair for one channel
// stream type.
func (r *goRenderer) renderStreamChannelHelpers(typ *wireType) {
	elemGo := r.goType(typ.Stream.Original)
	r.line("func fgbMakeStreamChannel%d(handle int64) chan %s {", typ.ID, elemGo)
	r.line("\t// Same generation guard as the sink factory: a hot restart retires")
	r.line("\t// this producer along with the isolate that started it.")
	r.line("\tgeneration := fgbCurrentStreamGeneration()")
	r.line("\tch := make(chan %s, 16)", elemGo)
	r.line("\tgo func() {")
	r.line("\t\t// Keep draining even after the Dart side stopped listening, so a")
	r.line("\t\t// producer that ignores ctx.Done() never blocks forever.")
	r.line("\t\tfor value := range ch {")
	r.line("\t\t\tencoded, err := fgbEncode%d(value)", typ.Stream.ID)
	r.line("\t\t\tif err != nil { continue }")
	r.line("\t\t\tfgbPostStreamEvent(generation, handle, 0, encoded)")
	r.line("\t\t}")
	r.line("\t\tfgbReleaseStreamSink(generation, handle)")
	r.line("\t}()")
	r.line("\treturn ch")
	r.line("}")
	r.line("")
	r.line("// fgbCloseStreamChannel%d ends the stream once the call returns; a user", typ.ID)
	r.line("// function that closed the channel itself is tolerated.")
	r.line("func fgbCloseStreamChannel%d(ch chan %s) {", typ.ID, elemGo)
	r.line("\tdefer func() { _ = recover() }()")
	r.line("\tclose(ch)")
	r.line("}")
}

func (r *goRenderer) renderSignedRangeCheck(typ *wireType, goType string) {
	switch typ.BasicKind {
	case types.Int8:
		r.line("\tif raw < -128 || raw > 127 { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of int8 range\", path) }", goType)
	case types.Int16:
		r.line("\tif raw < -32768 || raw > 32767 { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of int16 range\", path) }", goType)
	case types.Int32:
		r.line("\tif raw < -2147483648 || raw > 2147483647 { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of int32 range\", path) }", goType)
	case types.Int:
		r.line("\tif int64(int(raw)) != raw { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of int range\", path) }", goType)
	}
}

func (r *goRenderer) renderUnsignedRangeCheck(typ *wireType, goType string) {
	switch typ.BasicKind {
	case types.Uint8:
		r.line("\tif raw > 255 { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of uint8 range\", path) }", goType)
	case types.Uint16:
		r.line("\tif raw > 65535 { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of uint16 range\", path) }", goType)
	case types.Uint32:
		r.line("\tif raw > 4294967295 { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of uint32 range\", path) }", goType)
	case types.Uint, types.Uintptr:
		r.line("\tif uint64(%s(raw)) != raw { var zero %s; return zero, fmt.Errorf(\"%%s: integer out of %s range\", path) }", goType, goType, goType)
	}
}

func (r *goRenderer) renderBigIntDecoder(typ *wireType, goType string) {
	_, pointer := typ.Original.(*types.Pointer)
	if pointer {
		r.line("\tif value == nil { return nil, nil }")
	}
	r.line("\tvar parsed *big.Int")
	r.line("\tswitch raw := value.(type) {")
	r.line("\tcase *big.Int:")
	r.line("\t\tparsed = new(big.Int).Set(raw)")
	r.line("\tcase string:")
	r.line("\t\tvar ok bool")
	r.line("\t\tparsed, ok = new(big.Int).SetString(raw, 16)")
	r.line("\t\tif !ok { var zero %s; return zero, fmt.Errorf(\"%%s: invalid hexadecimal BigInt\", path) }", goType)
	r.line("\tdefault:")
	r.line("\t\tvar zero %s; return zero, fgbTypeError(path, \"BigInt hexadecimal string\", value)", goType)
	r.line("\t}")
	if pointer {
		r.line("\treturn parsed, nil")
	} else {
		r.line("\treturn *parsed, nil")
	}
}

func (r *goRenderer) renderBigIntEncoder(typ *wireType) {
	_, pointer := typ.Original.(*types.Pointer)
	if pointer {
		r.line("\tif value == nil { return nil, nil }")
		r.line("\treturn new(big.Int).Set(value), nil")
	} else {
		r.line("\treturn new(big.Int).Set(&value), nil")
	}
}

func (r *goRenderer) renderDurationFromMicroseconds(goType, expression string) {
	r.line("\tconst maxDurationMicroseconds = int64(^uint64(0)>>1) / int64(time.Microsecond)")
	r.line("\tif %s < -maxDurationMicroseconds || %s > maxDurationMicroseconds { var zero %s; return zero, fmt.Errorf(\"%%s: duration out of time.Duration range\", path) }", expression, expression, goType)
	r.line("\treturn %s(%s) * %s(time.Microsecond), nil", goType, expression, goType)
}

func (r *goRenderer) goType(typ types.Type) string {
	return types.TypeString(typ, func(pkg *types.Package) string {
		if pkg == nil {
			return ""
		}
		if pkg.Path() == r.unit.PackagePath {
			if r.unit.Direct {
				return ""
			}
			return "api"
		}
		switch pkg.Path() {
		case "time":
			return "time"
		case "math/big":
			return "big"
		case r.unit.SupportPackagePath:
			return "fgbrt"
		case "sync/atomic":
			return "atomic"
		default:
			if alias := r.unit.GoPackageAliases[pkg.Path()]; alias != "" {
				return alias
			}
			return pkg.Name()
		}
	})
}

func (r *goRenderer) line(format string, args ...any) {
	if len(args) == 0 {
		r.buffer.WriteString(format)
	} else {
		fmt.Fprintf(&r.buffer, format, args...)
	}
	r.buffer.WriteByte('\n')
}

func (r *goRenderer) raw(value string) {
	r.buffer.WriteString(value)
	r.buffer.WriteByte('\n')
}
