package generator

import (
	_ "embed"
	"os"
	"path/filepath"
	"strings"

	"github.com/star4277/flutter-go-bridge-gokit/internal/config"
)

// supportPackageDirName is the directory - and package - holding the types a
// bridged Go API needs in its signatures. It sits under `internal` next to the
// generated bridge, inside the user's own module: no external dependency is
// required, and Go's internal rule keeps it out of their public API surface.
var supportPackageDirParts = []string{"internal", "fgb"}

const supportPackageFileName = "fgb_generated.go"

// supportPackageSource is the single source of truth for those types. Keeping
// it as a real package (rather than a string literal) means the compiler and
// the repository's own tests check it.
//
//go:embed gosupport/fgb.go
var supportPackageSource string

const supportPackageHeader = "// Code generated by flutter_go_bridge_codegen. DO NOT EDIT.\n\n"

// SupportPackageDir is where the support package is written for a resolved
// configuration: `internal/fgb` next to the generated Go bridge.
func SupportPackageDir(resolved config.Resolved) string {
	parts := append([]string{filepath.Dir(resolved.GoOutput)}, supportPackageDirParts...)
	return filepath.Join(parts...)
}

// WriteSupportPackage emits the support package. It must run before the Go
// input is parsed: an API that references the package cannot even be loaded
// until the package exists on disk. The content is static, so this is safe to
// do up front, and rewriting it on every run keeps it in lockstep with the
// generated bridge - the two share an internal contract.
func WriteSupportPackage(resolved config.Resolved) (string, error) {
	dir := SupportPackageDir(resolved)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, supportPackageFileName)
	content := []byte(supportPackageHeader + supportPackageSource)
	if existing, err := os.ReadFile(path); err == nil && string(existing) == string(content) {
		return path, nil
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// supportPackageImportPath derives the import path of the support package from
// the module that owns it, so generated code and user code agree on one path.
// It returns "" when the module cannot be determined, which simply disables
// support-type detection.
func supportPackageImportPath(modulePath, moduleDir, supportDir string) string {
	if modulePath == "" || moduleDir == "" {
		return ""
	}
	relative, err := filepath.Rel(moduleDir, supportDir)
	if err != nil {
		return ""
	}
	relative = filepath.ToSlash(relative)
	if relative == "." {
		return modulePath
	}
	if strings.HasPrefix(relative, "../") {
		// The support package lives outside the module that declares the API;
		// there is no import path we could rely on.
		return ""
	}
	return modulePath + "/" + relative
}
